// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const AudienceCodeType = {
  "01": "OnixAudienceCodes",
  "02": "Proprietary",
  "03": "MpaaRating",
  "04": "BbfcRating",
  "05": "FskRating",
  "06": "BtlfAudienceCode",
  "07": "ElectreAudienceCode",
  "08": "AneleTipo",
  "09": "Avi",
  "10": "UskRating",
  "11": "Aws",
  "12": "Schulform",
  "13": "Bundesland",
  "14": "Ausbildungsberuf",
  "15": "SuomalainenKouluasteluokitus",
  "16": "CbgAgeGuidance",
  "17": "NielsenBookAudienceCode",
  "18": "AviRevised",
  "19": "LexileMeasure",
  "20": "FryReadabilityScore",
  "21": "JapaneseChildrenSAudienceCode",
  "22": "OnixAdultAudienceRating",
  "23": "CommonEuropeanFrameworkOfReferenceForLanguageLearningCefr",
  "24": "KoreanPublicationEthicsCommissionRating",
  "25": "IoEBookBand",
  "26": "FskLehrInfoprogramm",
  "27": "IntendedAudienceLanguage",
  "28": "PegiRating",
  "29": "Gymnasieprogram",
};

export enum AudienceCodeTypeEnum {
  OnixAudienceCodes = "OnixAudienceCodes",
  Proprietary = "Proprietary",
  MpaaRating = "MpaaRating",
  BbfcRating = "BbfcRating",
  FskRating = "FskRating",
  BtlfAudienceCode = "BtlfAudienceCode",
  ElectreAudienceCode = "ElectreAudienceCode",
  AneleTipo = "AneleTipo",
  Avi = "Avi",
  UskRating = "UskRating",
  Aws = "Aws",
  Schulform = "Schulform",
  Bundesland = "Bundesland",
  Ausbildungsberuf = "Ausbildungsberuf",
  SuomalainenKouluasteluokitus = "SuomalainenKouluasteluokitus",
  CbgAgeGuidance = "CbgAgeGuidance",
  NielsenBookAudienceCode = "NielsenBookAudienceCode",
  AviRevised = "AviRevised",
  LexileMeasure = "LexileMeasure",
  FryReadabilityScore = "FryReadabilityScore",
  JapaneseChildrenSAudienceCode = "JapaneseChildrenSAudienceCode",
  OnixAdultAudienceRating = "OnixAdultAudienceRating",
  CommonEuropeanFrameworkOfReferenceForLanguageLearningCefr = "CommonEuropeanFrameworkOfReferenceForLanguageLearningCefr",
  KoreanPublicationEthicsCommissionRating = "KoreanPublicationEthicsCommissionRating",
  IoEBookBand = "IoEBookBand",
  FskLehrInfoprogramm = "FskLehrInfoprogramm",
  IntendedAudienceLanguage = "IntendedAudienceLanguage",
  PegiRating = "PegiRating",
  Gymnasieprogram = "Gymnasieprogram"
}
  