export const AudienceRangeQualifier = {
  "11": "UsSchoolGradeRange",
  "12": "UkSchoolGrade",
  "15": "ReadingSpeedWordsPerMinute",
  "16": "InterestAgeMonths",
  "17": "InterestAgeYears",
  "18": "ReadingAgeYears",
  "19": "SpanishSchoolGrade",
  "20": "Skoletrinn",
  "21": "Niv",
  "22": "ItalianSchoolGrade",
  "23": "Schulform",
  "24": "Bundesland",
  "25": "Ausbildungsberuf",
  "26": "CanadianSchoolGradeRange",
  "27": "FinnishSchoolGradeRange",
  "28": "FinnishUpperSecondarySchoolCourse",
  "29": "ChineseSchoolGradeRange",
  "30": "NomenclatureNiveauxDucatifDTaill",
  "31": "BrazilEducationLevel",
  "32": "NomenclatureNiveauxDucatifDeBase",
  "33": "FinnishUpperSecondarySchoolCourse_2021",
};

export enum AudienceRangeQualifierEnum {
  UsSchoolGradeRange,
  UkSchoolGrade,
  ReadingSpeedWordsPerMinute,
  InterestAgeMonths,
  InterestAgeYears,
  ReadingAgeYears,
  SpanishSchoolGrade,
  Skoletrinn,
  Niv,
  ItalianSchoolGrade,
  Schulform,
  Bundesland,
  Ausbildungsberuf,
  CanadianSchoolGradeRange,
  FinnishSchoolGradeRange,
  FinnishUpperSecondarySchoolCourse,
  ChineseSchoolGradeRange,
  NomenclatureNiveauxDucatifDTaill,
  BrazilEducationLevel,
  NomenclatureNiveauxDucatifDeBase,
  FinnishUpperSecondarySchoolCourse_2021
}
