export const BibleContents = {
  "AP": "ApocryphaCatholicCanon",
  "AQ": "ApocryphaCanonUnspecified",
  "AX": "AdditionalApocryphalTextsGreekOrthodoxCanon",
  "AY": "AdditionalApocryphalTextsSlavonicOrthodoxCanon",
  "AZ": "AdditionalApocryphalTexts",
  "GA": "GeneralCanonWithApocryphaCatholicCanon",
  "GC": "GeneralCanonWithApocryphalTextsCanonUnspecified",
  "GE": "GeneralCanon",
  "GS": "Gospels",
  "OT": "OldTestament",
  "NT": "NewTestament",
  "NP": "NewTestamentWithPsalmsAndProverbs",
  "PE": "PaulSEpistles",
  "PP": "PsalmsAndProverbs",
  "PS": "Psalms",
  "PT": "Pentateuch",
  "ZZ": "OtherPortions",
};
