export const BibleContents = {
  "AP": "ApocryphaCatholicCanon",
  "AQ": "ApocryphaCanonUnspecified",
  "AX": "AdditionalApocryphalTextsGreekOrthodoxCanon",
  "AY": "AdditionalApocryphalTextsSlavonicOrthodoxCanon",
  "AZ": "AdditionalApocryphalTexts",
  "GA": "GeneralCanonWithApocryphaCatholicCanon",
  "GC": "GeneralCanonWithApocryphalTextsCanonUnspecified",
  "GE": "GeneralCanon",
  "GS": "Gospels",
  "OT": "OldTestament",
  "NT": "NewTestament",
  "NP": "NewTestamentWithPsalmsAndProverbs",
  "PE": "PaulSEpistles",
  "PP": "PsalmsAndProverbs",
  "PS": "Psalms",
  "PT": "Pentateuch",
  "ZZ": "OtherPortions",
};

export enum BibleContentsEnum {
  ApocryphaCatholicCanon,
  ApocryphaCanonUnspecified,
  AdditionalApocryphalTextsGreekOrthodoxCanon,
  AdditionalApocryphalTextsSlavonicOrthodoxCanon,
  AdditionalApocryphalTexts,
  GeneralCanonWithApocryphaCatholicCanon,
  GeneralCanonWithApocryphalTextsCanonUnspecified,
  GeneralCanon,
  Gospels,
  OldTestament,
  NewTestament,
  NewTestamentWithPsalmsAndProverbs,
  PaulSEpistles,
  PsalmsAndProverbs,
  Psalms,
  Pentateuch,
  OtherPortions
}
