// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const BibleVersion = {
  "ALV": "AlbertoVaccari",
  "AMP": "Amplified",
  "ANM": "AntonioMartini",
  "ASV": "AmericanStandard",
  "CEB": "CommonEnglishBible",
  "CEI": "ConferenzaEpiscopaleItaliana",
  "CEN": "ConferenzaEpiscopaleItaliana_2008",
  "CEV": "ContemporaryEnglish",
  "CNC": "Concordata",
  "DDI": "Diodati",
  "DDN": "NuovaDiodati",
  "DOU": "DouayRheims",
  "EIN": "EinheitsBersetzung",
  "ESV": "EnglishStandard",
  "FBB": "Biblia_1776",
  "FRA": "Raamattu_1933_1938",
  "FRK": "RaamattuKansalle",
  "FRM": "Raamattu_1992",
  "GDW": "GodSWord",
  "GEN": "Geneva",
  "GNB": "GoodNews",
  "GPR": "GalbiatiPennaRossanoUtet",
  "GRK": "OriginalGreek",
  "GRM": "GarofanoRinaldiMarietti",
  "HBR": "OriginalHebrew",
  "HCS": "HolmanChristianStandard",
  "ICB": "InternationalChildrenS",
  "ILC": "TraduzioneInterconfessionaleInLinguaCorrente",
  "JER": "Jerusalem",
  "KJV": "KingJames",
  "KJT": "21stCenturyKingJames",
  "LVB": "LivingBible",
  "LZZ": "Luzzi",
  "MSG": "MessageBible",
  "NAB": "NewAmerican",
  "NAS": "NewAmericanStandard",
  "NAU": "NewAmericanStandardUpdated",
  "NBA": "Bibelen_1895",
  "NBB": "Bibelen_1930",
  "NBC": "Bibelen_1938",
  "NBD": "Bibelen_1978_85",
  "NBE": "Bibelen_1978",
  "NBF": "Bibelen_1985",
  "NBG": "Bibelen_1988",
  "NBH": "Bibelen_1978_85Rev_2005",
  "NBI": "Bibelen_2011",
  "NCV": "NewCentury",
  "NEB": "NewEnglish",
  "NGO": "BibelenGudsOrd",
  "NIV": "NewInternational",
  "NIR": "NewInternationalReaderS",
  "NJB": "NewJerusalem",
  "NKJ": "NewKingJames",
  "NNK": "BibelenNynorsk",
  "NLV": "NewLiving",
  "NRS": "NewRevisedStandard",
  "NTV": "NuevaTraduccionVivienta",
  "NVB": "NovissimaVersioneDellaBibbia",
  "NVD": "NuevaBibliaAlDia",
  "NVI": "NuevaVersionInternacional",
  "PHP": "NewTestamentInModernEnglishPhillips",
  "REB": "RevisedEnglish",
  "REV": "RevisedVersion",
  "RSV": "RevisedStandard",
  "RVL": "ReinaValera",
  "SBB": "Bibel_2000",
  "SMK": "BibelenSamisk",
  "TEV": "TodaySEnglish",
  "TNI": "TodaySNewInternational",
  "ZZZ": "Other",
};

export enum BibleVersionEnum {
  AlbertoVaccari = "AlbertoVaccari",
  Amplified = "Amplified",
  AntonioMartini = "AntonioMartini",
  AmericanStandard = "AmericanStandard",
  CommonEnglishBible = "CommonEnglishBible",
  ConferenzaEpiscopaleItaliana = "ConferenzaEpiscopaleItaliana",
  ConferenzaEpiscopaleItaliana_2008 = "ConferenzaEpiscopaleItaliana_2008",
  ContemporaryEnglish = "ContemporaryEnglish",
  Concordata = "Concordata",
  Diodati = "Diodati",
  NuovaDiodati = "NuovaDiodati",
  DouayRheims = "DouayRheims",
  EinheitsBersetzung = "EinheitsBersetzung",
  EnglishStandard = "EnglishStandard",
  Biblia_1776 = "Biblia_1776",
  Raamattu_1933_1938 = "Raamattu_1933_1938",
  RaamattuKansalle = "RaamattuKansalle",
  Raamattu_1992 = "Raamattu_1992",
  GodSWord = "GodSWord",
  Geneva = "Geneva",
  GoodNews = "GoodNews",
  GalbiatiPennaRossanoUtet = "GalbiatiPennaRossanoUtet",
  OriginalGreek = "OriginalGreek",
  GarofanoRinaldiMarietti = "GarofanoRinaldiMarietti",
  OriginalHebrew = "OriginalHebrew",
  HolmanChristianStandard = "HolmanChristianStandard",
  InternationalChildrenS = "InternationalChildrenS",
  TraduzioneInterconfessionaleInLinguaCorrente = "TraduzioneInterconfessionaleInLinguaCorrente",
  Jerusalem = "Jerusalem",
  KingJames = "KingJames",
  "21stCenturyKingJames" = "21stCenturyKingJames",
  LivingBible = "LivingBible",
  Luzzi = "Luzzi",
  MessageBible = "MessageBible",
  NewAmerican = "NewAmerican",
  NewAmericanStandard = "NewAmericanStandard",
  NewAmericanStandardUpdated = "NewAmericanStandardUpdated",
  Bibelen_1895 = "Bibelen_1895",
  Bibelen_1930 = "Bibelen_1930",
  Bibelen_1938 = "Bibelen_1938",
  Bibelen_1978_85 = "Bibelen_1978_85",
  Bibelen_1978 = "Bibelen_1978",
  Bibelen_1985 = "Bibelen_1985",
  Bibelen_1988 = "Bibelen_1988",
  Bibelen_1978_85Rev_2005 = "Bibelen_1978_85Rev_2005",
  Bibelen_2011 = "Bibelen_2011",
  NewCentury = "NewCentury",
  NewEnglish = "NewEnglish",
  BibelenGudsOrd = "BibelenGudsOrd",
  NewInternational = "NewInternational",
  NewInternationalReaderS = "NewInternationalReaderS",
  NewJerusalem = "NewJerusalem",
  NewKingJames = "NewKingJames",
  BibelenNynorsk = "BibelenNynorsk",
  NewLiving = "NewLiving",
  NewRevisedStandard = "NewRevisedStandard",
  NuevaTraduccionVivienta = "NuevaTraduccionVivienta",
  NovissimaVersioneDellaBibbia = "NovissimaVersioneDellaBibbia",
  NuevaBibliaAlDia = "NuevaBibliaAlDia",
  NuevaVersionInternacional = "NuevaVersionInternacional",
  NewTestamentInModernEnglishPhillips = "NewTestamentInModernEnglishPhillips",
  RevisedEnglish = "RevisedEnglish",
  RevisedVersion = "RevisedVersion",
  RevisedStandard = "RevisedStandard",
  ReinaValera = "ReinaValera",
  Bibel_2000 = "Bibel_2000",
  BibelenSamisk = "BibelenSamisk",
  TodaySEnglish = "TodaySEnglish",
  TodaySNewInternational = "TodaySNewInternational",
  Other = "Other"
}
  