// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const BiblePurpose = {
  "AW": "Award",
  "BB": "Baby",
  "BR": "Bride",
  "CF": "Confirmation",
  "CH": "ChildrenS",
  "CM": "Compact",
  "CR": "CrossReference",
  "DR": "DailyReadings",
  "DV": "Devotional",
  "FM": "Family",
  "GT": "GeneralText",
  "GF": "Gift",
  "LP": "LecternPulpit",
  "MN": "MenS",
  "PS": "PrimarySchool",
  "PW": "Pew",
  "SC": "Scholarly",
  "SL": "Slimline",
  "ST": "Student",
  "SU": "Study",
  "WG": "WeddingGift",
  "WM": "WomenS",
  "YT": "Youth",
};

export enum BiblePurposeEnum {
  Award = "Award",
  Baby = "Baby",
  Bride = "Bride",
  Confirmation = "Confirmation",
  ChildrenS = "ChildrenS",
  Compact = "Compact",
  CrossReference = "CrossReference",
  DailyReadings = "DailyReadings",
  Devotional = "Devotional",
  Family = "Family",
  GeneralText = "GeneralText",
  Gift = "Gift",
  LecternPulpit = "LecternPulpit",
  MenS = "MenS",
  PrimarySchool = "PrimarySchool",
  Pew = "Pew",
  Scholarly = "Scholarly",
  Slimline = "Slimline",
  Student = "Student",
  Study = "Study",
  WeddingGift = "WeddingGift",
  WomenS = "WomenS",
  Youth = "Youth"
}
  