export const BiblePurpose = {
  "AW": "Award",
  "BB": "Baby",
  "BR": "Bride",
  "CF": "Confirmation",
  "CH": "ChildrenS",
  "CM": "Compact",
  "CR": "CrossReference",
  "DR": "DailyReadings",
  "DV": "Devotional",
  "FM": "Family",
  "GT": "GeneralText",
  "GF": "Gift",
  "LP": "LecternPulpit",
  "MN": "MenS",
  "PS": "PrimarySchool",
  "PW": "Pew",
  "SC": "Scholarly",
  "SL": "Slimline",
  "ST": "Student",
  "SU": "Study",
  "WG": "WeddingGift",
  "WM": "WomenS",
  "YT": "Youth",
};
