export const BibleVersion = {
  "ALV": "AlbertoVaccari",
  "AMP": "Amplified",
  "ANM": "AntonioMartini",
  "ASV": "AmericanStandard",
  "CEB": "CommonEnglishBible",
  "CEI": "ConferenzaEpiscopaleItaliana",
  "CEN": "ConferenzaEpiscopaleItaliana_2008",
  "CEV": "ContemporaryEnglish",
  "CNC": "Concordata",
  "DDI": "Diodati",
  "DDN": "NuovaDiodati",
  "DOU": "DouayRheims",
  "EIN": "EinheitsBersetzung",
  "ESV": "EnglishStandard",
  "FBB": "Biblia_1776",
  "FRA": "Raamattu_1933_1938",
  "FRK": "RaamattuKansalle",
  "FRM": "Raamattu_1992",
  "GDW": "GodSWord",
  "GEN": "Geneva",
  "GNB": "GoodNews",
  "GPR": "GalbiatiPennaRossanoUtet",
  "GRK": "OriginalGreek",
  "GRM": "GarofanoRinaldiMarietti",
  "HBR": "OriginalHebrew",
  "HCS": "HolmanChristianStandard",
  "ICB": "InternationalChildrenS",
  "ILC": "TraduzioneInterconfessionaleInLinguaCorrente",
  "JER": "Jerusalem",
  "KJV": "KingJames",
  "KJT": "21stCenturyKingJames",
  "LVB": "LivingBible",
  "LZZ": "Luzzi",
  "MSG": "MessageBible",
  "NAB": "NewAmerican",
  "NAS": "NewAmericanStandard",
  "NAU": "NewAmericanStandardUpdated",
  "NBA": "Bibelen_1895",
  "NBB": "Bibelen_1930",
  "NBC": "Bibelen_1938",
  "NBD": "Bibelen_1978_85",
  "NBE": "Bibelen_1978",
  "NBF": "Bibelen_1985",
  "NBG": "Bibelen_1988",
  "NBH": "Bibelen_1978_85Rev_2005",
  "NBI": "Bibelen_2011",
  "NCV": "NewCentury",
  "NEB": "NewEnglish",
  "NGO": "BibelenGudsOrd",
  "NIV": "NewInternational",
  "NIR": "NewInternationalReaderS",
  "NJB": "NewJerusalem",
  "NKJ": "NewKingJames",
  "NNK": "BibelenNynorsk",
  "NLV": "NewLiving",
  "NRS": "NewRevisedStandard",
  "NTV": "NuevaTraduccionVivienta",
  "NVB": "NovissimaVersioneDellaBibbia",
  "NVD": "NuevaBibliaAlDia",
  "NVI": "NuevaVersionInternacional",
  "PHP": "NewTestamentInModernEnglishPhillips",
  "REB": "RevisedEnglish",
  "REV": "RevisedVersion",
  "RSV": "RevisedStandard",
  "RVL": "ReinaValera",
  "SBB": "Bibel_2000",
  "SMK": "BibelenSamisk",
  "TEV": "TodaySEnglish",
  "TNI": "TodaySNewInternational",
  "ZZZ": "Other",
};

export enum BibleVersionEnum {
  AlbertoVaccari,
  Amplified,
  AntonioMartini,
  AmericanStandard,
  CommonEnglishBible,
  ConferenzaEpiscopaleItaliana,
  ConferenzaEpiscopaleItaliana_2008,
  ContemporaryEnglish,
  Concordata,
  Diodati,
  NuovaDiodati,
  DouayRheims,
  EinheitsBersetzung,
  EnglishStandard,
  Biblia_1776,
  Raamattu_1933_1938,
  RaamattuKansalle,
  Raamattu_1992,
  GodSWord,
  Geneva,
  GoodNews,
  GalbiatiPennaRossanoUtet,
  OriginalGreek,
  GarofanoRinaldiMarietti,
  OriginalHebrew,
  HolmanChristianStandard,
  InternationalChildrenS,
  TraduzioneInterconfessionaleInLinguaCorrente,
  Jerusalem,
  KingJames,
  "21stCenturyKingJames",
  LivingBible,
  Luzzi,
  MessageBible,
  NewAmerican,
  NewAmericanStandard,
  NewAmericanStandardUpdated,
  Bibelen_1895,
  Bibelen_1930,
  Bibelen_1938,
  Bibelen_1978_85,
  Bibelen_1978,
  Bibelen_1985,
  Bibelen_1988,
  Bibelen_1978_85Rev_2005,
  Bibelen_2011,
  NewCentury,
  NewEnglish,
  BibelenGudsOrd,
  NewInternational,
  NewInternationalReaderS,
  NewJerusalem,
  NewKingJames,
  BibelenNynorsk,
  NewLiving,
  NewRevisedStandard,
  NuevaTraduccionVivienta,
  NovissimaVersioneDellaBibbia,
  NuevaBibliaAlDia,
  NuevaVersionInternacional,
  NewTestamentInModernEnglishPhillips,
  RevisedEnglish,
  RevisedVersion,
  RevisedStandard,
  ReinaValera,
  Bibel_2000,
  BibelenSamisk,
  TodaySEnglish,
  TodaySNewInternational,
  Other
}
