// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const BindingOrPageEdgeColor = {
  "BLK": "Black",
  "BLU": "Blue",
  "BRN": "Brown",
  "BUR": "BurgundyMaroon",
  "CEL": "CeladonPaleGreen",
  "CRE": "Cream",
  "FCO": "FourColor",
  "FCS": "FourColorAndSpotColor",
  "GLD": "Gold",
  "GRN": "Green",
  "GRY": "Grey",
  "MUL": "Multicolor",
  "NAV": "NavyDarkBlue",
  "ORG": "Orange",
  "PNK": "Pink",
  "PUR": "Purple",
  "RED": "Red",
  "SKY": "SkyPaleBlue",
  "SLV": "Silver",
  "TAN": "TanLightBrown",
  "TEA": "TealTurquoiseGreen",
  "WHI": "White",
  "YEL": "Yellow",
  "ZZZ": "Other",
};

export enum BindingOrPageEdgeColorEnum {
  Black,
  Blue,
  Brown,
  BurgundyMaroon,
  CeladonPaleGreen,
  Cream,
  FourColor,
  FourColorAndSpotColor,
  Gold,
  Green,
  Grey,
  Multicolor,
  NavyDarkBlue,
  Orange,
  Pink,
  Purple,
  Red,
  SkyPaleBlue,
  Silver,
  TanLightBrown,
  TealTurquoiseGreen,
  White,
  Yellow,
  Other
}
  