// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const BindingOrPageEdgeColor = {
  "BLK": "Black",
  "BLU": "Blue",
  "BRN": "Brown",
  "BUR": "BurgundyMaroon",
  "CEL": "CeladonPaleGreen",
  "CRE": "Cream",
  "FCO": "FourColor",
  "FCS": "FourColorAndSpotColor",
  "GLD": "Gold",
  "GRN": "Green",
  "GRY": "Grey",
  "MUL": "Multicolor",
  "NAV": "NavyDarkBlue",
  "ORG": "Orange",
  "PNK": "Pink",
  "PUR": "Purple",
  "RED": "Red",
  "SKY": "SkyPaleBlue",
  "SLV": "Silver",
  "TAN": "TanLightBrown",
  "TEA": "TealTurquoiseGreen",
  "WHI": "White",
  "YEL": "Yellow",
  "ZZZ": "Other",
};

export enum BindingOrPageEdgeColorEnum {
  Black = "Black",
  Blue = "Blue",
  Brown = "Brown",
  BurgundyMaroon = "BurgundyMaroon",
  CeladonPaleGreen = "CeladonPaleGreen",
  Cream = "Cream",
  FourColor = "FourColor",
  FourColorAndSpotColor = "FourColorAndSpotColor",
  Gold = "Gold",
  Green = "Green",
  Grey = "Grey",
  Multicolor = "Multicolor",
  NavyDarkBlue = "NavyDarkBlue",
  Orange = "Orange",
  Pink = "Pink",
  Purple = "Purple",
  Red = "Red",
  SkyPaleBlue = "SkyPaleBlue",
  Silver = "Silver",
  TanLightBrown = "TanLightBrown",
  TealTurquoiseGreen = "TealTurquoiseGreen",
  White = "White",
  Yellow = "Yellow",
  Other = "Other"
}
  