export const ContributorRoleCode = {
  "A01": "ByAuthor",
  "A02": "With",
  "A03": "ScreenplayBy",
  "A04": "LibrettoBy",
  "A05": "LyricsBy",
  "A06": "ByComposer",
  "A07": "ByArtist",
  "A08": "ByPhotographer",
  "A09": "CreatedBy",
  "A10": "FromAnIdeaBy",
  "A11": "DesignedBy",
  "A12": "IllustratedBy",
  "A13": "PhotographsBy",
  "A14": "TextBy",
  "A15": "PrefaceBy",
  "A16": "PrologueBy",
  "A17": "SummaryBy",
  "A18": "SupplementBy",
  "A19": "AfterwordBy",
  "A20": "NotesBy",
  "A21": "CommentariesBy",
  "A22": "EpilogueBy",
  "A23": "ForewordBy",
  "A24": "IntroductionBy",
  "A25": "FootnotesBy",
  "A26": "MemoirBy",
  "A27": "ExperimentsBy",
  "A29": "IntroductionAndNotesBy",
  "A30": "SoftwareWrittenBy",
  "A31": "BookAndLyricsBy",
  "A32": "ContributionsBy",
  "A33": "AppendixBy",
  "A34": "IndexBy",
  "A35": "DrawingsBy",
  "A36": "CoverDesignOrArtworkBy",
  "A37": "PreliminaryWorkBy",
  "A38": "OriginalAuthor",
  "A39": "MapsBy",
  "A40": "InkedOrColoredBy",
  "A41": "PaperEngineeringBy",
  "A42": "ContinuedBy",
  "A43": "Interviewer",
  "A44": "Interviewee",
  "A45": "ComicScriptBy",
  "A46": "Inker",
  "A47": "Colorist",
  "A48": "Letterer",
  "A51": "ResearchBy",
  "A99": "OtherPrimaryCreator",
  "B01": "EditedBy",
  "B02": "RevisedBy",
  "B03": "RetoldBy",
  "B04": "AbridgedBy",
  "B05": "AdaptedBy",
  "B06": "TranslatedBy",
  "B07": "AsToldBy",
  "B08": "TranslatedWithCommentaryBy",
  "B09": "SeriesEditedBy",
  "B10": "EditedAndTranslatedBy",
  "B11": "EditorInChief",
  "B12": "GuestEditor",
  "B13": "VolumeEditor",
  "B14": "EditorialBoardMember",
  "B15": "EditorialCoordinationBy",
  "B16": "ManagingEditor",
  "B17": "FoundedBy",
  "B18": "PreparedForPublicationBy",
  "B19": "AssociateEditor",
  "B20": "ConsultantEditor",
  "B21": "GeneralEditor",
  "B22": "DramatizedBy",
  "B23": "GeneralRapporteur",
  "B24": "LiteraryEditor",
  "B25": "ArrangedByMusic",
  "B26": "TechnicalEditor",
  "B27": "ThesisAdvisorOrSupervisor",
  "B28": "ThesisExaminer",
  "B29": "ScientificEditor",
  "B30": "HistoricalAdvisor",
  "B31": "OriginalEditor",
  "B32": "TranslationRevisedBy",
  "B99": "OtherAdaptationBy",
  "C01": "CompiledBy",
  "C02": "SelectedBy",
  "C03": "NonTextMaterialSelectedBy",
  "C04": "CuratedBy",
  "C99": "OtherCompilationBy",
  "D01": "Producer",
  "D02": "Director",
  "D03": "Conductor",
  "D04": "Choreographer",
  "D99": "OtherDirectionBy",
  "E01": "Actor",
  "E02": "Dancer",
  "E03": "Narrator",
  "E04": "Commentator",
  "E05": "VocalSoloist",
  "E06": "InstrumentalSoloist",
  "E07": "ReadBy",
  "E08": "PerformedByOrchestraBandEnsemble",
  "E09": "Speaker",
  "E10": "Presenter",
  "E99": "PerformedBy",
  "F01": "FilmedPhotographedBy",
  "F02": "EditorFilmOrVideo",
  "F99": "OtherRecordingBy",
  "Z01": "AssistedBy",
  "Z02": "HonoredDedicatedTo",
  "Z03": "EnactingJurisdiction",
  "Z04": "PeerReviewed",
  "Z98": "VariousRoles",
  "Z99": "Other",
};

export enum ContributorRoleCodeEnum {
  ByAuthor,
  With,
  ScreenplayBy,
  LibrettoBy,
  LyricsBy,
  ByComposer,
  ByArtist,
  ByPhotographer,
  CreatedBy,
  FromAnIdeaBy,
  DesignedBy,
  IllustratedBy,
  PhotographsBy,
  TextBy,
  PrefaceBy,
  PrologueBy,
  SummaryBy,
  SupplementBy,
  AfterwordBy,
  NotesBy,
  CommentariesBy,
  EpilogueBy,
  ForewordBy,
  IntroductionBy,
  FootnotesBy,
  MemoirBy,
  ExperimentsBy,
  IntroductionAndNotesBy,
  SoftwareWrittenBy,
  BookAndLyricsBy,
  ContributionsBy,
  AppendixBy,
  IndexBy,
  DrawingsBy,
  CoverDesignOrArtworkBy,
  PreliminaryWorkBy,
  OriginalAuthor,
  MapsBy,
  InkedOrColoredBy,
  PaperEngineeringBy,
  ContinuedBy,
  Interviewer,
  Interviewee,
  ComicScriptBy,
  Inker,
  Colorist,
  Letterer,
  ResearchBy,
  OtherPrimaryCreator,
  EditedBy,
  RevisedBy,
  RetoldBy,
  AbridgedBy,
  AdaptedBy,
  TranslatedBy,
  AsToldBy,
  TranslatedWithCommentaryBy,
  SeriesEditedBy,
  EditedAndTranslatedBy,
  EditorInChief,
  GuestEditor,
  VolumeEditor,
  EditorialBoardMember,
  EditorialCoordinationBy,
  ManagingEditor,
  FoundedBy,
  PreparedForPublicationBy,
  AssociateEditor,
  ConsultantEditor,
  GeneralEditor,
  DramatizedBy,
  GeneralRapporteur,
  LiteraryEditor,
  ArrangedByMusic,
  TechnicalEditor,
  ThesisAdvisorOrSupervisor,
  ThesisExaminer,
  ScientificEditor,
  HistoricalAdvisor,
  OriginalEditor,
  TranslationRevisedBy,
  OtherAdaptationBy,
  CompiledBy,
  SelectedBy,
  NonTextMaterialSelectedBy,
  CuratedBy,
  OtherCompilationBy,
  Producer,
  Director,
  Conductor,
  Choreographer,
  OtherDirectionBy,
  Actor,
  Dancer,
  Narrator,
  Commentator,
  VocalSoloist,
  InstrumentalSoloist,
  ReadBy,
  PerformedByOrchestraBandEnsemble,
  Speaker,
  Presenter,
  PerformedBy,
  FilmedPhotographedBy,
  EditorFilmOrVideo,
  OtherRecordingBy,
  AssistedBy,
  HonoredDedicatedTo,
  EnactingJurisdiction,
  PeerReviewed,
  VariousRoles,
  Other
}
