// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const CountryBasedOnIso_3166_1 = {
  "AD": "Andorra",
  "AE": "UnitedArabEmirates",
  "AF": "Afghanistan",
  "AG": "AntiguaAndBarbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AN": "NetherlandsAntilles",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Argentina",
  "AS": "AmericanSamoa",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "LandIslands",
  "AZ": "Azerbaijan",
  "BA": "BosniaAndHerzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgium",
  "BF": "BurkinaFaso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "SaintBarthLemy",
  "BM": "Bermuda",
  "BN": "BruneiDarussalam",
  "BO": "BoliviaPlurinationalStateOf",
  "BQ": "BonaireSintEustatiusAndSaba",
  "BR": "Brazil",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "BouvetIsland",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "CA": "Canada",
  "CC": "CocosKeelingIslands",
  "CD": "CongoDemocraticRepublicOfThe",
  "CF": "CentralAfricanRepublic",
  "CG": "Congo",
  "CH": "Switzerland",
  "CI": "CoteDIvoire",
  "CK": "CookIslands",
  "CL": "Chile",
  "CM": "Cameroon",
  "CN": "China",
  "CO": "Colombia",
  "CR": "CostaRica",
  "CS": "SerbiaAndMontenegro",
  "CU": "Cuba",
  "CV": "CaboVerde",
  "CW": "CuraAo",
  "CX": "ChristmasIsland",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "DE": "Germany",
  "DJ": "Djibouti",
  "DK": "Denmark",
  "DM": "Dominica",
  "DO": "DominicanRepublic",
  "DZ": "Algeria",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egypt",
  "EH": "WesternSahara",
  "ER": "Eritrea",
  "ES": "Spain",
  "ET": "Ethiopia",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "FalklandIslandsMalvinas",
  "FM": "MicronesiaFederatedStatesOf",
  "FO": "FaroeIslands",
  "FR": "France",
  "GA": "Gabon",
  "GB": "UnitedKingdom",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "FrenchGuiana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Greenland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "EquatorialGuinea",
  "GR": "Greece",
  "GS": "SouthGeorgiaAndTheSouthSandwichIslands",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "GuineaBissau",
  "GY": "Guyana",
  "HK": "HongKong",
  "HM": "HeardIslandAndMcDonaldIslands",
  "HN": "Honduras",
  "HR": "Croatia",
  "HT": "Haiti",
  "HU": "Hungary",
  "ID": "Indonesia",
  "IE": "Ireland",
  "IL": "Israel",
  "IM": "IsleOfMan",
  "IN": "India",
  "IO": "BritishIndianOceanTerritory",
  "IQ": "Iraq",
  "IR": "IranIslamicRepublicOf",
  "IS": "Iceland",
  "IT": "Italy",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordan",
  "JP": "Japan",
  "KE": "Kenya",
  "KG": "Kyrgyzstan",
  "KH": "Cambodia",
  "KI": "Kiribati",
  "KM": "Comoros",
  "KN": "SaintKittsAndNevis",
  "KP": "KoreaDemocraticPeopleSRepublicOf",
  "KR": "KoreaRepublicOf",
  "KW": "Kuwait",
  "KY": "CaymanIslands",
  "KZ": "Kazakhstan",
  "LA": "LaoPeopleSDemocraticRepublic",
  "LB": "Lebanon",
  "LC": "SaintLucia",
  "LI": "Liechtenstein",
  "LK": "SriLanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "LY": "Libya",
  "MA": "Morocco",
  "MC": "Monaco",
  "MD": "MoldovaRepublicOf",
  "ME": "Montenegro",
  "MF": "SaintMartinFrenchPart",
  "MG": "Madagascar",
  "MH": "MarshallIslands",
  "MK": "NorthMacedonia",
  "ML": "Mali",
  "MM": "Myanmar",
  "MN": "Mongolia",
  "MO": "Macao",
  "MP": "NorthernMarianaIslands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaysia",
  "MZ": "Mozambique",
  "NA": "Namibia",
  "NC": "NewCaledonia",
  "NE": "Niger",
  "NF": "NorfolkIsland",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Netherlands",
  "NO": "Norway",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "NewZealand",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "FrenchPolynesia",
  "PG": "PapuaNewGuinea",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Poland",
  "PM": "SaintPierreAndMiquelon",
  "PN": "Pitcairn",
  "PR": "PuertoRico",
  "PS": "PalestineStateOf",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RE": "RUnion",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "RussianFederation",
  "RW": "Rwanda",
  "SA": "SaudiArabia",
  "SB": "SolomonIslands",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Sweden",
  "SG": "Singapore",
  "SH": "SaintHelenaAscensionAndTristanDaCunha",
  "SI": "Slovenia",
  "SJ": "SvalbardAndJanMayen",
  "SK": "Slovakia",
  "SL": "SierraLeone",
  "SM": "SanMarino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "SouthSudan",
  "ST": "SaoTomeAndPrincipe",
  "SV": "ElSalvador",
  "SX": "SintMaartenDutchPart",
  "SY": "SyrianArabRepublic",
  "SZ": "Eswatini",
  "TC": "TurksAndCaicosIslands",
  "TD": "Chad",
  "TF": "FrenchSouthernTerritories",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tajikistan",
  "TK": "Tokelau",
  "TL": "TimorLeste",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Turkey",
  "TT": "TrinidadAndTobago",
  "TV": "Tuvalu",
  "TW": "TaiwanProvinceOfChina",
  "TZ": "TanzaniaUnitedRepublicOf",
  "UA": "Ukraine",
  "UG": "Uganda",
  "UM": "UnitedStatesMinorOutlyingIslands",
  "US": "UnitedStates",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VA": "HolySeeVaticanCityState",
  "VC": "SaintVincentAndTheGrenadines",
  "VE": "VenezuelaBolivarianRepublicOf",
  "VG": "VirginIslandsBritish",
  "VI": "VirginIslandsUs",
  "VN": "VietNam",
  "VU": "Vanuatu",
  "WF": "WallisAndFutuna",
  "WS": "Samoa",
  "YE": "Yemen",
  "YT": "Mayotte",
  "YU": "Yugoslavia",
  "ZA": "SouthAfrica",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
};

export enum CountryBasedOnIso_3166_1Enum {
  Andorra = "Andorra",
  UnitedArabEmirates = "UnitedArabEmirates",
  Afghanistan = "Afghanistan",
  AntiguaAndBarbuda = "AntiguaAndBarbuda",
  Anguilla = "Anguilla",
  Albania = "Albania",
  Armenia = "Armenia",
  NetherlandsAntilles = "NetherlandsAntilles",
  Angola = "Angola",
  Antarctica = "Antarctica",
  Argentina = "Argentina",
  AmericanSamoa = "AmericanSamoa",
  Austria = "Austria",
  Australia = "Australia",
  Aruba = "Aruba",
  LandIslands = "LandIslands",
  Azerbaijan = "Azerbaijan",
  BosniaAndHerzegovina = "BosniaAndHerzegovina",
  Barbados = "Barbados",
  Bangladesh = "Bangladesh",
  Belgium = "Belgium",
  BurkinaFaso = "BurkinaFaso",
  Bulgaria = "Bulgaria",
  Bahrain = "Bahrain",
  Burundi = "Burundi",
  Benin = "Benin",
  SaintBarthLemy = "SaintBarthLemy",
  Bermuda = "Bermuda",
  BruneiDarussalam = "BruneiDarussalam",
  BoliviaPlurinationalStateOf = "BoliviaPlurinationalStateOf",
  BonaireSintEustatiusAndSaba = "BonaireSintEustatiusAndSaba",
  Brazil = "Brazil",
  Bahamas = "Bahamas",
  Bhutan = "Bhutan",
  BouvetIsland = "BouvetIsland",
  Botswana = "Botswana",
  Belarus = "Belarus",
  Belize = "Belize",
  Canada = "Canada",
  CocosKeelingIslands = "CocosKeelingIslands",
  CongoDemocraticRepublicOfThe = "CongoDemocraticRepublicOfThe",
  CentralAfricanRepublic = "CentralAfricanRepublic",
  Congo = "Congo",
  Switzerland = "Switzerland",
  CoteDIvoire = "CoteDIvoire",
  CookIslands = "CookIslands",
  Chile = "Chile",
  Cameroon = "Cameroon",
  China = "China",
  Colombia = "Colombia",
  CostaRica = "CostaRica",
  SerbiaAndMontenegro = "SerbiaAndMontenegro",
  Cuba = "Cuba",
  CaboVerde = "CaboVerde",
  CuraAo = "CuraAo",
  ChristmasIsland = "ChristmasIsland",
  Cyprus = "Cyprus",
  Czechia = "Czechia",
  Germany = "Germany",
  Djibouti = "Djibouti",
  Denmark = "Denmark",
  Dominica = "Dominica",
  DominicanRepublic = "DominicanRepublic",
  Algeria = "Algeria",
  Ecuador = "Ecuador",
  Estonia = "Estonia",
  Egypt = "Egypt",
  WesternSahara = "WesternSahara",
  Eritrea = "Eritrea",
  Spain = "Spain",
  Ethiopia = "Ethiopia",
  Finland = "Finland",
  Fiji = "Fiji",
  FalklandIslandsMalvinas = "FalklandIslandsMalvinas",
  MicronesiaFederatedStatesOf = "MicronesiaFederatedStatesOf",
  FaroeIslands = "FaroeIslands",
  France = "France",
  Gabon = "Gabon",
  UnitedKingdom = "UnitedKingdom",
  Grenada = "Grenada",
  Georgia = "Georgia",
  FrenchGuiana = "FrenchGuiana",
  Guernsey = "Guernsey",
  Ghana = "Ghana",
  Gibraltar = "Gibraltar",
  Greenland = "Greenland",
  Gambia = "Gambia",
  Guinea = "Guinea",
  Guadeloupe = "Guadeloupe",
  EquatorialGuinea = "EquatorialGuinea",
  Greece = "Greece",
  SouthGeorgiaAndTheSouthSandwichIslands = "SouthGeorgiaAndTheSouthSandwichIslands",
  Guatemala = "Guatemala",
  Guam = "Guam",
  GuineaBissau = "GuineaBissau",
  Guyana = "Guyana",
  HongKong = "HongKong",
  HeardIslandAndMcDonaldIslands = "HeardIslandAndMcDonaldIslands",
  Honduras = "Honduras",
  Croatia = "Croatia",
  Haiti = "Haiti",
  Hungary = "Hungary",
  Indonesia = "Indonesia",
  Ireland = "Ireland",
  Israel = "Israel",
  IsleOfMan = "IsleOfMan",
  India = "India",
  BritishIndianOceanTerritory = "BritishIndianOceanTerritory",
  Iraq = "Iraq",
  IranIslamicRepublicOf = "IranIslamicRepublicOf",
  Iceland = "Iceland",
  Italy = "Italy",
  Jersey = "Jersey",
  Jamaica = "Jamaica",
  Jordan = "Jordan",
  Japan = "Japan",
  Kenya = "Kenya",
  Kyrgyzstan = "Kyrgyzstan",
  Cambodia = "Cambodia",
  Kiribati = "Kiribati",
  Comoros = "Comoros",
  SaintKittsAndNevis = "SaintKittsAndNevis",
  KoreaDemocraticPeopleSRepublicOf = "KoreaDemocraticPeopleSRepublicOf",
  KoreaRepublicOf = "KoreaRepublicOf",
  Kuwait = "Kuwait",
  CaymanIslands = "CaymanIslands",
  Kazakhstan = "Kazakhstan",
  LaoPeopleSDemocraticRepublic = "LaoPeopleSDemocraticRepublic",
  Lebanon = "Lebanon",
  SaintLucia = "SaintLucia",
  Liechtenstein = "Liechtenstein",
  SriLanka = "SriLanka",
  Liberia = "Liberia",
  Lesotho = "Lesotho",
  Lithuania = "Lithuania",
  Luxembourg = "Luxembourg",
  Latvia = "Latvia",
  Libya = "Libya",
  Morocco = "Morocco",
  Monaco = "Monaco",
  MoldovaRepublicOf = "MoldovaRepublicOf",
  Montenegro = "Montenegro",
  SaintMartinFrenchPart = "SaintMartinFrenchPart",
  Madagascar = "Madagascar",
  MarshallIslands = "MarshallIslands",
  NorthMacedonia = "NorthMacedonia",
  Mali = "Mali",
  Myanmar = "Myanmar",
  Mongolia = "Mongolia",
  Macao = "Macao",
  NorthernMarianaIslands = "NorthernMarianaIslands",
  Martinique = "Martinique",
  Mauritania = "Mauritania",
  Montserrat = "Montserrat",
  Malta = "Malta",
  Mauritius = "Mauritius",
  Maldives = "Maldives",
  Malawi = "Malawi",
  Mexico = "Mexico",
  Malaysia = "Malaysia",
  Mozambique = "Mozambique",
  Namibia = "Namibia",
  NewCaledonia = "NewCaledonia",
  Niger = "Niger",
  NorfolkIsland = "NorfolkIsland",
  Nigeria = "Nigeria",
  Nicaragua = "Nicaragua",
  Netherlands = "Netherlands",
  Norway = "Norway",
  Nepal = "Nepal",
  Nauru = "Nauru",
  Niue = "Niue",
  NewZealand = "NewZealand",
  Oman = "Oman",
  Panama = "Panama",
  Peru = "Peru",
  FrenchPolynesia = "FrenchPolynesia",
  PapuaNewGuinea = "PapuaNewGuinea",
  Philippines = "Philippines",
  Pakistan = "Pakistan",
  Poland = "Poland",
  SaintPierreAndMiquelon = "SaintPierreAndMiquelon",
  Pitcairn = "Pitcairn",
  PuertoRico = "PuertoRico",
  PalestineStateOf = "PalestineStateOf",
  Portugal = "Portugal",
  Palau = "Palau",
  Paraguay = "Paraguay",
  Qatar = "Qatar",
  RUnion = "RUnion",
  Romania = "Romania",
  Serbia = "Serbia",
  RussianFederation = "RussianFederation",
  Rwanda = "Rwanda",
  SaudiArabia = "SaudiArabia",
  SolomonIslands = "SolomonIslands",
  Seychelles = "Seychelles",
  Sudan = "Sudan",
  Sweden = "Sweden",
  Singapore = "Singapore",
  SaintHelenaAscensionAndTristanDaCunha = "SaintHelenaAscensionAndTristanDaCunha",
  Slovenia = "Slovenia",
  SvalbardAndJanMayen = "SvalbardAndJanMayen",
  Slovakia = "Slovakia",
  SierraLeone = "SierraLeone",
  SanMarino = "SanMarino",
  Senegal = "Senegal",
  Somalia = "Somalia",
  Suriname = "Suriname",
  SouthSudan = "SouthSudan",
  SaoTomeAndPrincipe = "SaoTomeAndPrincipe",
  ElSalvador = "ElSalvador",
  SintMaartenDutchPart = "SintMaartenDutchPart",
  SyrianArabRepublic = "SyrianArabRepublic",
  Eswatini = "Eswatini",
  TurksAndCaicosIslands = "TurksAndCaicosIslands",
  Chad = "Chad",
  FrenchSouthernTerritories = "FrenchSouthernTerritories",
  Togo = "Togo",
  Thailand = "Thailand",
  Tajikistan = "Tajikistan",
  Tokelau = "Tokelau",
  TimorLeste = "TimorLeste",
  Turkmenistan = "Turkmenistan",
  Tunisia = "Tunisia",
  Tonga = "Tonga",
  Turkey = "Turkey",
  TrinidadAndTobago = "TrinidadAndTobago",
  Tuvalu = "Tuvalu",
  TaiwanProvinceOfChina = "TaiwanProvinceOfChina",
  TanzaniaUnitedRepublicOf = "TanzaniaUnitedRepublicOf",
  Ukraine = "Ukraine",
  Uganda = "Uganda",
  UnitedStatesMinorOutlyingIslands = "UnitedStatesMinorOutlyingIslands",
  UnitedStates = "UnitedStates",
  Uruguay = "Uruguay",
  Uzbekistan = "Uzbekistan",
  HolySeeVaticanCityState = "HolySeeVaticanCityState",
  SaintVincentAndTheGrenadines = "SaintVincentAndTheGrenadines",
  VenezuelaBolivarianRepublicOf = "VenezuelaBolivarianRepublicOf",
  VirginIslandsBritish = "VirginIslandsBritish",
  VirginIslandsUs = "VirginIslandsUs",
  VietNam = "VietNam",
  Vanuatu = "Vanuatu",
  WallisAndFutuna = "WallisAndFutuna",
  Samoa = "Samoa",
  Yemen = "Yemen",
  Mayotte = "Mayotte",
  Yugoslavia = "Yugoslavia",
  SouthAfrica = "SouthAfrica",
  Zambia = "Zambia",
  Zimbabwe = "Zimbabwe"
}
  