export const CountryBasedOnIso_3166_1 = {
  "AD": "Andorra",
  "AE": "UnitedArabEmirates",
  "AF": "Afghanistan",
  "AG": "AntiguaAndBarbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AN": "NetherlandsAntilles",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Argentina",
  "AS": "AmericanSamoa",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "LandIslands",
  "AZ": "Azerbaijan",
  "BA": "BosniaAndHerzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgium",
  "BF": "BurkinaFaso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "SaintBarthLemy",
  "BM": "Bermuda",
  "BN": "BruneiDarussalam",
  "BO": "BoliviaPlurinationalStateOf",
  "BQ": "BonaireSintEustatiusAndSaba",
  "BR": "Brazil",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "BouvetIsland",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "CA": "Canada",
  "CC": "CocosKeelingIslands",
  "CD": "CongoDemocraticRepublicOfThe",
  "CF": "CentralAfricanRepublic",
  "CG": "Congo",
  "CH": "Switzerland",
  "CI": "CoteDIvoire",
  "CK": "CookIslands",
  "CL": "Chile",
  "CM": "Cameroon",
  "CN": "China",
  "CO": "Colombia",
  "CR": "CostaRica",
  "CS": "SerbiaAndMontenegro",
  "CU": "Cuba",
  "CV": "CaboVerde",
  "CW": "CuraAo",
  "CX": "ChristmasIsland",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "DE": "Germany",
  "DJ": "Djibouti",
  "DK": "Denmark",
  "DM": "Dominica",
  "DO": "DominicanRepublic",
  "DZ": "Algeria",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egypt",
  "EH": "WesternSahara",
  "ER": "Eritrea",
  "ES": "Spain",
  "ET": "Ethiopia",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "FalklandIslandsMalvinas",
  "FM": "MicronesiaFederatedStatesOf",
  "FO": "FaroeIslands",
  "FR": "France",
  "GA": "Gabon",
  "GB": "UnitedKingdom",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "FrenchGuiana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Greenland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "EquatorialGuinea",
  "GR": "Greece",
  "GS": "SouthGeorgiaAndTheSouthSandwichIslands",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "GuineaBissau",
  "GY": "Guyana",
  "HK": "HongKong",
  "HM": "HeardIslandAndMcDonaldIslands",
  "HN": "Honduras",
  "HR": "Croatia",
  "HT": "Haiti",
  "HU": "Hungary",
  "ID": "Indonesia",
  "IE": "Ireland",
  "IL": "Israel",
  "IM": "IsleOfMan",
  "IN": "India",
  "IO": "BritishIndianOceanTerritory",
  "IQ": "Iraq",
  "IR": "IranIslamicRepublicOf",
  "IS": "Iceland",
  "IT": "Italy",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordan",
  "JP": "Japan",
  "KE": "Kenya",
  "KG": "Kyrgyzstan",
  "KH": "Cambodia",
  "KI": "Kiribati",
  "KM": "Comoros",
  "KN": "SaintKittsAndNevis",
  "KP": "KoreaDemocraticPeopleSRepublicOf",
  "KR": "KoreaRepublicOf",
  "KW": "Kuwait",
  "KY": "CaymanIslands",
  "KZ": "Kazakhstan",
  "LA": "LaoPeopleSDemocraticRepublic",
  "LB": "Lebanon",
  "LC": "SaintLucia",
  "LI": "Liechtenstein",
  "LK": "SriLanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "LY": "Libya",
  "MA": "Morocco",
  "MC": "Monaco",
  "MD": "MoldovaRepublicOf",
  "ME": "Montenegro",
  "MF": "SaintMartinFrenchPart",
  "MG": "Madagascar",
  "MH": "MarshallIslands",
  "MK": "NorthMacedonia",
  "ML": "Mali",
  "MM": "Myanmar",
  "MN": "Mongolia",
  "MO": "Macao",
  "MP": "NorthernMarianaIslands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaysia",
  "MZ": "Mozambique",
  "NA": "Namibia",
  "NC": "NewCaledonia",
  "NE": "Niger",
  "NF": "NorfolkIsland",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Netherlands",
  "NO": "Norway",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "NewZealand",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "FrenchPolynesia",
  "PG": "PapuaNewGuinea",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Poland",
  "PM": "SaintPierreAndMiquelon",
  "PN": "Pitcairn",
  "PR": "PuertoRico",
  "PS": "PalestineStateOf",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RE": "RUnion",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "RussianFederation",
  "RW": "Rwanda",
  "SA": "SaudiArabia",
  "SB": "SolomonIslands",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Sweden",
  "SG": "Singapore",
  "SH": "SaintHelenaAscensionAndTristanDaCunha",
  "SI": "Slovenia",
  "SJ": "SvalbardAndJanMayen",
  "SK": "Slovakia",
  "SL": "SierraLeone",
  "SM": "SanMarino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "SouthSudan",
  "ST": "SaoTomeAndPrincipe",
  "SV": "ElSalvador",
  "SX": "SintMaartenDutchPart",
  "SY": "SyrianArabRepublic",
  "SZ": "Eswatini",
  "TC": "TurksAndCaicosIslands",
  "TD": "Chad",
  "TF": "FrenchSouthernTerritories",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tajikistan",
  "TK": "Tokelau",
  "TL": "TimorLeste",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Turkey",
  "TT": "TrinidadAndTobago",
  "TV": "Tuvalu",
  "TW": "TaiwanProvinceOfChina",
  "TZ": "TanzaniaUnitedRepublicOf",
  "UA": "Ukraine",
  "UG": "Uganda",
  "UM": "UnitedStatesMinorOutlyingIslands",
  "US": "UnitedStates",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VA": "HolySeeVaticanCityState",
  "VC": "SaintVincentAndTheGrenadines",
  "VE": "VenezuelaBolivarianRepublicOf",
  "VG": "VirginIslandsBritish",
  "VI": "VirginIslandsUs",
  "VN": "VietNam",
  "VU": "Vanuatu",
  "WF": "WallisAndFutuna",
  "WS": "Samoa",
  "YE": "Yemen",
  "YT": "Mayotte",
  "YU": "Yugoslavia",
  "ZA": "SouthAfrica",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
};

export enum CountryBasedOnIso_3166_1Enum {
  Andorra,
  UnitedArabEmirates,
  Afghanistan,
  AntiguaAndBarbuda,
  Anguilla,
  Albania,
  Armenia,
  NetherlandsAntilles,
  Angola,
  Antarctica,
  Argentina,
  AmericanSamoa,
  Austria,
  Australia,
  Aruba,
  LandIslands,
  Azerbaijan,
  BosniaAndHerzegovina,
  Barbados,
  Bangladesh,
  Belgium,
  BurkinaFaso,
  Bulgaria,
  Bahrain,
  Burundi,
  Benin,
  SaintBarthLemy,
  Bermuda,
  BruneiDarussalam,
  BoliviaPlurinationalStateOf,
  BonaireSintEustatiusAndSaba,
  Brazil,
  Bahamas,
  Bhutan,
  BouvetIsland,
  Botswana,
  Belarus,
  Belize,
  Canada,
  CocosKeelingIslands,
  CongoDemocraticRepublicOfThe,
  CentralAfricanRepublic,
  Congo,
  Switzerland,
  CoteDIvoire,
  CookIslands,
  Chile,
  Cameroon,
  China,
  Colombia,
  CostaRica,
  SerbiaAndMontenegro,
  Cuba,
  CaboVerde,
  CuraAo,
  ChristmasIsland,
  Cyprus,
  Czechia,
  Germany,
  Djibouti,
  Denmark,
  Dominica,
  DominicanRepublic,
  Algeria,
  Ecuador,
  Estonia,
  Egypt,
  WesternSahara,
  Eritrea,
  Spain,
  Ethiopia,
  Finland,
  Fiji,
  FalklandIslandsMalvinas,
  MicronesiaFederatedStatesOf,
  FaroeIslands,
  France,
  Gabon,
  UnitedKingdom,
  Grenada,
  Georgia,
  FrenchGuiana,
  Guernsey,
  Ghana,
  Gibraltar,
  Greenland,
  Gambia,
  Guinea,
  Guadeloupe,
  EquatorialGuinea,
  Greece,
  SouthGeorgiaAndTheSouthSandwichIslands,
  Guatemala,
  Guam,
  GuineaBissau,
  Guyana,
  HongKong,
  HeardIslandAndMcDonaldIslands,
  Honduras,
  Croatia,
  Haiti,
  Hungary,
  Indonesia,
  Ireland,
  Israel,
  IsleOfMan,
  India,
  BritishIndianOceanTerritory,
  Iraq,
  IranIslamicRepublicOf,
  Iceland,
  Italy,
  Jersey,
  Jamaica,
  Jordan,
  Japan,
  Kenya,
  Kyrgyzstan,
  Cambodia,
  Kiribati,
  Comoros,
  SaintKittsAndNevis,
  KoreaDemocraticPeopleSRepublicOf,
  KoreaRepublicOf,
  Kuwait,
  CaymanIslands,
  Kazakhstan,
  LaoPeopleSDemocraticRepublic,
  Lebanon,
  SaintLucia,
  Liechtenstein,
  SriLanka,
  Liberia,
  Lesotho,
  Lithuania,
  Luxembourg,
  Latvia,
  Libya,
  Morocco,
  Monaco,
  MoldovaRepublicOf,
  Montenegro,
  SaintMartinFrenchPart,
  Madagascar,
  MarshallIslands,
  NorthMacedonia,
  Mali,
  Myanmar,
  Mongolia,
  Macao,
  NorthernMarianaIslands,
  Martinique,
  Mauritania,
  Montserrat,
  Malta,
  Mauritius,
  Maldives,
  Malawi,
  Mexico,
  Malaysia,
  Mozambique,
  Namibia,
  NewCaledonia,
  Niger,
  NorfolkIsland,
  Nigeria,
  Nicaragua,
  Netherlands,
  Norway,
  Nepal,
  Nauru,
  Niue,
  NewZealand,
  Oman,
  Panama,
  Peru,
  FrenchPolynesia,
  PapuaNewGuinea,
  Philippines,
  Pakistan,
  Poland,
  SaintPierreAndMiquelon,
  Pitcairn,
  PuertoRico,
  PalestineStateOf,
  Portugal,
  Palau,
  Paraguay,
  Qatar,
  RUnion,
  Romania,
  Serbia,
  RussianFederation,
  Rwanda,
  SaudiArabia,
  SolomonIslands,
  Seychelles,
  Sudan,
  Sweden,
  Singapore,
  SaintHelenaAscensionAndTristanDaCunha,
  Slovenia,
  SvalbardAndJanMayen,
  Slovakia,
  SierraLeone,
  SanMarino,
  Senegal,
  Somalia,
  Suriname,
  SouthSudan,
  SaoTomeAndPrincipe,
  ElSalvador,
  SintMaartenDutchPart,
  SyrianArabRepublic,
  Eswatini,
  TurksAndCaicosIslands,
  Chad,
  FrenchSouthernTerritories,
  Togo,
  Thailand,
  Tajikistan,
  Tokelau,
  TimorLeste,
  Turkmenistan,
  Tunisia,
  Tonga,
  Turkey,
  TrinidadAndTobago,
  Tuvalu,
  TaiwanProvinceOfChina,
  TanzaniaUnitedRepublicOf,
  Ukraine,
  Uganda,
  UnitedStatesMinorOutlyingIslands,
  UnitedStates,
  Uruguay,
  Uzbekistan,
  HolySeeVaticanCityState,
  SaintVincentAndTheGrenadines,
  VenezuelaBolivarianRepublicOf,
  VirginIslandsBritish,
  VirginIslandsUs,
  VietNam,
  Vanuatu,
  WallisAndFutuna,
  Samoa,
  Yemen,
  Mayotte,
  Yugoslavia,
  SouthAfrica,
  Zambia,
  Zimbabwe
}
