export const CurrencyCodeBasedOnIso_4217 = {
  "AED": "UaeDirham",
  "AFA": "Afghani",
  "AFN": "Afghani",
  "ALL": "Lek",
  "AMD": "ArmenianDram",
  "ANG": "NetherlandsAntillianGuilder",
  "AOA": "Kwanza",
  "ARS": "ArgentinePeso",
  "ATS": "Schilling",
  "AUD": "AustralianDollar",
  "AWG": "ArubanFlorin",
  "AZN": "AzerbaijanManat",
  "BAM": "ConvertibleMarks",
  "BBD": "BarbadosDollar",
  "BDT": "Taka",
  "BEF": "BelgianFranc",
  "BGL": "BulgarianLev",
  "BGN": "BulgarianLev",
  "BHD": "BahrainiDinar",
  "BIF": "BurundiFranc",
  "BMD": "BermudianDollar",
  "BND": "BruneiDollar",
  "BOB": "Boliviano",
  "BRL": "BrazilianReal",
  "BSD": "BahamianDollar",
  "BTN": "Ngultrun",
  "BWP": "Pula",
  "BYR": "OldBelarussianRuble",
  "BYN": "BelarussianRuble",
  "BZD": "BelizeDollar",
  "CAD": "CanadianDollar",
  "CDF": "FrancCongolais",
  "CHF": "SwissFranc",
  "CLP": "ChileanPeso",
  "CNY": "YuanRenminbi",
  "COP": "ColombianPeso",
  "CRC": "CostaRicanColon",
  "CSD": "SerbianDinar",
  "CUC": "CubanConvertiblePeso",
  "CUP": "CubanPeso",
  "CVE": "CaboVerdeEscudo",
  "CYP": "CyprusPound",
  "CZK": "CzechKoruna",
  "DEM": "Mark",
  "DJF": "DjiboutiFranc",
  "DKK": "DanishKrone",
  "DOP": "DominicanPeso",
  "DZD": "AlgerianDinar",
  "EEK": "Kroon",
  "EGP": "EgyptianPound",
  "ERN": "Nakfa",
  "ESP": "Peseta",
  "ETB": "EthiopianBirr",
  "EUR": "Euro",
  "FIM": "Markka",
  "FJD": "FijiDollar",
  "FKP": "FalklandIslandsPound",
  "FRF": "Franc",
  "GBP": "PoundSterling",
  "GEL": "Lari",
  "GHC": "GhanaCedi",
  "GHS": "GhanaCedi",
  "GIP": "GibraltarPound",
  "GMD": "Dalasi",
  "GNF": "GuineanFranc",
  "GRD": "Drachma",
  "GTQ": "Quetzal",
  "GWP": "GuineaBissauPeso",
  "GYD": "GuyanaDollar",
  "HKD": "HongKongDollar",
  "HNL": "Lempira",
  "HRK": "Kuna",
  "HTG": "Gourde",
  "HUF": "Forint",
  "IDR": "Rupiah",
  "IEP": "Punt",
  "ILS": "NewIsraeliSheqel",
  "INR": "IndianRupee",
  "IQD": "IraqiDinar",
  "IRR": "IranianRial",
  "ISK": "IcelandKrona",
  "ITL": "Lira",
  "JMD": "JamaicanDollar",
  "JOD": "JordanianDinar",
  "JPY": "Yen",
  "KES": "KenyanShilling",
  "KGS": "Som",
  "KHR": "Riel",
  "KMF": "ComorianFranc",
  "KPW": "NorthKoreanWon",
  "KRW": "Won",
  "KWD": "KuwaitiDinar",
  "KYD": "CaymanIslandsDollar",
  "KZT": "Tenge",
  "LAK": "LaoKip",
  "LBP": "LebanesePound",
  "LKR": "SriLankaRupee",
  "LRD": "LiberianDollar",
  "LSL": "Loti",
  "LTL": "Litus",
  "LUF": "LuxembourgFranc",
  "LVL": "LatvianLats",
  "LYD": "LibyanDinar",
  "MAD": "MoroccanDirham",
  "MDL": "MoldovanLeu",
  "MGA": "MalagasyAriary",
  "MGF": "MalagasyFranc",
  "MKD": "Denar",
  "MMK": "Kyat",
  "MNT": "Tugrik",
  "MOP": "Pataca",
  "MRO": "OldOuguiya",
  "MRU": "Ouguiya",
  "MTL": "MalteseLira",
  "MUR": "MauritiusRupee",
  "MVR": "Rufiyaa",
  "MWK": "MalawiKwacha",
  "MXN": "MexicanPeso",
  "MYR": "MalaysianRinggit",
  "MZN": "MozambiqueMetical",
  "NAD": "NamibiaDollar",
  "NGN": "Naira",
  "NIO": "CordobaOro",
  "NLG": "Guilder",
  "NOK": "NorwegianKrone",
  "NPR": "NepaleseRupee",
  "NZD": "NewZealandDollar",
  "OMR": "RialOmani",
  "PAB": "Balboa",
  "PEN": "Sol",
  "PGK": "Kina",
  "PHP": "PhilippinePeso",
  "PKR": "PakistanRupee",
  "PLN": "ZOty",
  "PTE": "Escudo",
  "PYG": "Guarani",
  "QAR": "QatariRial",
  "ROL": "RomanianOldLeu",
  "RON": "RomanianLeu",
  "RSD": "SerbianDinar",
  "RUB": "RussianRuble",
  "RUR": "RussianRuble",
  "RWF": "RwandaFranc",
  "SAR": "SaudiRiyal",
  "SBD": "SolomonIslandsDollar",
  "SCR": "SeychellesRupee",
  "SDD": "SudaneseDinar",
  "SDG": "SudanesePound",
  "SEK": "SwedishKrona",
  "SGD": "SingaporeDollar",
  "SHP": "SaintHelenaPound",
  "SIT": "Tolar",
  "SKK": "SlovakKoruna",
  "SLL": "Leone",
  "SOS": "SomaliShilling",
  "SRD": "SurinamDollar",
  "SRG": "SurinameGuilder",
  "STD": "OldDobra",
  "STN": "Dobra",
  "SVC": "ElSalvadorColon",
  "SYP": "SyrianPound",
  "SZL": "Lilangeni",
  "THB": "Baht",
  "TJS": "Somoni",
  "TMM": "TurkmenistanManat",
  "TMT": "TurkmenistanNewManat",
  "TND": "TunisianDinar",
  "TOP": "PaAnga",
  "TPE": "TimorEscudo",
  "TRL": "TurkishLiraOld",
  "TRY": "TurkishLira",
  "TTD": "TrinidadAndTobagoDollar",
  "TWD": "NewTaiwanDollar",
  "TZS": "TanzanianShilling",
  "UAH": "Hryvnia",
  "UGX": "UgandaShilling",
  "USD": "UsDollar",
  "UYU": "PesoUruguayo",
  "UZS": "UzbekistanSum",
  "VEB": "BolVar",
  "VEF": "BolVar",
  "VES": "BolVarSoberano",
  "VND": "Dong",
  "VUV": "Vatu",
  "WST": "Tala",
  "XAF": "CfaFrancBeac",
  "XCD": "EastCaribbeanDollar",
  "XOF": "CfaFrancBceao",
  "XPF": "CfpFranc",
  "YER": "YemeniRial",
  "YUM": "YugoslavianDinar",
  "ZAR": "Rand",
  "ZMK": "Kwacha",
  "ZMW": "ZambianKwacha",
  "ZWD": "ZimbabweDollar",
  "ZWL": "ZimbabweDollar",
};

export enum CurrencyCodeBasedOnIso_4217Enum {
  UaeDirham,
  Afghani,
  Lek,
  ArmenianDram,
  NetherlandsAntillianGuilder,
  Kwanza,
  ArgentinePeso,
  Schilling,
  AustralianDollar,
  ArubanFlorin,
  AzerbaijanManat,
  ConvertibleMarks,
  BarbadosDollar,
  Taka,
  BelgianFranc,
  BulgarianLev,
  BahrainiDinar,
  BurundiFranc,
  BermudianDollar,
  BruneiDollar,
  Boliviano,
  BrazilianReal,
  BahamianDollar,
  Ngultrun,
  Pula,
  OldBelarussianRuble,
  BelarussianRuble,
  BelizeDollar,
  CanadianDollar,
  FrancCongolais,
  SwissFranc,
  ChileanPeso,
  YuanRenminbi,
  ColombianPeso,
  CostaRicanColon,
  SerbianDinar,
  CubanConvertiblePeso,
  CubanPeso,
  CaboVerdeEscudo,
  CyprusPound,
  CzechKoruna,
  Mark,
  DjiboutiFranc,
  DanishKrone,
  DominicanPeso,
  AlgerianDinar,
  Kroon,
  EgyptianPound,
  Nakfa,
  Peseta,
  EthiopianBirr,
  Euro,
  Markka,
  FijiDollar,
  FalklandIslandsPound,
  Franc,
  PoundSterling,
  Lari,
  GhanaCedi,
  GibraltarPound,
  Dalasi,
  GuineanFranc,
  Drachma,
  Quetzal,
  GuineaBissauPeso,
  GuyanaDollar,
  HongKongDollar,
  Lempira,
  Kuna,
  Gourde,
  Forint,
  Rupiah,
  Punt,
  NewIsraeliSheqel,
  IndianRupee,
  IraqiDinar,
  IranianRial,
  IcelandKrona,
  Lira,
  JamaicanDollar,
  JordanianDinar,
  Yen,
  KenyanShilling,
  Som,
  Riel,
  ComorianFranc,
  NorthKoreanWon,
  Won,
  KuwaitiDinar,
  CaymanIslandsDollar,
  Tenge,
  LaoKip,
  LebanesePound,
  SriLankaRupee,
  LiberianDollar,
  Loti,
  Litus,
  LuxembourgFranc,
  LatvianLats,
  LibyanDinar,
  MoroccanDirham,
  MoldovanLeu,
  MalagasyAriary,
  MalagasyFranc,
  Denar,
  Kyat,
  Tugrik,
  Pataca,
  OldOuguiya,
  Ouguiya,
  MalteseLira,
  MauritiusRupee,
  Rufiyaa,
  MalawiKwacha,
  MexicanPeso,
  MalaysianRinggit,
  MozambiqueMetical,
  NamibiaDollar,
  Naira,
  CordobaOro,
  Guilder,
  NorwegianKrone,
  NepaleseRupee,
  NewZealandDollar,
  RialOmani,
  Balboa,
  Sol,
  Kina,
  PhilippinePeso,
  PakistanRupee,
  ZOty,
  Escudo,
  Guarani,
  QatariRial,
  RomanianOldLeu,
  RomanianLeu,
  RussianRuble,
  RwandaFranc,
  SaudiRiyal,
  SolomonIslandsDollar,
  SeychellesRupee,
  SudaneseDinar,
  SudanesePound,
  SwedishKrona,
  SingaporeDollar,
  SaintHelenaPound,
  Tolar,
  SlovakKoruna,
  Leone,
  SomaliShilling,
  SurinamDollar,
  SurinameGuilder,
  OldDobra,
  Dobra,
  ElSalvadorColon,
  SyrianPound,
  Lilangeni,
  Baht,
  Somoni,
  TurkmenistanManat,
  TurkmenistanNewManat,
  TunisianDinar,
  PaAnga,
  TimorEscudo,
  TurkishLiraOld,
  TurkishLira,
  TrinidadAndTobagoDollar,
  NewTaiwanDollar,
  TanzanianShilling,
  Hryvnia,
  UgandaShilling,
  UsDollar,
  PesoUruguayo,
  UzbekistanSum,
  BolVar,
  BolVarSoberano,
  Dong,
  Vatu,
  Tala,
  CfaFrancBeac,
  EastCaribbeanDollar,
  CfaFrancBceao,
  CfpFranc,
  YemeniRial,
  YugoslavianDinar,
  Rand,
  Kwacha,
  ZambianKwacha,
  ZimbabweDollar
}
