// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const CurrencyCodeBasedOnIso_4217 = {
  "AED": "UaeDirham",
  "AFA": "Afghani",
  "AFN": "Afghani",
  "ALL": "Lek",
  "AMD": "ArmenianDram",
  "ANG": "NetherlandsAntillianGuilder",
  "AOA": "Kwanza",
  "ARS": "ArgentinePeso",
  "ATS": "Schilling",
  "AUD": "AustralianDollar",
  "AWG": "ArubanFlorin",
  "AZN": "AzerbaijanManat",
  "BAM": "ConvertibleMarks",
  "BBD": "BarbadosDollar",
  "BDT": "Taka",
  "BEF": "BelgianFranc",
  "BGL": "BulgarianLev",
  "BGN": "BulgarianLev",
  "BHD": "BahrainiDinar",
  "BIF": "BurundiFranc",
  "BMD": "BermudianDollar",
  "BND": "BruneiDollar",
  "BOB": "Boliviano",
  "BRL": "BrazilianReal",
  "BSD": "BahamianDollar",
  "BTN": "Ngultrun",
  "BWP": "Pula",
  "BYR": "OldBelarussianRuble",
  "BYN": "BelarussianRuble",
  "BZD": "BelizeDollar",
  "CAD": "CanadianDollar",
  "CDF": "FrancCongolais",
  "CHF": "SwissFranc",
  "CLP": "ChileanPeso",
  "CNY": "YuanRenminbi",
  "COP": "ColombianPeso",
  "CRC": "CostaRicanColon",
  "CSD": "SerbianDinar",
  "CUC": "CubanConvertiblePeso",
  "CUP": "CubanPeso",
  "CVE": "CaboVerdeEscudo",
  "CYP": "CyprusPound",
  "CZK": "CzechKoruna",
  "DEM": "Mark",
  "DJF": "DjiboutiFranc",
  "DKK": "DanishKrone",
  "DOP": "DominicanPeso",
  "DZD": "AlgerianDinar",
  "EEK": "Kroon",
  "EGP": "EgyptianPound",
  "ERN": "Nakfa",
  "ESP": "Peseta",
  "ETB": "EthiopianBirr",
  "EUR": "Euro",
  "FIM": "Markka",
  "FJD": "FijiDollar",
  "FKP": "FalklandIslandsPound",
  "FRF": "Franc",
  "GBP": "PoundSterling",
  "GEL": "Lari",
  "GHC": "GhanaCedi",
  "GHS": "GhanaCedi",
  "GIP": "GibraltarPound",
  "GMD": "Dalasi",
  "GNF": "GuineanFranc",
  "GRD": "Drachma",
  "GTQ": "Quetzal",
  "GWP": "GuineaBissauPeso",
  "GYD": "GuyanaDollar",
  "HKD": "HongKongDollar",
  "HNL": "Lempira",
  "HRK": "Kuna",
  "HTG": "Gourde",
  "HUF": "Forint",
  "IDR": "Rupiah",
  "IEP": "Punt",
  "ILS": "NewIsraeliSheqel",
  "INR": "IndianRupee",
  "IQD": "IraqiDinar",
  "IRR": "IranianRial",
  "ISK": "IcelandKrona",
  "ITL": "Lira",
  "JMD": "JamaicanDollar",
  "JOD": "JordanianDinar",
  "JPY": "Yen",
  "KES": "KenyanShilling",
  "KGS": "Som",
  "KHR": "Riel",
  "KMF": "ComorianFranc",
  "KPW": "NorthKoreanWon",
  "KRW": "Won",
  "KWD": "KuwaitiDinar",
  "KYD": "CaymanIslandsDollar",
  "KZT": "Tenge",
  "LAK": "LaoKip",
  "LBP": "LebanesePound",
  "LKR": "SriLankaRupee",
  "LRD": "LiberianDollar",
  "LSL": "Loti",
  "LTL": "Litus",
  "LUF": "LuxembourgFranc",
  "LVL": "LatvianLats",
  "LYD": "LibyanDinar",
  "MAD": "MoroccanDirham",
  "MDL": "MoldovanLeu",
  "MGA": "MalagasyAriary",
  "MGF": "MalagasyFranc",
  "MKD": "Denar",
  "MMK": "Kyat",
  "MNT": "Tugrik",
  "MOP": "Pataca",
  "MRO": "OldOuguiya",
  "MRU": "Ouguiya",
  "MTL": "MalteseLira",
  "MUR": "MauritiusRupee",
  "MVR": "Rufiyaa",
  "MWK": "MalawiKwacha",
  "MXN": "MexicanPeso",
  "MYR": "MalaysianRinggit",
  "MZN": "MozambiqueMetical",
  "NAD": "NamibiaDollar",
  "NGN": "Naira",
  "NIO": "CordobaOro",
  "NLG": "Guilder",
  "NOK": "NorwegianKrone",
  "NPR": "NepaleseRupee",
  "NZD": "NewZealandDollar",
  "OMR": "RialOmani",
  "PAB": "Balboa",
  "PEN": "Sol",
  "PGK": "Kina",
  "PHP": "PhilippinePeso",
  "PKR": "PakistanRupee",
  "PLN": "ZOty",
  "PTE": "Escudo",
  "PYG": "Guarani",
  "QAR": "QatariRial",
  "ROL": "RomanianOldLeu",
  "RON": "RomanianLeu",
  "RSD": "SerbianDinar",
  "RUB": "RussianRuble",
  "RUR": "RussianRuble",
  "RWF": "RwandaFranc",
  "SAR": "SaudiRiyal",
  "SBD": "SolomonIslandsDollar",
  "SCR": "SeychellesRupee",
  "SDD": "SudaneseDinar",
  "SDG": "SudanesePound",
  "SEK": "SwedishKrona",
  "SGD": "SingaporeDollar",
  "SHP": "SaintHelenaPound",
  "SIT": "Tolar",
  "SKK": "SlovakKoruna",
  "SLL": "Leone",
  "SOS": "SomaliShilling",
  "SRD": "SurinamDollar",
  "SRG": "SurinameGuilder",
  "STD": "OldDobra",
  "STN": "Dobra",
  "SVC": "ElSalvadorColon",
  "SYP": "SyrianPound",
  "SZL": "Lilangeni",
  "THB": "Baht",
  "TJS": "Somoni",
  "TMM": "TurkmenistanManat",
  "TMT": "TurkmenistanNewManat",
  "TND": "TunisianDinar",
  "TOP": "PaAnga",
  "TPE": "TimorEscudo",
  "TRL": "TurkishLiraOld",
  "TRY": "TurkishLira",
  "TTD": "TrinidadAndTobagoDollar",
  "TWD": "NewTaiwanDollar",
  "TZS": "TanzanianShilling",
  "UAH": "Hryvnia",
  "UGX": "UgandaShilling",
  "USD": "UsDollar",
  "UYU": "PesoUruguayo",
  "UZS": "UzbekistanSum",
  "VEB": "BolVar",
  "VEF": "BolVar",
  "VES": "BolVarSoberano",
  "VND": "Dong",
  "VUV": "Vatu",
  "WST": "Tala",
  "XAF": "CfaFrancBeac",
  "XCD": "EastCaribbeanDollar",
  "XOF": "CfaFrancBceao",
  "XPF": "CfpFranc",
  "YER": "YemeniRial",
  "YUM": "YugoslavianDinar",
  "ZAR": "Rand",
  "ZMK": "Kwacha",
  "ZMW": "ZambianKwacha",
  "ZWD": "ZimbabweDollar",
  "ZWL": "ZimbabweDollar",
};

export enum CurrencyCodeBasedOnIso_4217Enum {
  UaeDirham = "UaeDirham",
  Afghani = "Afghani",
  Lek = "Lek",
  ArmenianDram = "ArmenianDram",
  NetherlandsAntillianGuilder = "NetherlandsAntillianGuilder",
  Kwanza = "Kwanza",
  ArgentinePeso = "ArgentinePeso",
  Schilling = "Schilling",
  AustralianDollar = "AustralianDollar",
  ArubanFlorin = "ArubanFlorin",
  AzerbaijanManat = "AzerbaijanManat",
  ConvertibleMarks = "ConvertibleMarks",
  BarbadosDollar = "BarbadosDollar",
  Taka = "Taka",
  BelgianFranc = "BelgianFranc",
  BulgarianLev = "BulgarianLev",
  BahrainiDinar = "BahrainiDinar",
  BurundiFranc = "BurundiFranc",
  BermudianDollar = "BermudianDollar",
  BruneiDollar = "BruneiDollar",
  Boliviano = "Boliviano",
  BrazilianReal = "BrazilianReal",
  BahamianDollar = "BahamianDollar",
  Ngultrun = "Ngultrun",
  Pula = "Pula",
  OldBelarussianRuble = "OldBelarussianRuble",
  BelarussianRuble = "BelarussianRuble",
  BelizeDollar = "BelizeDollar",
  CanadianDollar = "CanadianDollar",
  FrancCongolais = "FrancCongolais",
  SwissFranc = "SwissFranc",
  ChileanPeso = "ChileanPeso",
  YuanRenminbi = "YuanRenminbi",
  ColombianPeso = "ColombianPeso",
  CostaRicanColon = "CostaRicanColon",
  SerbianDinar = "SerbianDinar",
  CubanConvertiblePeso = "CubanConvertiblePeso",
  CubanPeso = "CubanPeso",
  CaboVerdeEscudo = "CaboVerdeEscudo",
  CyprusPound = "CyprusPound",
  CzechKoruna = "CzechKoruna",
  Mark = "Mark",
  DjiboutiFranc = "DjiboutiFranc",
  DanishKrone = "DanishKrone",
  DominicanPeso = "DominicanPeso",
  AlgerianDinar = "AlgerianDinar",
  Kroon = "Kroon",
  EgyptianPound = "EgyptianPound",
  Nakfa = "Nakfa",
  Peseta = "Peseta",
  EthiopianBirr = "EthiopianBirr",
  Euro = "Euro",
  Markka = "Markka",
  FijiDollar = "FijiDollar",
  FalklandIslandsPound = "FalklandIslandsPound",
  Franc = "Franc",
  PoundSterling = "PoundSterling",
  Lari = "Lari",
  GhanaCedi = "GhanaCedi",
  GibraltarPound = "GibraltarPound",
  Dalasi = "Dalasi",
  GuineanFranc = "GuineanFranc",
  Drachma = "Drachma",
  Quetzal = "Quetzal",
  GuineaBissauPeso = "GuineaBissauPeso",
  GuyanaDollar = "GuyanaDollar",
  HongKongDollar = "HongKongDollar",
  Lempira = "Lempira",
  Kuna = "Kuna",
  Gourde = "Gourde",
  Forint = "Forint",
  Rupiah = "Rupiah",
  Punt = "Punt",
  NewIsraeliSheqel = "NewIsraeliSheqel",
  IndianRupee = "IndianRupee",
  IraqiDinar = "IraqiDinar",
  IranianRial = "IranianRial",
  IcelandKrona = "IcelandKrona",
  Lira = "Lira",
  JamaicanDollar = "JamaicanDollar",
  JordanianDinar = "JordanianDinar",
  Yen = "Yen",
  KenyanShilling = "KenyanShilling",
  Som = "Som",
  Riel = "Riel",
  ComorianFranc = "ComorianFranc",
  NorthKoreanWon = "NorthKoreanWon",
  Won = "Won",
  KuwaitiDinar = "KuwaitiDinar",
  CaymanIslandsDollar = "CaymanIslandsDollar",
  Tenge = "Tenge",
  LaoKip = "LaoKip",
  LebanesePound = "LebanesePound",
  SriLankaRupee = "SriLankaRupee",
  LiberianDollar = "LiberianDollar",
  Loti = "Loti",
  Litus = "Litus",
  LuxembourgFranc = "LuxembourgFranc",
  LatvianLats = "LatvianLats",
  LibyanDinar = "LibyanDinar",
  MoroccanDirham = "MoroccanDirham",
  MoldovanLeu = "MoldovanLeu",
  MalagasyAriary = "MalagasyAriary",
  MalagasyFranc = "MalagasyFranc",
  Denar = "Denar",
  Kyat = "Kyat",
  Tugrik = "Tugrik",
  Pataca = "Pataca",
  OldOuguiya = "OldOuguiya",
  Ouguiya = "Ouguiya",
  MalteseLira = "MalteseLira",
  MauritiusRupee = "MauritiusRupee",
  Rufiyaa = "Rufiyaa",
  MalawiKwacha = "MalawiKwacha",
  MexicanPeso = "MexicanPeso",
  MalaysianRinggit = "MalaysianRinggit",
  MozambiqueMetical = "MozambiqueMetical",
  NamibiaDollar = "NamibiaDollar",
  Naira = "Naira",
  CordobaOro = "CordobaOro",
  Guilder = "Guilder",
  NorwegianKrone = "NorwegianKrone",
  NepaleseRupee = "NepaleseRupee",
  NewZealandDollar = "NewZealandDollar",
  RialOmani = "RialOmani",
  Balboa = "Balboa",
  Sol = "Sol",
  Kina = "Kina",
  PhilippinePeso = "PhilippinePeso",
  PakistanRupee = "PakistanRupee",
  ZOty = "ZOty",
  Escudo = "Escudo",
  Guarani = "Guarani",
  QatariRial = "QatariRial",
  RomanianOldLeu = "RomanianOldLeu",
  RomanianLeu = "RomanianLeu",
  RussianRuble = "RussianRuble",
  RwandaFranc = "RwandaFranc",
  SaudiRiyal = "SaudiRiyal",
  SolomonIslandsDollar = "SolomonIslandsDollar",
  SeychellesRupee = "SeychellesRupee",
  SudaneseDinar = "SudaneseDinar",
  SudanesePound = "SudanesePound",
  SwedishKrona = "SwedishKrona",
  SingaporeDollar = "SingaporeDollar",
  SaintHelenaPound = "SaintHelenaPound",
  Tolar = "Tolar",
  SlovakKoruna = "SlovakKoruna",
  Leone = "Leone",
  SomaliShilling = "SomaliShilling",
  SurinamDollar = "SurinamDollar",
  SurinameGuilder = "SurinameGuilder",
  OldDobra = "OldDobra",
  Dobra = "Dobra",
  ElSalvadorColon = "ElSalvadorColon",
  SyrianPound = "SyrianPound",
  Lilangeni = "Lilangeni",
  Baht = "Baht",
  Somoni = "Somoni",
  TurkmenistanManat = "TurkmenistanManat",
  TurkmenistanNewManat = "TurkmenistanNewManat",
  TunisianDinar = "TunisianDinar",
  PaAnga = "PaAnga",
  TimorEscudo = "TimorEscudo",
  TurkishLiraOld = "TurkishLiraOld",
  TurkishLira = "TurkishLira",
  TrinidadAndTobagoDollar = "TrinidadAndTobagoDollar",
  NewTaiwanDollar = "NewTaiwanDollar",
  TanzanianShilling = "TanzanianShilling",
  Hryvnia = "Hryvnia",
  UgandaShilling = "UgandaShilling",
  UsDollar = "UsDollar",
  PesoUruguayo = "PesoUruguayo",
  UzbekistanSum = "UzbekistanSum",
  BolVar = "BolVar",
  BolVarSoberano = "BolVarSoberano",
  Dong = "Dong",
  Vatu = "Vatu",
  Tala = "Tala",
  CfaFrancBeac = "CfaFrancBeac",
  EastCaribbeanDollar = "EastCaribbeanDollar",
  CfaFrancBceao = "CfaFrancBceao",
  CfpFranc = "CfpFranc",
  YemeniRial = "YemeniRial",
  YugoslavianDinar = "YugoslavianDinar",
  Rand = "Rand",
  Kwacha = "Kwacha",
  ZambianKwacha = "ZambianKwacha",
  ZimbabweDollar = "ZimbabweDollar"
}
  