// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const EditionType = {
  "ABR": "AbridgedEdition",
  "ACT": "ActingEdition",
  "ADP": "AdaptedEdition",
  "ALT": "Alternate",
  "ANN": "AnnotatedEdition",
  "BLL": "BilingualEdition",
  "BLP": "BilingualFacingPageEdition",
  "BRL": "BrailleEdition",
  "CMB": "CombinedVolume",
  "CRI": "CriticalEdition",
  "CSP": "Coursepack",
  "DGO": "DigitalOriginal",
  "ENH": "EnhancedEdition",
  "ENL": "EnlargedEdition",
  "EXP": "ExpurgatedEdition",
  "FAC": "FacsimileEdition",
  "FST": "Festschrift",
  "HRE": "HighReadabilityEdition",
  "ILL": "IllustratedEdition",
  "INT": "InternationalEdition",
  "LTE": "LargeTypeLargePrintEdition",
  "MCP": "MicroprintEdition",
  "MDT": "MediaTieIn",
  "MLL": "MultilingualEdition",
  "NED": "NewEdition",
  "NUM": "EditionWithNumberedCopies",
  "PRB": "PreboundEdition",
  "REV": "RevisedEdition",
  "SCH": "SchoolEdition",
  "SIG": "SignedEdition",
  "SMP": "SimplifiedLanguageEdition",
  "SPE": "SpecialEdition",
  "STU": "StudentEdition",
  "TCH": "TeacherSEdition",
  "UBR": "UnabridgedEdition",
  "ULP": "UltraLargePrintEdition",
  "UNN": "EditionWithUnnumberedCopies",
  "UXP": "UnexpurgatedEdition",
  "VAR": "VariorumEdition",
};

export enum EditionTypeEnum {
  AbridgedEdition = "AbridgedEdition",
  ActingEdition = "ActingEdition",
  AdaptedEdition = "AdaptedEdition",
  Alternate = "Alternate",
  AnnotatedEdition = "AnnotatedEdition",
  BilingualEdition = "BilingualEdition",
  BilingualFacingPageEdition = "BilingualFacingPageEdition",
  BrailleEdition = "BrailleEdition",
  CombinedVolume = "CombinedVolume",
  CriticalEdition = "CriticalEdition",
  Coursepack = "Coursepack",
  DigitalOriginal = "DigitalOriginal",
  EnhancedEdition = "EnhancedEdition",
  EnlargedEdition = "EnlargedEdition",
  ExpurgatedEdition = "ExpurgatedEdition",
  FacsimileEdition = "FacsimileEdition",
  Festschrift = "Festschrift",
  HighReadabilityEdition = "HighReadabilityEdition",
  IllustratedEdition = "IllustratedEdition",
  InternationalEdition = "InternationalEdition",
  LargeTypeLargePrintEdition = "LargeTypeLargePrintEdition",
  MicroprintEdition = "MicroprintEdition",
  MediaTieIn = "MediaTieIn",
  MultilingualEdition = "MultilingualEdition",
  NewEdition = "NewEdition",
  EditionWithNumberedCopies = "EditionWithNumberedCopies",
  PreboundEdition = "PreboundEdition",
  RevisedEdition = "RevisedEdition",
  SchoolEdition = "SchoolEdition",
  SignedEdition = "SignedEdition",
  SimplifiedLanguageEdition = "SimplifiedLanguageEdition",
  SpecialEdition = "SpecialEdition",
  StudentEdition = "StudentEdition",
  TeacherSEdition = "TeacherSEdition",
  UnabridgedEdition = "UnabridgedEdition",
  UltraLargePrintEdition = "UltraLargePrintEdition",
  EditionWithUnnumberedCopies = "EditionWithUnnumberedCopies",
  UnexpurgatedEdition = "UnexpurgatedEdition",
  VariorumEdition = "VariorumEdition"
}
  