export const EditionType = {
  "ABR": "AbridgedEdition",
  "ACT": "ActingEdition",
  "ADP": "AdaptedEdition",
  "ALT": "Alternate",
  "ANN": "AnnotatedEdition",
  "BLL": "BilingualEdition",
  "BLP": "BilingualFacingPageEdition",
  "BRL": "BrailleEdition",
  "CMB": "CombinedVolume",
  "CRI": "CriticalEdition",
  "CSP": "Coursepack",
  "DGO": "DigitalOriginal",
  "ENH": "EnhancedEdition",
  "ENL": "EnlargedEdition",
  "EXP": "ExpurgatedEdition",
  "FAC": "FacsimileEdition",
  "FST": "Festschrift",
  "HRE": "HighReadabilityEdition",
  "ILL": "IllustratedEdition",
  "INT": "InternationalEdition",
  "LTE": "LargeTypeLargePrintEdition",
  "MCP": "MicroprintEdition",
  "MDT": "MediaTieIn",
  "MLL": "MultilingualEdition",
  "NED": "NewEdition",
  "NUM": "EditionWithNumberedCopies",
  "PRB": "PreboundEdition",
  "REV": "RevisedEdition",
  "SCH": "SchoolEdition",
  "SIG": "SignedEdition",
  "SMP": "SimplifiedLanguageEdition",
  "SPE": "SpecialEdition",
  "STU": "StudentEdition",
  "TCH": "TeacherSEdition",
  "UBR": "UnabridgedEdition",
  "ULP": "UltraLargePrintEdition",
  "UNN": "EditionWithUnnumberedCopies",
  "UXP": "UnexpurgatedEdition",
  "VAR": "VariorumEdition",
};

export enum EditionTypeEnum {
  AbridgedEdition,
  ActingEdition,
  AdaptedEdition,
  Alternate,
  AnnotatedEdition,
  BilingualEdition,
  BilingualFacingPageEdition,
  BrailleEdition,
  CombinedVolume,
  CriticalEdition,
  Coursepack,
  DigitalOriginal,
  EnhancedEdition,
  EnlargedEdition,
  ExpurgatedEdition,
  FacsimileEdition,
  Festschrift,
  HighReadabilityEdition,
  IllustratedEdition,
  InternationalEdition,
  LargeTypeLargePrintEdition,
  MicroprintEdition,
  MediaTieIn,
  MultilingualEdition,
  NewEdition,
  EditionWithNumberedCopies,
  PreboundEdition,
  RevisedEdition,
  SchoolEdition,
  SignedEdition,
  SimplifiedLanguageEdition,
  SpecialEdition,
  StudentEdition,
  TeacherSEdition,
  UnabridgedEdition,
  UltraLargePrintEdition,
  EditionWithUnnumberedCopies,
  UnexpurgatedEdition,
  VariorumEdition
}
