// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const EPublicationAccessibilityDetails = {
  "00": "AccessibilitySummary",
  "01": "LiaComplianceScheme",
  "02": "EpubAccessibilitySpecification_1_0A",
  "03": "EpubAccessibilitySpecification_1_0Aa",
  "05": "PdfUa",
  "09": "Inaccessible",
  "10": "NoReadingSystemAccessibilityOptionsDisabledExcept",
  "11": "TableOfContentsNavigation",
  "12": "IndexNavigation",
  "13": "ReadingOrder",
  "14": "ShortAlternativeDescriptions",
  "15": "FullAlternativeDescriptions",
  "16": "VisualisedDataAlsoAvailableAsNonGraphicalData",
  "17": "AccessibleMathContent",
  "18": "AccessibleChemContent",
  "19": "PrintEquivalentPageNumbering",
  "20": "SynchronisedPreRecordedAudio",
  "21": "TextToSpeechHintingProvided",
  "22": "LanguageTaggingProvided",
  "24": "DyslexiaReadability",
  "25": "UseOfColor",
  "26": "UseOfContrast",
  "27": "UseOfAudio",
  "28": "FullAlternativeAudioDescriptions",
  "29": "NextPreviousNavigation",
  "93": "ComplianceCertificationBy",
  "94": "ComplianceWebPageForDetailedAccessibilityInformation",
  "95": "TrustedIntermediarySWebPageForDetailedAccessibilityInformation",
  "96": "PublisherSWebPageForDetailedAccessibilityInformation",
  "97": "CompatibilityTested",
  "98": "TrustedIntermediaryContact",
  "99": "PublisherContactForFurtherAccessibilityInformation",
};

export enum EPublicationAccessibilityDetailsEnum {
  AccessibilitySummary,
  LiaComplianceScheme,
  EpubAccessibilitySpecification_1_0A,
  EpubAccessibilitySpecification_1_0Aa,
  PdfUa,
  Inaccessible,
  NoReadingSystemAccessibilityOptionsDisabledExcept,
  TableOfContentsNavigation,
  IndexNavigation,
  ReadingOrder,
  ShortAlternativeDescriptions,
  FullAlternativeDescriptions,
  VisualisedDataAlsoAvailableAsNonGraphicalData,
  AccessibleMathContent,
  AccessibleChemContent,
  PrintEquivalentPageNumbering,
  SynchronisedPreRecordedAudio,
  TextToSpeechHintingProvided,
  LanguageTaggingProvided,
  DyslexiaReadability,
  UseOfColor,
  UseOfContrast,
  UseOfAudio,
  FullAlternativeAudioDescriptions,
  NextPreviousNavigation,
  ComplianceCertificationBy,
  ComplianceWebPageForDetailedAccessibilityInformation,
  TrustedIntermediarySWebPageForDetailedAccessibilityInformation,
  PublisherSWebPageForDetailedAccessibilityInformation,
  CompatibilityTested,
  TrustedIntermediaryContact,
  PublisherContactForFurtherAccessibilityInformation
}
  