// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const IllustrationAndOtherContentType = {
  "00": "UnspecifiedSeeDescription",
  "01": "IllustrationsBlackAndWhite",
  "02": "IllustrationsColor",
  "03": "HalftonesBlackAndWhite",
  "04": "HalftonesColor",
  "05": "LineDrawingsBlackAndWhite",
  "06": "LineDrawingsColor",
  "07": "TablesBlackAndWhite",
  "08": "TablesColor",
  "09": "IllustrationsUnspecified",
  "10": "HalftonesUnspecified",
  "11": "TablesUnspecified",
  "12": "LineDrawingsUnspecified",
  "13": "HalftonesDuotone",
  "14": "Maps",
  "15": "Frontispiece",
  "16": "Diagrams",
  "17": "Figures",
  "18": "Charts",
  "19": "RecordedMusicItems",
  "20": "PrintedMusicItems",
  "21": "Graphs",
  "22": "PlatesUnspecified",
  "23": "PlatesBlackAndWhite",
  "24": "PlatesColor",
  "25": "Index",
  "26": "Bibliography",
  "27": "InsetMaps",
  "28": "GpsGrids",
  "29": "Glossary",
  "30": "TableOfContents",
};

export enum IllustrationAndOtherContentTypeEnum {
  UnspecifiedSeeDescription = "UnspecifiedSeeDescription",
  IllustrationsBlackAndWhite = "IllustrationsBlackAndWhite",
  IllustrationsColor = "IllustrationsColor",
  HalftonesBlackAndWhite = "HalftonesBlackAndWhite",
  HalftonesColor = "HalftonesColor",
  LineDrawingsBlackAndWhite = "LineDrawingsBlackAndWhite",
  LineDrawingsColor = "LineDrawingsColor",
  TablesBlackAndWhite = "TablesBlackAndWhite",
  TablesColor = "TablesColor",
  IllustrationsUnspecified = "IllustrationsUnspecified",
  HalftonesUnspecified = "HalftonesUnspecified",
  TablesUnspecified = "TablesUnspecified",
  LineDrawingsUnspecified = "LineDrawingsUnspecified",
  HalftonesDuotone = "HalftonesDuotone",
  Maps = "Maps",
  Frontispiece = "Frontispiece",
  Diagrams = "Diagrams",
  Figures = "Figures",
  Charts = "Charts",
  RecordedMusicItems = "RecordedMusicItems",
  PrintedMusicItems = "PrintedMusicItems",
  Graphs = "Graphs",
  PlatesUnspecified = "PlatesUnspecified",
  PlatesBlackAndWhite = "PlatesBlackAndWhite",
  PlatesColor = "PlatesColor",
  Index = "Index",
  Bibliography = "Bibliography",
  InsetMaps = "InsetMaps",
  GpsGrids = "GpsGrids",
  Glossary = "Glossary",
  TableOfContents = "TableOfContents"
}
  