// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const LanguageBasedOnIso_639_2B = {
  "aar": "Afar",
  "abk": "Abkhaz",
  "ace": "Achinese",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adygei",
  "afa": "AfroAsiaticLanguages",
  "afh": "Afrihili",
  "afr": "Afrikaans",
  "ain": "Ainu",
  "aka": "Akan",
  "akk": "Akkadian",
  "alb": "Albanian",
  "ale": "Aleut",
  "alg": "AlgonquianLanguages",
  "alt": "SouthernAltai",
  "amh": "Amharic",
  "ang": "EnglishOldCa_450_1100",
  "anp": "Angika",
  "apa": "ApacheLanguages",
  "ara": "Arabic",
  "arc": "OfficialAramaicImperialAramaic_700_300Bce",
  "arg": "Aragonese",
  "arm": "Armenian",
  "arn": "MapudungunMapuche",
  "arp": "Arapaho",
  "art": "ArtificialLanguages",
  "arw": "Arawak",
  "asm": "Assamese",
  "ast": "AsturianBableLeoneseAsturleonese",
  "ath": "AthapascanLanguages",
  "aus": "AustralianLanguages",
  "ava": "Avaric",
  "ave": "Avestan",
  "awa": "Awadhi",
  "aym": "Aymara",
  "aze": "Azerbaijani",
  "bad": "BandaLanguages",
  "bai": "BamilekeLanguages",
  "bak": "Bashkir",
  "bal": "Baluchi",
  "bam": "Bambara",
  "ban": "Balinese",
  "baq": "Basque",
  "bas": "Basa",
  "bat": "BalticLanguages",
  "bej": "BejaBedawiyet",
  "bel": "Belarusian",
  "bem": "Bemba",
  "ben": "Bengali",
  "ber": "BerberLanguages",
  "bho": "Bhojpuri",
  "bih": "BihariLanguages",
  "bik": "Bikol",
  "bin": "BiniEdo",
  "bis": "Bislama",
  "bla": "Siksika",
  "bnt": "BantuLanguages",
  "bos": "Bosnian",
  "bra": "Braj",
  "bre": "Breton",
  "btk": "BatakLanguages",
  "bua": "Buriat",
  "bug": "Buginese",
  "bul": "Bulgarian",
  "bur": "Burmese",
  "byn": "BlinBilin",
  "cad": "Caddo",
  "cai": "CentralAmericanIndianLanguages",
  "car": "GalibiCarib",
  "cat": "Catalan",
  "cau": "CaucasianLanguages",
  "ceb": "Cebuano",
  "cel": "CelticLanguages",
  "cha": "Chamorro",
  "chb": "Chibcha",
  "che": "Chechen",
  "chg": "Chagatai",
  "chi": "Chinese",
  "chk": "ChuukeseTruk",
  "chm": "Mari",
  "chn": "ChinookJargon",
  "cho": "Choctaw",
  "chp": "ChipewyanDeneSuline",
  "chr": "Cherokee",
  "chu": "ChurchSlavicOldSlavonicChurchSlavonicOldBulgarianOldChurchSlavonic",
  "chv": "Chuvash",
  "chy": "Cheyenne",
  "ckb": "CentralKurdishSorani",
  "cmc": "ChamicLanguages",
  "cmn": "Mandarin",
  "cnr": "Montenegrin",
  "cop": "Coptic",
  "cor": "Cornish",
  "cos": "Corsican",
  "cpe": "CreolesAndPidginsEnglishBased",
  "cpf": "CreolesAndPidginsFrenchBased",
  "cpp": "CreolesAndPidginsPortugueseBased",
  "cre": "Cree",
  "crh": "CrimeanTurkishCrimeanTatar",
  "crp": "CreolesAndPidgins",
  "csb": "Kashubian",
  "cus": "CushiticLanguages",
  "cze": "Czech",
  "dak": "Dakota",
  "dan": "Danish",
  "dar": "Dargwa",
  "day": "LandDayakLanguages",
  "del": "Delaware",
  "den": "SlaveAthapascan",
  "dgr": "Dogrib",
  "din": "Dinka",
  "div": "DivehiDhivehiMaldivian",
  "doi": "Dogri",
  "dra": "DravidianLanguages",
  "dsb": "LowerSorbian",
  "dua": "Duala",
  "dum": "DutchMiddleCa_1050_1350",
  "dut": "DutchFlemish",
  "dyu": "Dyula",
  "dzo": "Dzongkha",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "EgyptianAncient",
  "eka": "Ekajuk",
  "elx": "Elamite",
  "eng": "English",
  "enm": "EnglishMiddle_1100_1500",
  "epo": "Esperanto",
  "est": "Estonian",
  "ewe": "Ewe",
  "ewo": "Ewondo",
  "fan": "Fang",
  "fao": "Faroese",
  "fat": "Fanti",
  "fij": "Fijian",
  "fil": "FilipinoPilipino",
  "fin": "Finnish",
  "fit": "MeNkieliTornedalenFinnish",
  "fiu": "FinnoUgrianLanguages",
  "fkv": "Kvensk",
  "fon": "Fon",
  "fre": "French",
  "frm": "FrenchMiddleCa_1400_1600",
  "fro": "FrenchOldCa_842_1400",
  "frr": "NorthernFrisian",
  "frs": "EasternFrisian",
  "fry": "WesternFrisian",
  "ful": "Fulah",
  "fur": "Friulian",
  "gaa": "G",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gem": "GermanicLanguages",
  "geo": "Georgian",
  "ger": "German",
  "gez": "EthiopicGeEz",
  "gil": "Gilbertese",
  "gla": "ScottishGaelic",
  "gle": "Irish",
  "glg": "Galician",
  "glv": "Manx",
  "gmh": "GermanMiddleHighCa_1050_1500",
  "goh": "GermanOldHighCa_750_1050",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "GreekAncientTo_1453",
  "gre": "GreekModern_1453",
  "grn": "Guarani",
  "grt": "Garo",
  "gsw": "SwissGermanAlemannic",
  "guj": "Gujarati",
  "gwi": "GwichIn",
  "hai": "Haida",
  "hat": "HaitianFrenchCreole",
  "hau": "Hausa",
  "haw": "Hawaiian",
  "heb": "Hebrew",
  "her": "Herero",
  "hil": "Hiligaynon",
  "him": "HimachaliLanguagesWesternPahariLanguages",
  "hin": "Hindi",
  "hit": "Hittite",
  "hmn": "HmongMong",
  "hmo": "HiriMotu",
  "hrv": "Croatian",
  "hsb": "UpperSorbian",
  "hun": "Hungarian",
  "hup": "Hupa",
  "iba": "Iban",
  "ibo": "Igbo",
  "ice": "Icelandic",
  "ido": "Ido",
  "iii": "SichuanYiNuosu",
  "ijo": "IjoLanguages",
  "iku": "Inuktitut",
  "ile": "InterlingueOccidental",
  "ilo": "Iloko",
  "ina": "InterlinguaInternationalAuxiliaryLanguageAssociation",
  "inc": "IndicLanguages",
  "ind": "Indonesian",
  "ine": "IndoEuropeanLanguages",
  "inh": "Ingush",
  "ipk": "Inupiaq",
  "ira": "IranianLanguages",
  "iro": "IroquoianLanguages",
  "ita": "Italian",
  "jav": "Javanese",
  "jbo": "Lojban",
  "jpn": "Japanese",
  "jpr": "JudeoPersian",
  "jrb": "JudeoArabic",
  "kaa": "KaraKalpak",
  "kab": "Kabyle",
  "kac": "KachinJingpho",
  "kal": "KalTdlisutGreenlandic",
  "kam": "Kamba",
  "kan": "Kannada",
  "kar": "KarenLanguages",
  "kas": "Kashmiri",
  "kau": "Kanuri",
  "kaw": "Kawi",
  "kaz": "Kazakh",
  "kbd": "KabardianCircassian",
  "kdr": "Karaim",
  "kha": "Khasi",
  "khi": "KhoisanLanguages",
  "khm": "CentralKhmer",
  "kho": "KhotaneseSakan",
  "kik": "KikuyuGikuyu",
  "kin": "Kinyarwanda",
  "kir": "KirghizKyrgyz",
  "kmb": "Kimbundu",
  "kok": "Konkani",
  "kom": "Komi",
  "kon": "Kongo",
  "kor": "Korean",
  "kos": "KusaieanCarolineIslands",
  "kpe": "Kpelle",
  "krc": "KarachayBalkar",
  "krl": "Karelian",
  "kro": "KruLanguages",
  "kru": "Kurukh",
  "kua": "Kuanyama",
  "kum": "Kumyk",
  "kur": "Kurdish",
  "kut": "Kutenai",
  "lad": "Ladino",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lao": "Lao",
  "lat": "Latin",
  "lav": "Latvian",
  "lez": "Lezgian",
  "lij": "Ligurian",
  "lim": "Limburgish",
  "lin": "Lingala",
  "lit": "Lithuanian",
  "lmo": "Lombard",
  "lol": "MongoNkundu",
  "loz": "Lozi",
  "ltz": "LuxembourgishLetzeburgesch",
  "lua": "LubaLulua",
  "lub": "LubaKatanga",
  "lug": "Ganda",
  "lui": "LuiseO",
  "lun": "Lunda",
  "luo": "LuoKenyaAndTanzania",
  "lus": "Lushai",
  "mac": "Macedonian",
  "mad": "Madurese",
  "mag": "Magahi",
  "mah": "Marshallese",
  "mai": "Maithili",
  "mak": "Makasar",
  "mal": "Malayalam",
  "man": "Mandingo",
  "mao": "Maori",
  "map": "AustronesianLanguages",
  "mar": "Marathi",
  "mas": "Masai",
  "may": "Malay",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mga": "IrishMiddleCa_1100_1550",
  "mic": "MiKmaqMicmac",
  "min": "Minangkabau",
  "mis": "UncodedLanguages",
  "mkh": "MonKhmerLanguages",
  "mlg": "Malagasy",
  "mlt": "Maltese",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "mno": "ManoboLanguages",
  "moh": "Mohawk",
  "mol": "MoldavianMoldovan",
  "mon": "Mongolian",
  "mos": "MoorMossi",
  "mul": "MultipleLanguages",
  "mun": "MundaLanguages",
  "mus": "Creek",
  "mwf": "MurrinhPatha",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "myn": "MayanLanguages",
  "myv": "Erzya",
  "nah": "NahuatlLanguages",
  "nai": "NorthAmericanIndianLanguages",
  "nap": "Neapolitan",
  "nau": "Nauruan",
  "nav": "Navajo",
  "nbl": "NdebeleSouth",
  "nde": "NdebeleNorth",
  "ndo": "Ndonga",
  "nds": "LowGermanLowSaxon",
  "nep": "Nepali",
  "new": "NewariNepalBhasa",
  "nia": "Nias",
  "nic": "NigerKordofanianLanguages",
  "niu": "Niuean",
  "nno": "NorwegianNynorsk",
  "nob": "NorwegianBokmL",
  "nog": "Nogai",
  "non": "OldNorse",
  "nor": "Norwegian",
  "nqo": "NKo",
  "nrf": "GuernSiaisJRriais",
  "nso": "PediSepediNorthernSotho",
  "nub": "NubianLanguages",
  "nwc": "ClassicalNewariOldNewariClassicalNepalBhasa",
  "nya": "ChichewaChewaNyanja",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oci": "OccitanPost_1500",
  "odt": "OldDutchOldLowFranconianCa_400_1050",
  "oji": "Ojibwa",
  "omq": "OtoMangueanLanguages",
  "ori": "Oriya",
  "orm": "Oromo",
  "osa": "Osage",
  "oss": "OssetianOssetic",
  "ota": "TurkishOttoman",
  "oto": "OtomianLanguages",
  "paa": "PapuanLanguages",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "PampangaKapampangan",
  "pan": "Panjabi",
  "pap": "Papiamento",
  "pau": "Palauan",
  "peo": "OldPersianCa_600_400BC",
  "per": "PersianFarsi",
  "pes": "IranianPersianParsi",
  "phi": "PhilippineLanguages",
  "phn": "Phoenician",
  "pli": "Pali",
  "pms": "Piedmontese",
  "pol": "Polish",
  "pon": "Ponapeian",
  "por": "Portuguese",
  "pra": "PrakritLanguages",
  "pro": "ProvenAlOldTo_1500OccitanOldTo_1500",
  "prs": "DariAfghanPersian",
  "pus": "PushtoPashto",
  "qar": "AranS",
  "qav": "Valencian",
  "qgl": "Gallo",
  "qlk": "Lemko",
  "qls": "NeutralLatinAmericanSpanish",
  "que": "Quechua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "RarotonganCookIslandsMaori",
  "rcf": "RUnionCreoleFrench",
  "rgn": "Romagnol",
  "roa": "RomanceLanguages",
  "roh": "Romansh",
  "rom": "Romany",
  "rum": "Romanian",
  "run": "Rundi",
  "rup": "AromanianArumanianMacedoRomanian",
  "rus": "Russian",
  "sad": "Sandawe",
  "sag": "Sango",
  "sah": "Yakut",
  "sai": "SouthAmericanIndianLanguages",
  "sal": "SalishanLanguages",
  "sam": "SamaritanAramaic",
  "san": "Sanskrit",
  "sas": "Sasak",
  "sat": "Santali",
  "scc": "Serbian",
  "scn": "Sicilian",
  "sco": "Scots",
  "scr": "Croatian",
  "sdc": "Sassarese",
  "sdn": "Gallurese",
  "sel": "Selkup",
  "sem": "SemiticLanguages",
  "sga": "IrishOldTo_1100",
  "sgn": "SignLanguages",
  "shn": "Shan",
  "sid": "Sidamo",
  "sin": "SinhalaSinhalese",
  "sio": "SiouanLanguages",
  "sit": "SinoTibetanLanguages",
  "sla": "SlavicLanguages",
  "slo": "Slovak",
  "slv": "Slovenian",
  "sma": "SouthernSami",
  "sme": "NorthernSami",
  "smi": "SamiLanguages",
  "smj": "LuleSami",
  "smn": "InariSami",
  "smo": "Samoan",
  "sms": "SkoltSami",
  "sna": "Shona",
  "snd": "Sindhi",
  "snk": "Soninke",
  "sog": "Sogdian",
  "som": "Somali",
  "son": "SonghaiLanguages",
  "sot": "SothoSesotho",
  "spa": "Spanish",
  "srd": "Sardinian",
  "srn": "SrananTongo",
  "sro": "Campidanese",
  "srp": "Serbian",
  "srr": "Serer",
  "ssa": "NiloSaharanLanguages",
  "ssw": "SwaziSwati",
  "suk": "Sukuma",
  "sun": "Sundanese",
  "sus": "Susu",
  "sux": "Sumerian",
  "swa": "Swahili",
  "swe": "Swedish",
  "syc": "ClassicalSyriac",
  "syr": "Syriac",
  "tah": "Tahitian",
  "tai": "TaiLanguages",
  "tam": "Tamil",
  "tat": "Tatar",
  "tel": "Telugu",
  "tem": "TemneTime",
  "ter": "Terena",
  "tet": "Tetum",
  "tgk": "TajikTajikiPersian",
  "tgl": "Tagalog",
  "tha": "Thai",
  "tib": "Tibetan",
  "tig": "Tigr",
  "tir": "Tigrinya",
  "tiv": "Tiv",
  "tkl": "Tokelauan",
  "tlh": "KlingonTlhInganHol",
  "tli": "Tlingit",
  "tmh": "Tamashek",
  "tog": "TongaNyasa",
  "ton": "Tongan",
  "tpi": "TokPisin",
  "tsi": "Tsimshian",
  "tsn": "Tswana",
  "tso": "Tsonga",
  "tuk": "Turkmen",
  "tum": "Tumbuka",
  "tup": "TupiLanguages",
  "tur": "Turkish",
  "tut": "AltaicLanguages",
  "tvl": "Tuvaluan",
  "twi": "Twi",
  "tyv": "Tuvinian",
  "tzo": "Tzotzil",
  "udm": "Udmurt",
  "uga": "Ugaritic",
  "uig": "UighurUyghur",
  "ukr": "Ukrainian",
  "umb": "Umbundu",
  "und": "UndeterminedLanguage",
  "urd": "Urdu",
  "uzb": "Uzbek",
  "vai": "Vai",
  "vec": "VenetianVenetan",
  "ven": "Venda",
  "vie": "Vietnamese",
  "vol": "VolapK",
  "vot": "Votic",
  "wak": "WakashanLanguages",
  "wal": "WolaittaWolaytta",
  "war": "Waray",
  "was": "Washo",
  "wel": "Welsh",
  "wen": "SorbianLanguages",
  "wln": "Walloon",
  "wol": "Wolof",
  "wym": "Wymysorys",
  "xal": "Kalmyk",
  "xho": "Xhosa",
  "xuu": "KhwedamKxoe",
  "yao": "Yao",
  "yap": "Yapese",
  "yid": "Yiddish",
  "yor": "Yoruba",
  "ypk": "YupikLanguages",
  "yue": "Cantonese",
  "zap": "Zapotec",
  "zbl": "BlissymbolsBlissymbolicsBliss",
  "zen": "Zenaga",
  "zgh": "StandardMoroccanTamazight",
  "zha": "ZhuangChuang",
  "znd": "ZandeLanguages",
  "zul": "Zulu",
  "zun": "Zuni",
  "zxx": "NoLinguisticContent",
  "zza": "ZazaDimiliDimliKirdkiKirmanjkiZazaki",
};

export enum LanguageBasedOnIso_639_2BEnum {
  Afar,
  Abkhaz,
  Achinese,
  Acoli,
  Adangme,
  Adygei,
  AfroAsiaticLanguages,
  Afrihili,
  Afrikaans,
  Ainu,
  Akan,
  Akkadian,
  Albanian,
  Aleut,
  AlgonquianLanguages,
  SouthernAltai,
  Amharic,
  EnglishOldCa_450_1100,
  Angika,
  ApacheLanguages,
  Arabic,
  OfficialAramaicImperialAramaic_700_300Bce,
  Aragonese,
  Armenian,
  MapudungunMapuche,
  Arapaho,
  ArtificialLanguages,
  Arawak,
  Assamese,
  AsturianBableLeoneseAsturleonese,
  AthapascanLanguages,
  AustralianLanguages,
  Avaric,
  Avestan,
  Awadhi,
  Aymara,
  Azerbaijani,
  BandaLanguages,
  BamilekeLanguages,
  Bashkir,
  Baluchi,
  Bambara,
  Balinese,
  Basque,
  Basa,
  BalticLanguages,
  BejaBedawiyet,
  Belarusian,
  Bemba,
  Bengali,
  BerberLanguages,
  Bhojpuri,
  BihariLanguages,
  Bikol,
  BiniEdo,
  Bislama,
  Siksika,
  BantuLanguages,
  Bosnian,
  Braj,
  Breton,
  BatakLanguages,
  Buriat,
  Buginese,
  Bulgarian,
  Burmese,
  BlinBilin,
  Caddo,
  CentralAmericanIndianLanguages,
  GalibiCarib,
  Catalan,
  CaucasianLanguages,
  Cebuano,
  CelticLanguages,
  Chamorro,
  Chibcha,
  Chechen,
  Chagatai,
  Chinese,
  ChuukeseTruk,
  Mari,
  ChinookJargon,
  Choctaw,
  ChipewyanDeneSuline,
  Cherokee,
  ChurchSlavicOldSlavonicChurchSlavonicOldBulgarianOldChurchSlavonic,
  Chuvash,
  Cheyenne,
  CentralKurdishSorani,
  ChamicLanguages,
  Mandarin,
  Montenegrin,
  Coptic,
  Cornish,
  Corsican,
  CreolesAndPidginsEnglishBased,
  CreolesAndPidginsFrenchBased,
  CreolesAndPidginsPortugueseBased,
  Cree,
  CrimeanTurkishCrimeanTatar,
  CreolesAndPidgins,
  Kashubian,
  CushiticLanguages,
  Czech,
  Dakota,
  Danish,
  Dargwa,
  LandDayakLanguages,
  Delaware,
  SlaveAthapascan,
  Dogrib,
  Dinka,
  DivehiDhivehiMaldivian,
  Dogri,
  DravidianLanguages,
  LowerSorbian,
  Duala,
  DutchMiddleCa_1050_1350,
  DutchFlemish,
  Dyula,
  Dzongkha,
  Efik,
  Emilian,
  EgyptianAncient,
  Ekajuk,
  Elamite,
  English,
  EnglishMiddle_1100_1500,
  Esperanto,
  Estonian,
  Ewe,
  Ewondo,
  Fang,
  Faroese,
  Fanti,
  Fijian,
  FilipinoPilipino,
  Finnish,
  MeNkieliTornedalenFinnish,
  FinnoUgrianLanguages,
  Kvensk,
  Fon,
  French,
  FrenchMiddleCa_1400_1600,
  FrenchOldCa_842_1400,
  NorthernFrisian,
  EasternFrisian,
  WesternFrisian,
  Fulah,
  Friulian,
  G,
  Gayo,
  Gbaya,
  GermanicLanguages,
  Georgian,
  German,
  EthiopicGeEz,
  Gilbertese,
  ScottishGaelic,
  Irish,
  Galician,
  Manx,
  GermanMiddleHighCa_1050_1500,
  GermanOldHighCa_750_1050,
  Gondi,
  Gorontalo,
  Gothic,
  Grebo,
  GreekAncientTo_1453,
  GreekModern_1453,
  Guarani,
  Garo,
  SwissGermanAlemannic,
  Gujarati,
  GwichIn,
  Haida,
  HaitianFrenchCreole,
  Hausa,
  Hawaiian,
  Hebrew,
  Herero,
  Hiligaynon,
  HimachaliLanguagesWesternPahariLanguages,
  Hindi,
  Hittite,
  HmongMong,
  HiriMotu,
  Croatian,
  UpperSorbian,
  Hungarian,
  Hupa,
  Iban,
  Igbo,
  Icelandic,
  Ido,
  SichuanYiNuosu,
  IjoLanguages,
  Inuktitut,
  InterlingueOccidental,
  Iloko,
  InterlinguaInternationalAuxiliaryLanguageAssociation,
  IndicLanguages,
  Indonesian,
  IndoEuropeanLanguages,
  Ingush,
  Inupiaq,
  IranianLanguages,
  IroquoianLanguages,
  Italian,
  Javanese,
  Lojban,
  Japanese,
  JudeoPersian,
  JudeoArabic,
  KaraKalpak,
  Kabyle,
  KachinJingpho,
  KalTdlisutGreenlandic,
  Kamba,
  Kannada,
  KarenLanguages,
  Kashmiri,
  Kanuri,
  Kawi,
  Kazakh,
  KabardianCircassian,
  Karaim,
  Khasi,
  KhoisanLanguages,
  CentralKhmer,
  KhotaneseSakan,
  KikuyuGikuyu,
  Kinyarwanda,
  KirghizKyrgyz,
  Kimbundu,
  Konkani,
  Komi,
  Kongo,
  Korean,
  KusaieanCarolineIslands,
  Kpelle,
  KarachayBalkar,
  Karelian,
  KruLanguages,
  Kurukh,
  Kuanyama,
  Kumyk,
  Kurdish,
  Kutenai,
  Ladino,
  Lahnda,
  Lamba,
  Lao,
  Latin,
  Latvian,
  Lezgian,
  Ligurian,
  Limburgish,
  Lingala,
  Lithuanian,
  Lombard,
  MongoNkundu,
  Lozi,
  LuxembourgishLetzeburgesch,
  LubaLulua,
  LubaKatanga,
  Ganda,
  LuiseO,
  Lunda,
  LuoKenyaAndTanzania,
  Lushai,
  Macedonian,
  Madurese,
  Magahi,
  Marshallese,
  Maithili,
  Makasar,
  Malayalam,
  Mandingo,
  Maori,
  AustronesianLanguages,
  Marathi,
  Masai,
  Malay,
  Moksha,
  Mandar,
  Mende,
  IrishMiddleCa_1100_1550,
  MiKmaqMicmac,
  Minangkabau,
  UncodedLanguages,
  MonKhmerLanguages,
  Malagasy,
  Maltese,
  Manchu,
  Manipuri,
  ManoboLanguages,
  Mohawk,
  MoldavianMoldovan,
  Mongolian,
  MoorMossi,
  MultipleLanguages,
  MundaLanguages,
  Creek,
  MurrinhPatha,
  Mirandese,
  Marwari,
  MayanLanguages,
  Erzya,
  NahuatlLanguages,
  NorthAmericanIndianLanguages,
  Neapolitan,
  Nauruan,
  Navajo,
  NdebeleSouth,
  NdebeleNorth,
  Ndonga,
  LowGermanLowSaxon,
  Nepali,
  NewariNepalBhasa,
  Nias,
  NigerKordofanianLanguages,
  Niuean,
  NorwegianNynorsk,
  NorwegianBokmL,
  Nogai,
  OldNorse,
  Norwegian,
  NKo,
  GuernSiaisJRriais,
  PediSepediNorthernSotho,
  NubianLanguages,
  ClassicalNewariOldNewariClassicalNepalBhasa,
  ChichewaChewaNyanja,
  Nyamwezi,
  Nyankole,
  Nyoro,
  Nzima,
  OccitanPost_1500,
  OldDutchOldLowFranconianCa_400_1050,
  Ojibwa,
  OtoMangueanLanguages,
  Oriya,
  Oromo,
  Osage,
  OssetianOssetic,
  TurkishOttoman,
  OtomianLanguages,
  PapuanLanguages,
  Pangasinan,
  Pahlavi,
  PampangaKapampangan,
  Panjabi,
  Papiamento,
  Palauan,
  OldPersianCa_600_400BC,
  PersianFarsi,
  IranianPersianParsi,
  PhilippineLanguages,
  Phoenician,
  Pali,
  Piedmontese,
  Polish,
  Ponapeian,
  Portuguese,
  PrakritLanguages,
  ProvenAlOldTo_1500OccitanOldTo_1500,
  DariAfghanPersian,
  PushtoPashto,
  AranS,
  Valencian,
  Gallo,
  Lemko,
  NeutralLatinAmericanSpanish,
  Quechua,
  Rajasthani,
  Rapanui,
  RarotonganCookIslandsMaori,
  RUnionCreoleFrench,
  Romagnol,
  RomanceLanguages,
  Romansh,
  Romany,
  Romanian,
  Rundi,
  AromanianArumanianMacedoRomanian,
  Russian,
  Sandawe,
  Sango,
  Yakut,
  SouthAmericanIndianLanguages,
  SalishanLanguages,
  SamaritanAramaic,
  Sanskrit,
  Sasak,
  Santali,
  Serbian,
  Sicilian,
  Scots,
  Sassarese,
  Gallurese,
  Selkup,
  SemiticLanguages,
  IrishOldTo_1100,
  SignLanguages,
  Shan,
  Sidamo,
  SinhalaSinhalese,
  SiouanLanguages,
  SinoTibetanLanguages,
  SlavicLanguages,
  Slovak,
  Slovenian,
  SouthernSami,
  NorthernSami,
  SamiLanguages,
  LuleSami,
  InariSami,
  Samoan,
  SkoltSami,
  Shona,
  Sindhi,
  Soninke,
  Sogdian,
  Somali,
  SonghaiLanguages,
  SothoSesotho,
  Spanish,
  Sardinian,
  SrananTongo,
  Campidanese,
  Serer,
  NiloSaharanLanguages,
  SwaziSwati,
  Sukuma,
  Sundanese,
  Susu,
  Sumerian,
  Swahili,
  Swedish,
  ClassicalSyriac,
  Syriac,
  Tahitian,
  TaiLanguages,
  Tamil,
  Tatar,
  Telugu,
  TemneTime,
  Terena,
  Tetum,
  TajikTajikiPersian,
  Tagalog,
  Thai,
  Tibetan,
  Tigr,
  Tigrinya,
  Tiv,
  Tokelauan,
  KlingonTlhInganHol,
  Tlingit,
  Tamashek,
  TongaNyasa,
  Tongan,
  TokPisin,
  Tsimshian,
  Tswana,
  Tsonga,
  Turkmen,
  Tumbuka,
  TupiLanguages,
  Turkish,
  AltaicLanguages,
  Tuvaluan,
  Twi,
  Tuvinian,
  Tzotzil,
  Udmurt,
  Ugaritic,
  UighurUyghur,
  Ukrainian,
  Umbundu,
  UndeterminedLanguage,
  Urdu,
  Uzbek,
  Vai,
  VenetianVenetan,
  Venda,
  Vietnamese,
  VolapK,
  Votic,
  WakashanLanguages,
  WolaittaWolaytta,
  Waray,
  Washo,
  Welsh,
  SorbianLanguages,
  Walloon,
  Wolof,
  Wymysorys,
  Kalmyk,
  Xhosa,
  KhwedamKxoe,
  Yao,
  Yapese,
  Yiddish,
  Yoruba,
  YupikLanguages,
  Cantonese,
  Zapotec,
  BlissymbolsBlissymbolicsBliss,
  Zenaga,
  StandardMoroccanTamazight,
  ZhuangChuang,
  ZandeLanguages,
  Zulu,
  Zuni,
  NoLinguisticContent,
  ZazaDimiliDimliKirdkiKirmanjkiZazaki
}
  