// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const LanguageBasedOnIso_639_2B = {
  "aar": "Afar",
  "abk": "Abkhaz",
  "ace": "Achinese",
  "ach": "Acoli",
  "ada": "Adangme",
  "ady": "Adygei",
  "afa": "AfroAsiaticLanguages",
  "afh": "Afrihili",
  "afr": "Afrikaans",
  "ain": "Ainu",
  "aka": "Akan",
  "akk": "Akkadian",
  "alb": "Albanian",
  "ale": "Aleut",
  "alg": "AlgonquianLanguages",
  "alt": "SouthernAltai",
  "amh": "Amharic",
  "ang": "EnglishOldCa_450_1100",
  "anp": "Angika",
  "apa": "ApacheLanguages",
  "ara": "Arabic",
  "arc": "OfficialAramaicImperialAramaic_700_300Bce",
  "arg": "Aragonese",
  "arm": "Armenian",
  "arn": "MapudungunMapuche",
  "arp": "Arapaho",
  "art": "ArtificialLanguages",
  "arw": "Arawak",
  "asm": "Assamese",
  "ast": "AsturianBableLeoneseAsturleonese",
  "ath": "AthapascanLanguages",
  "aus": "AustralianLanguages",
  "ava": "Avaric",
  "ave": "Avestan",
  "awa": "Awadhi",
  "aym": "Aymara",
  "aze": "Azerbaijani",
  "bad": "BandaLanguages",
  "bai": "BamilekeLanguages",
  "bak": "Bashkir",
  "bal": "Baluchi",
  "bam": "Bambara",
  "ban": "Balinese",
  "baq": "Basque",
  "bas": "Basa",
  "bat": "BalticLanguages",
  "bej": "BejaBedawiyet",
  "bel": "Belarusian",
  "bem": "Bemba",
  "ben": "Bengali",
  "ber": "BerberLanguages",
  "bho": "Bhojpuri",
  "bih": "BihariLanguages",
  "bik": "Bikol",
  "bin": "BiniEdo",
  "bis": "Bislama",
  "bla": "Siksika",
  "bnt": "BantuLanguages",
  "bos": "Bosnian",
  "bra": "Braj",
  "bre": "Breton",
  "btk": "BatakLanguages",
  "bua": "Buriat",
  "bug": "Buginese",
  "bul": "Bulgarian",
  "bur": "Burmese",
  "byn": "BlinBilin",
  "cad": "Caddo",
  "cai": "CentralAmericanIndianLanguages",
  "car": "GalibiCarib",
  "cat": "Catalan",
  "cau": "CaucasianLanguages",
  "ceb": "Cebuano",
  "cel": "CelticLanguages",
  "cha": "Chamorro",
  "chb": "Chibcha",
  "che": "Chechen",
  "chg": "Chagatai",
  "chi": "Chinese",
  "chk": "ChuukeseTruk",
  "chm": "Mari",
  "chn": "ChinookJargon",
  "cho": "Choctaw",
  "chp": "ChipewyanDeneSuline",
  "chr": "Cherokee",
  "chu": "ChurchSlavicOldSlavonicChurchSlavonicOldBulgarianOldChurchSlavonic",
  "chv": "Chuvash",
  "chy": "Cheyenne",
  "ckb": "CentralKurdishSorani",
  "cmc": "ChamicLanguages",
  "cmn": "Mandarin",
  "cnr": "Montenegrin",
  "cop": "Coptic",
  "cor": "Cornish",
  "cos": "Corsican",
  "cpe": "CreolesAndPidginsEnglishBased",
  "cpf": "CreolesAndPidginsFrenchBased",
  "cpp": "CreolesAndPidginsPortugueseBased",
  "cre": "Cree",
  "crh": "CrimeanTurkishCrimeanTatar",
  "crp": "CreolesAndPidgins",
  "csb": "Kashubian",
  "cus": "CushiticLanguages",
  "cze": "Czech",
  "dak": "Dakota",
  "dan": "Danish",
  "dar": "Dargwa",
  "day": "LandDayakLanguages",
  "del": "Delaware",
  "den": "SlaveAthapascan",
  "dgr": "Dogrib",
  "din": "Dinka",
  "div": "DivehiDhivehiMaldivian",
  "doi": "Dogri",
  "dra": "DravidianLanguages",
  "dsb": "LowerSorbian",
  "dua": "Duala",
  "dum": "DutchMiddleCa_1050_1350",
  "dut": "DutchFlemish",
  "dyu": "Dyula",
  "dzo": "Dzongkha",
  "efi": "Efik",
  "egl": "Emilian",
  "egy": "EgyptianAncient",
  "eka": "Ekajuk",
  "elx": "Elamite",
  "eng": "English",
  "enm": "EnglishMiddle_1100_1500",
  "epo": "Esperanto",
  "est": "Estonian",
  "ewe": "Ewe",
  "ewo": "Ewondo",
  "fan": "Fang",
  "fao": "Faroese",
  "fat": "Fanti",
  "fij": "Fijian",
  "fil": "FilipinoPilipino",
  "fin": "Finnish",
  "fit": "MeNkieliTornedalenFinnish",
  "fiu": "FinnoUgrianLanguages",
  "fkv": "Kvensk",
  "fon": "Fon",
  "fre": "French",
  "frm": "FrenchMiddleCa_1400_1600",
  "fro": "FrenchOldCa_842_1400",
  "frr": "NorthernFrisian",
  "frs": "EasternFrisian",
  "fry": "WesternFrisian",
  "ful": "Fulah",
  "fur": "Friulian",
  "gaa": "G",
  "gay": "Gayo",
  "gba": "Gbaya",
  "gem": "GermanicLanguages",
  "geo": "Georgian",
  "ger": "German",
  "gez": "EthiopicGeEz",
  "gil": "Gilbertese",
  "gla": "ScottishGaelic",
  "gle": "Irish",
  "glg": "Galician",
  "glv": "Manx",
  "gmh": "GermanMiddleHighCa_1050_1500",
  "goh": "GermanOldHighCa_750_1050",
  "gon": "Gondi",
  "gor": "Gorontalo",
  "got": "Gothic",
  "grb": "Grebo",
  "grc": "GreekAncientTo_1453",
  "gre": "GreekModern_1453",
  "grn": "Guarani",
  "grt": "Garo",
  "gsw": "SwissGermanAlemannic",
  "guj": "Gujarati",
  "gwi": "GwichIn",
  "hai": "Haida",
  "hat": "HaitianFrenchCreole",
  "hau": "Hausa",
  "haw": "Hawaiian",
  "heb": "Hebrew",
  "her": "Herero",
  "hil": "Hiligaynon",
  "him": "HimachaliLanguagesWesternPahariLanguages",
  "hin": "Hindi",
  "hit": "Hittite",
  "hmn": "HmongMong",
  "hmo": "HiriMotu",
  "hrv": "Croatian",
  "hsb": "UpperSorbian",
  "hun": "Hungarian",
  "hup": "Hupa",
  "iba": "Iban",
  "ibo": "Igbo",
  "ice": "Icelandic",
  "ido": "Ido",
  "iii": "SichuanYiNuosu",
  "ijo": "IjoLanguages",
  "iku": "Inuktitut",
  "ile": "InterlingueOccidental",
  "ilo": "Iloko",
  "ina": "InterlinguaInternationalAuxiliaryLanguageAssociation",
  "inc": "IndicLanguages",
  "ind": "Indonesian",
  "ine": "IndoEuropeanLanguages",
  "inh": "Ingush",
  "ipk": "Inupiaq",
  "ira": "IranianLanguages",
  "iro": "IroquoianLanguages",
  "ita": "Italian",
  "jav": "Javanese",
  "jbo": "Lojban",
  "jpn": "Japanese",
  "jpr": "JudeoPersian",
  "jrb": "JudeoArabic",
  "kaa": "KaraKalpak",
  "kab": "Kabyle",
  "kac": "KachinJingpho",
  "kal": "KalTdlisutGreenlandic",
  "kam": "Kamba",
  "kan": "Kannada",
  "kar": "KarenLanguages",
  "kas": "Kashmiri",
  "kau": "Kanuri",
  "kaw": "Kawi",
  "kaz": "Kazakh",
  "kbd": "KabardianCircassian",
  "kdr": "Karaim",
  "kha": "Khasi",
  "khi": "KhoisanLanguages",
  "khm": "CentralKhmer",
  "kho": "KhotaneseSakan",
  "kik": "KikuyuGikuyu",
  "kin": "Kinyarwanda",
  "kir": "KirghizKyrgyz",
  "kmb": "Kimbundu",
  "kok": "Konkani",
  "kom": "Komi",
  "kon": "Kongo",
  "kor": "Korean",
  "kos": "KusaieanCarolineIslands",
  "kpe": "Kpelle",
  "krc": "KarachayBalkar",
  "krl": "Karelian",
  "kro": "KruLanguages",
  "kru": "Kurukh",
  "kua": "Kuanyama",
  "kum": "Kumyk",
  "kur": "Kurdish",
  "kut": "Kutenai",
  "lad": "Ladino",
  "lah": "Lahnda",
  "lam": "Lamba",
  "lao": "Lao",
  "lat": "Latin",
  "lav": "Latvian",
  "lez": "Lezgian",
  "lij": "Ligurian",
  "lim": "Limburgish",
  "lin": "Lingala",
  "lit": "Lithuanian",
  "lmo": "Lombard",
  "lol": "MongoNkundu",
  "loz": "Lozi",
  "ltz": "LuxembourgishLetzeburgesch",
  "lua": "LubaLulua",
  "lub": "LubaKatanga",
  "lug": "Ganda",
  "lui": "LuiseO",
  "lun": "Lunda",
  "luo": "LuoKenyaAndTanzania",
  "lus": "Lushai",
  "mac": "Macedonian",
  "mad": "Madurese",
  "mag": "Magahi",
  "mah": "Marshallese",
  "mai": "Maithili",
  "mak": "Makasar",
  "mal": "Malayalam",
  "man": "Mandingo",
  "mao": "Maori",
  "map": "AustronesianLanguages",
  "mar": "Marathi",
  "mas": "Masai",
  "may": "Malay",
  "mdf": "Moksha",
  "mdr": "Mandar",
  "men": "Mende",
  "mga": "IrishMiddleCa_1100_1550",
  "mic": "MiKmaqMicmac",
  "min": "Minangkabau",
  "mis": "UncodedLanguages",
  "mkh": "MonKhmerLanguages",
  "mlg": "Malagasy",
  "mlt": "Maltese",
  "mnc": "Manchu",
  "mni": "Manipuri",
  "mno": "ManoboLanguages",
  "moh": "Mohawk",
  "mol": "MoldavianMoldovan",
  "mon": "Mongolian",
  "mos": "MoorMossi",
  "mul": "MultipleLanguages",
  "mun": "MundaLanguages",
  "mus": "Creek",
  "mwf": "MurrinhPatha",
  "mwl": "Mirandese",
  "mwr": "Marwari",
  "myn": "MayanLanguages",
  "myv": "Erzya",
  "nah": "NahuatlLanguages",
  "nai": "NorthAmericanIndianLanguages",
  "nap": "Neapolitan",
  "nau": "Nauruan",
  "nav": "Navajo",
  "nbl": "NdebeleSouth",
  "nde": "NdebeleNorth",
  "ndo": "Ndonga",
  "nds": "LowGermanLowSaxon",
  "nep": "Nepali",
  "new": "NewariNepalBhasa",
  "nia": "Nias",
  "nic": "NigerKordofanianLanguages",
  "niu": "Niuean",
  "nno": "NorwegianNynorsk",
  "nob": "NorwegianBokmL",
  "nog": "Nogai",
  "non": "OldNorse",
  "nor": "Norwegian",
  "nqo": "NKo",
  "nrf": "GuernSiaisJRriais",
  "nso": "PediSepediNorthernSotho",
  "nub": "NubianLanguages",
  "nwc": "ClassicalNewariOldNewariClassicalNepalBhasa",
  "nya": "ChichewaChewaNyanja",
  "nym": "Nyamwezi",
  "nyn": "Nyankole",
  "nyo": "Nyoro",
  "nzi": "Nzima",
  "oci": "OccitanPost_1500",
  "odt": "OldDutchOldLowFranconianCa_400_1050",
  "oji": "Ojibwa",
  "omq": "OtoMangueanLanguages",
  "ori": "Oriya",
  "orm": "Oromo",
  "osa": "Osage",
  "oss": "OssetianOssetic",
  "ota": "TurkishOttoman",
  "oto": "OtomianLanguages",
  "paa": "PapuanLanguages",
  "pag": "Pangasinan",
  "pal": "Pahlavi",
  "pam": "PampangaKapampangan",
  "pan": "Panjabi",
  "pap": "Papiamento",
  "pau": "Palauan",
  "peo": "OldPersianCa_600_400BC",
  "per": "PersianFarsi",
  "pes": "IranianPersianParsi",
  "phi": "PhilippineLanguages",
  "phn": "Phoenician",
  "pli": "Pali",
  "pms": "Piedmontese",
  "pol": "Polish",
  "pon": "Ponapeian",
  "por": "Portuguese",
  "pra": "PrakritLanguages",
  "pro": "ProvenAlOldTo_1500OccitanOldTo_1500",
  "prs": "DariAfghanPersian",
  "pus": "PushtoPashto",
  "qar": "AranS",
  "qav": "Valencian",
  "qgl": "Gallo",
  "qlk": "Lemko",
  "qls": "NeutralLatinAmericanSpanish",
  "que": "Quechua",
  "raj": "Rajasthani",
  "rap": "Rapanui",
  "rar": "RarotonganCookIslandsMaori",
  "rcf": "RUnionCreoleFrench",
  "rgn": "Romagnol",
  "roa": "RomanceLanguages",
  "roh": "Romansh",
  "rom": "Romany",
  "rum": "Romanian",
  "run": "Rundi",
  "rup": "AromanianArumanianMacedoRomanian",
  "rus": "Russian",
  "sad": "Sandawe",
  "sag": "Sango",
  "sah": "Yakut",
  "sai": "SouthAmericanIndianLanguages",
  "sal": "SalishanLanguages",
  "sam": "SamaritanAramaic",
  "san": "Sanskrit",
  "sas": "Sasak",
  "sat": "Santali",
  "scc": "Serbian",
  "scn": "Sicilian",
  "sco": "Scots",
  "scr": "Croatian",
  "sdc": "Sassarese",
  "sdn": "Gallurese",
  "sel": "Selkup",
  "sem": "SemiticLanguages",
  "sga": "IrishOldTo_1100",
  "sgn": "SignLanguages",
  "shn": "Shan",
  "sid": "Sidamo",
  "sin": "SinhalaSinhalese",
  "sio": "SiouanLanguages",
  "sit": "SinoTibetanLanguages",
  "sla": "SlavicLanguages",
  "slo": "Slovak",
  "slv": "Slovenian",
  "sma": "SouthernSami",
  "sme": "NorthernSami",
  "smi": "SamiLanguages",
  "smj": "LuleSami",
  "smn": "InariSami",
  "smo": "Samoan",
  "sms": "SkoltSami",
  "sna": "Shona",
  "snd": "Sindhi",
  "snk": "Soninke",
  "sog": "Sogdian",
  "som": "Somali",
  "son": "SonghaiLanguages",
  "sot": "SothoSesotho",
  "spa": "Spanish",
  "srd": "Sardinian",
  "srn": "SrananTongo",
  "sro": "Campidanese",
  "srp": "Serbian",
  "srr": "Serer",
  "ssa": "NiloSaharanLanguages",
  "ssw": "SwaziSwati",
  "suk": "Sukuma",
  "sun": "Sundanese",
  "sus": "Susu",
  "sux": "Sumerian",
  "swa": "Swahili",
  "swe": "Swedish",
  "syc": "ClassicalSyriac",
  "syr": "Syriac",
  "tah": "Tahitian",
  "tai": "TaiLanguages",
  "tam": "Tamil",
  "tat": "Tatar",
  "tel": "Telugu",
  "tem": "TemneTime",
  "ter": "Terena",
  "tet": "Tetum",
  "tgk": "TajikTajikiPersian",
  "tgl": "Tagalog",
  "tha": "Thai",
  "tib": "Tibetan",
  "tig": "Tigr",
  "tir": "Tigrinya",
  "tiv": "Tiv",
  "tkl": "Tokelauan",
  "tlh": "KlingonTlhInganHol",
  "tli": "Tlingit",
  "tmh": "Tamashek",
  "tog": "TongaNyasa",
  "ton": "Tongan",
  "tpi": "TokPisin",
  "tsi": "Tsimshian",
  "tsn": "Tswana",
  "tso": "Tsonga",
  "tuk": "Turkmen",
  "tum": "Tumbuka",
  "tup": "TupiLanguages",
  "tur": "Turkish",
  "tut": "AltaicLanguages",
  "tvl": "Tuvaluan",
  "twi": "Twi",
  "tyv": "Tuvinian",
  "tzo": "Tzotzil",
  "udm": "Udmurt",
  "uga": "Ugaritic",
  "uig": "UighurUyghur",
  "ukr": "Ukrainian",
  "umb": "Umbundu",
  "und": "UndeterminedLanguage",
  "urd": "Urdu",
  "uzb": "Uzbek",
  "vai": "Vai",
  "vec": "VenetianVenetan",
  "ven": "Venda",
  "vie": "Vietnamese",
  "vol": "VolapK",
  "vot": "Votic",
  "wak": "WakashanLanguages",
  "wal": "WolaittaWolaytta",
  "war": "Waray",
  "was": "Washo",
  "wel": "Welsh",
  "wen": "SorbianLanguages",
  "wln": "Walloon",
  "wol": "Wolof",
  "wym": "Wymysorys",
  "xal": "Kalmyk",
  "xho": "Xhosa",
  "xuu": "KhwedamKxoe",
  "yao": "Yao",
  "yap": "Yapese",
  "yid": "Yiddish",
  "yor": "Yoruba",
  "ypk": "YupikLanguages",
  "yue": "Cantonese",
  "zap": "Zapotec",
  "zbl": "BlissymbolsBlissymbolicsBliss",
  "zen": "Zenaga",
  "zgh": "StandardMoroccanTamazight",
  "zha": "ZhuangChuang",
  "znd": "ZandeLanguages",
  "zul": "Zulu",
  "zun": "Zuni",
  "zxx": "NoLinguisticContent",
  "zza": "ZazaDimiliDimliKirdkiKirmanjkiZazaki",
};

export enum LanguageBasedOnIso_639_2BEnum {
  Afar = "Afar",
  Abkhaz = "Abkhaz",
  Achinese = "Achinese",
  Acoli = "Acoli",
  Adangme = "Adangme",
  Adygei = "Adygei",
  AfroAsiaticLanguages = "AfroAsiaticLanguages",
  Afrihili = "Afrihili",
  Afrikaans = "Afrikaans",
  Ainu = "Ainu",
  Akan = "Akan",
  Akkadian = "Akkadian",
  Albanian = "Albanian",
  Aleut = "Aleut",
  AlgonquianLanguages = "AlgonquianLanguages",
  SouthernAltai = "SouthernAltai",
  Amharic = "Amharic",
  EnglishOldCa_450_1100 = "EnglishOldCa_450_1100",
  Angika = "Angika",
  ApacheLanguages = "ApacheLanguages",
  Arabic = "Arabic",
  OfficialAramaicImperialAramaic_700_300Bce = "OfficialAramaicImperialAramaic_700_300Bce",
  Aragonese = "Aragonese",
  Armenian = "Armenian",
  MapudungunMapuche = "MapudungunMapuche",
  Arapaho = "Arapaho",
  ArtificialLanguages = "ArtificialLanguages",
  Arawak = "Arawak",
  Assamese = "Assamese",
  AsturianBableLeoneseAsturleonese = "AsturianBableLeoneseAsturleonese",
  AthapascanLanguages = "AthapascanLanguages",
  AustralianLanguages = "AustralianLanguages",
  Avaric = "Avaric",
  Avestan = "Avestan",
  Awadhi = "Awadhi",
  Aymara = "Aymara",
  Azerbaijani = "Azerbaijani",
  BandaLanguages = "BandaLanguages",
  BamilekeLanguages = "BamilekeLanguages",
  Bashkir = "Bashkir",
  Baluchi = "Baluchi",
  Bambara = "Bambara",
  Balinese = "Balinese",
  Basque = "Basque",
  Basa = "Basa",
  BalticLanguages = "BalticLanguages",
  BejaBedawiyet = "BejaBedawiyet",
  Belarusian = "Belarusian",
  Bemba = "Bemba",
  Bengali = "Bengali",
  BerberLanguages = "BerberLanguages",
  Bhojpuri = "Bhojpuri",
  BihariLanguages = "BihariLanguages",
  Bikol = "Bikol",
  BiniEdo = "BiniEdo",
  Bislama = "Bislama",
  Siksika = "Siksika",
  BantuLanguages = "BantuLanguages",
  Bosnian = "Bosnian",
  Braj = "Braj",
  Breton = "Breton",
  BatakLanguages = "BatakLanguages",
  Buriat = "Buriat",
  Buginese = "Buginese",
  Bulgarian = "Bulgarian",
  Burmese = "Burmese",
  BlinBilin = "BlinBilin",
  Caddo = "Caddo",
  CentralAmericanIndianLanguages = "CentralAmericanIndianLanguages",
  GalibiCarib = "GalibiCarib",
  Catalan = "Catalan",
  CaucasianLanguages = "CaucasianLanguages",
  Cebuano = "Cebuano",
  CelticLanguages = "CelticLanguages",
  Chamorro = "Chamorro",
  Chibcha = "Chibcha",
  Chechen = "Chechen",
  Chagatai = "Chagatai",
  Chinese = "Chinese",
  ChuukeseTruk = "ChuukeseTruk",
  Mari = "Mari",
  ChinookJargon = "ChinookJargon",
  Choctaw = "Choctaw",
  ChipewyanDeneSuline = "ChipewyanDeneSuline",
  Cherokee = "Cherokee",
  ChurchSlavicOldSlavonicChurchSlavonicOldBulgarianOldChurchSlavonic = "ChurchSlavicOldSlavonicChurchSlavonicOldBulgarianOldChurchSlavonic",
  Chuvash = "Chuvash",
  Cheyenne = "Cheyenne",
  CentralKurdishSorani = "CentralKurdishSorani",
  ChamicLanguages = "ChamicLanguages",
  Mandarin = "Mandarin",
  Montenegrin = "Montenegrin",
  Coptic = "Coptic",
  Cornish = "Cornish",
  Corsican = "Corsican",
  CreolesAndPidginsEnglishBased = "CreolesAndPidginsEnglishBased",
  CreolesAndPidginsFrenchBased = "CreolesAndPidginsFrenchBased",
  CreolesAndPidginsPortugueseBased = "CreolesAndPidginsPortugueseBased",
  Cree = "Cree",
  CrimeanTurkishCrimeanTatar = "CrimeanTurkishCrimeanTatar",
  CreolesAndPidgins = "CreolesAndPidgins",
  Kashubian = "Kashubian",
  CushiticLanguages = "CushiticLanguages",
  Czech = "Czech",
  Dakota = "Dakota",
  Danish = "Danish",
  Dargwa = "Dargwa",
  LandDayakLanguages = "LandDayakLanguages",
  Delaware = "Delaware",
  SlaveAthapascan = "SlaveAthapascan",
  Dogrib = "Dogrib",
  Dinka = "Dinka",
  DivehiDhivehiMaldivian = "DivehiDhivehiMaldivian",
  Dogri = "Dogri",
  DravidianLanguages = "DravidianLanguages",
  LowerSorbian = "LowerSorbian",
  Duala = "Duala",
  DutchMiddleCa_1050_1350 = "DutchMiddleCa_1050_1350",
  DutchFlemish = "DutchFlemish",
  Dyula = "Dyula",
  Dzongkha = "Dzongkha",
  Efik = "Efik",
  Emilian = "Emilian",
  EgyptianAncient = "EgyptianAncient",
  Ekajuk = "Ekajuk",
  Elamite = "Elamite",
  English = "English",
  EnglishMiddle_1100_1500 = "EnglishMiddle_1100_1500",
  Esperanto = "Esperanto",
  Estonian = "Estonian",
  Ewe = "Ewe",
  Ewondo = "Ewondo",
  Fang = "Fang",
  Faroese = "Faroese",
  Fanti = "Fanti",
  Fijian = "Fijian",
  FilipinoPilipino = "FilipinoPilipino",
  Finnish = "Finnish",
  MeNkieliTornedalenFinnish = "MeNkieliTornedalenFinnish",
  FinnoUgrianLanguages = "FinnoUgrianLanguages",
  Kvensk = "Kvensk",
  Fon = "Fon",
  French = "French",
  FrenchMiddleCa_1400_1600 = "FrenchMiddleCa_1400_1600",
  FrenchOldCa_842_1400 = "FrenchOldCa_842_1400",
  NorthernFrisian = "NorthernFrisian",
  EasternFrisian = "EasternFrisian",
  WesternFrisian = "WesternFrisian",
  Fulah = "Fulah",
  Friulian = "Friulian",
  G = "G",
  Gayo = "Gayo",
  Gbaya = "Gbaya",
  GermanicLanguages = "GermanicLanguages",
  Georgian = "Georgian",
  German = "German",
  EthiopicGeEz = "EthiopicGeEz",
  Gilbertese = "Gilbertese",
  ScottishGaelic = "ScottishGaelic",
  Irish = "Irish",
  Galician = "Galician",
  Manx = "Manx",
  GermanMiddleHighCa_1050_1500 = "GermanMiddleHighCa_1050_1500",
  GermanOldHighCa_750_1050 = "GermanOldHighCa_750_1050",
  Gondi = "Gondi",
  Gorontalo = "Gorontalo",
  Gothic = "Gothic",
  Grebo = "Grebo",
  GreekAncientTo_1453 = "GreekAncientTo_1453",
  GreekModern_1453 = "GreekModern_1453",
  Guarani = "Guarani",
  Garo = "Garo",
  SwissGermanAlemannic = "SwissGermanAlemannic",
  Gujarati = "Gujarati",
  GwichIn = "GwichIn",
  Haida = "Haida",
  HaitianFrenchCreole = "HaitianFrenchCreole",
  Hausa = "Hausa",
  Hawaiian = "Hawaiian",
  Hebrew = "Hebrew",
  Herero = "Herero",
  Hiligaynon = "Hiligaynon",
  HimachaliLanguagesWesternPahariLanguages = "HimachaliLanguagesWesternPahariLanguages",
  Hindi = "Hindi",
  Hittite = "Hittite",
  HmongMong = "HmongMong",
  HiriMotu = "HiriMotu",
  Croatian = "Croatian",
  UpperSorbian = "UpperSorbian",
  Hungarian = "Hungarian",
  Hupa = "Hupa",
  Iban = "Iban",
  Igbo = "Igbo",
  Icelandic = "Icelandic",
  Ido = "Ido",
  SichuanYiNuosu = "SichuanYiNuosu",
  IjoLanguages = "IjoLanguages",
  Inuktitut = "Inuktitut",
  InterlingueOccidental = "InterlingueOccidental",
  Iloko = "Iloko",
  InterlinguaInternationalAuxiliaryLanguageAssociation = "InterlinguaInternationalAuxiliaryLanguageAssociation",
  IndicLanguages = "IndicLanguages",
  Indonesian = "Indonesian",
  IndoEuropeanLanguages = "IndoEuropeanLanguages",
  Ingush = "Ingush",
  Inupiaq = "Inupiaq",
  IranianLanguages = "IranianLanguages",
  IroquoianLanguages = "IroquoianLanguages",
  Italian = "Italian",
  Javanese = "Javanese",
  Lojban = "Lojban",
  Japanese = "Japanese",
  JudeoPersian = "JudeoPersian",
  JudeoArabic = "JudeoArabic",
  KaraKalpak = "KaraKalpak",
  Kabyle = "Kabyle",
  KachinJingpho = "KachinJingpho",
  KalTdlisutGreenlandic = "KalTdlisutGreenlandic",
  Kamba = "Kamba",
  Kannada = "Kannada",
  KarenLanguages = "KarenLanguages",
  Kashmiri = "Kashmiri",
  Kanuri = "Kanuri",
  Kawi = "Kawi",
  Kazakh = "Kazakh",
  KabardianCircassian = "KabardianCircassian",
  Karaim = "Karaim",
  Khasi = "Khasi",
  KhoisanLanguages = "KhoisanLanguages",
  CentralKhmer = "CentralKhmer",
  KhotaneseSakan = "KhotaneseSakan",
  KikuyuGikuyu = "KikuyuGikuyu",
  Kinyarwanda = "Kinyarwanda",
  KirghizKyrgyz = "KirghizKyrgyz",
  Kimbundu = "Kimbundu",
  Konkani = "Konkani",
  Komi = "Komi",
  Kongo = "Kongo",
  Korean = "Korean",
  KusaieanCarolineIslands = "KusaieanCarolineIslands",
  Kpelle = "Kpelle",
  KarachayBalkar = "KarachayBalkar",
  Karelian = "Karelian",
  KruLanguages = "KruLanguages",
  Kurukh = "Kurukh",
  Kuanyama = "Kuanyama",
  Kumyk = "Kumyk",
  Kurdish = "Kurdish",
  Kutenai = "Kutenai",
  Ladino = "Ladino",
  Lahnda = "Lahnda",
  Lamba = "Lamba",
  Lao = "Lao",
  Latin = "Latin",
  Latvian = "Latvian",
  Lezgian = "Lezgian",
  Ligurian = "Ligurian",
  Limburgish = "Limburgish",
  Lingala = "Lingala",
  Lithuanian = "Lithuanian",
  Lombard = "Lombard",
  MongoNkundu = "MongoNkundu",
  Lozi = "Lozi",
  LuxembourgishLetzeburgesch = "LuxembourgishLetzeburgesch",
  LubaLulua = "LubaLulua",
  LubaKatanga = "LubaKatanga",
  Ganda = "Ganda",
  LuiseO = "LuiseO",
  Lunda = "Lunda",
  LuoKenyaAndTanzania = "LuoKenyaAndTanzania",
  Lushai = "Lushai",
  Macedonian = "Macedonian",
  Madurese = "Madurese",
  Magahi = "Magahi",
  Marshallese = "Marshallese",
  Maithili = "Maithili",
  Makasar = "Makasar",
  Malayalam = "Malayalam",
  Mandingo = "Mandingo",
  Maori = "Maori",
  AustronesianLanguages = "AustronesianLanguages",
  Marathi = "Marathi",
  Masai = "Masai",
  Malay = "Malay",
  Moksha = "Moksha",
  Mandar = "Mandar",
  Mende = "Mende",
  IrishMiddleCa_1100_1550 = "IrishMiddleCa_1100_1550",
  MiKmaqMicmac = "MiKmaqMicmac",
  Minangkabau = "Minangkabau",
  UncodedLanguages = "UncodedLanguages",
  MonKhmerLanguages = "MonKhmerLanguages",
  Malagasy = "Malagasy",
  Maltese = "Maltese",
  Manchu = "Manchu",
  Manipuri = "Manipuri",
  ManoboLanguages = "ManoboLanguages",
  Mohawk = "Mohawk",
  MoldavianMoldovan = "MoldavianMoldovan",
  Mongolian = "Mongolian",
  MoorMossi = "MoorMossi",
  MultipleLanguages = "MultipleLanguages",
  MundaLanguages = "MundaLanguages",
  Creek = "Creek",
  MurrinhPatha = "MurrinhPatha",
  Mirandese = "Mirandese",
  Marwari = "Marwari",
  MayanLanguages = "MayanLanguages",
  Erzya = "Erzya",
  NahuatlLanguages = "NahuatlLanguages",
  NorthAmericanIndianLanguages = "NorthAmericanIndianLanguages",
  Neapolitan = "Neapolitan",
  Nauruan = "Nauruan",
  Navajo = "Navajo",
  NdebeleSouth = "NdebeleSouth",
  NdebeleNorth = "NdebeleNorth",
  Ndonga = "Ndonga",
  LowGermanLowSaxon = "LowGermanLowSaxon",
  Nepali = "Nepali",
  NewariNepalBhasa = "NewariNepalBhasa",
  Nias = "Nias",
  NigerKordofanianLanguages = "NigerKordofanianLanguages",
  Niuean = "Niuean",
  NorwegianNynorsk = "NorwegianNynorsk",
  NorwegianBokmL = "NorwegianBokmL",
  Nogai = "Nogai",
  OldNorse = "OldNorse",
  Norwegian = "Norwegian",
  NKo = "NKo",
  GuernSiaisJRriais = "GuernSiaisJRriais",
  PediSepediNorthernSotho = "PediSepediNorthernSotho",
  NubianLanguages = "NubianLanguages",
  ClassicalNewariOldNewariClassicalNepalBhasa = "ClassicalNewariOldNewariClassicalNepalBhasa",
  ChichewaChewaNyanja = "ChichewaChewaNyanja",
  Nyamwezi = "Nyamwezi",
  Nyankole = "Nyankole",
  Nyoro = "Nyoro",
  Nzima = "Nzima",
  OccitanPost_1500 = "OccitanPost_1500",
  OldDutchOldLowFranconianCa_400_1050 = "OldDutchOldLowFranconianCa_400_1050",
  Ojibwa = "Ojibwa",
  OtoMangueanLanguages = "OtoMangueanLanguages",
  Oriya = "Oriya",
  Oromo = "Oromo",
  Osage = "Osage",
  OssetianOssetic = "OssetianOssetic",
  TurkishOttoman = "TurkishOttoman",
  OtomianLanguages = "OtomianLanguages",
  PapuanLanguages = "PapuanLanguages",
  Pangasinan = "Pangasinan",
  Pahlavi = "Pahlavi",
  PampangaKapampangan = "PampangaKapampangan",
  Panjabi = "Panjabi",
  Papiamento = "Papiamento",
  Palauan = "Palauan",
  OldPersianCa_600_400BC = "OldPersianCa_600_400BC",
  PersianFarsi = "PersianFarsi",
  IranianPersianParsi = "IranianPersianParsi",
  PhilippineLanguages = "PhilippineLanguages",
  Phoenician = "Phoenician",
  Pali = "Pali",
  Piedmontese = "Piedmontese",
  Polish = "Polish",
  Ponapeian = "Ponapeian",
  Portuguese = "Portuguese",
  PrakritLanguages = "PrakritLanguages",
  ProvenAlOldTo_1500OccitanOldTo_1500 = "ProvenAlOldTo_1500OccitanOldTo_1500",
  DariAfghanPersian = "DariAfghanPersian",
  PushtoPashto = "PushtoPashto",
  AranS = "AranS",
  Valencian = "Valencian",
  Gallo = "Gallo",
  Lemko = "Lemko",
  NeutralLatinAmericanSpanish = "NeutralLatinAmericanSpanish",
  Quechua = "Quechua",
  Rajasthani = "Rajasthani",
  Rapanui = "Rapanui",
  RarotonganCookIslandsMaori = "RarotonganCookIslandsMaori",
  RUnionCreoleFrench = "RUnionCreoleFrench",
  Romagnol = "Romagnol",
  RomanceLanguages = "RomanceLanguages",
  Romansh = "Romansh",
  Romany = "Romany",
  Romanian = "Romanian",
  Rundi = "Rundi",
  AromanianArumanianMacedoRomanian = "AromanianArumanianMacedoRomanian",
  Russian = "Russian",
  Sandawe = "Sandawe",
  Sango = "Sango",
  Yakut = "Yakut",
  SouthAmericanIndianLanguages = "SouthAmericanIndianLanguages",
  SalishanLanguages = "SalishanLanguages",
  SamaritanAramaic = "SamaritanAramaic",
  Sanskrit = "Sanskrit",
  Sasak = "Sasak",
  Santali = "Santali",
  Serbian = "Serbian",
  Sicilian = "Sicilian",
  Scots = "Scots",
  Sassarese = "Sassarese",
  Gallurese = "Gallurese",
  Selkup = "Selkup",
  SemiticLanguages = "SemiticLanguages",
  IrishOldTo_1100 = "IrishOldTo_1100",
  SignLanguages = "SignLanguages",
  Shan = "Shan",
  Sidamo = "Sidamo",
  SinhalaSinhalese = "SinhalaSinhalese",
  SiouanLanguages = "SiouanLanguages",
  SinoTibetanLanguages = "SinoTibetanLanguages",
  SlavicLanguages = "SlavicLanguages",
  Slovak = "Slovak",
  Slovenian = "Slovenian",
  SouthernSami = "SouthernSami",
  NorthernSami = "NorthernSami",
  SamiLanguages = "SamiLanguages",
  LuleSami = "LuleSami",
  InariSami = "InariSami",
  Samoan = "Samoan",
  SkoltSami = "SkoltSami",
  Shona = "Shona",
  Sindhi = "Sindhi",
  Soninke = "Soninke",
  Sogdian = "Sogdian",
  Somali = "Somali",
  SonghaiLanguages = "SonghaiLanguages",
  SothoSesotho = "SothoSesotho",
  Spanish = "Spanish",
  Sardinian = "Sardinian",
  SrananTongo = "SrananTongo",
  Campidanese = "Campidanese",
  Serer = "Serer",
  NiloSaharanLanguages = "NiloSaharanLanguages",
  SwaziSwati = "SwaziSwati",
  Sukuma = "Sukuma",
  Sundanese = "Sundanese",
  Susu = "Susu",
  Sumerian = "Sumerian",
  Swahili = "Swahili",
  Swedish = "Swedish",
  ClassicalSyriac = "ClassicalSyriac",
  Syriac = "Syriac",
  Tahitian = "Tahitian",
  TaiLanguages = "TaiLanguages",
  Tamil = "Tamil",
  Tatar = "Tatar",
  Telugu = "Telugu",
  TemneTime = "TemneTime",
  Terena = "Terena",
  Tetum = "Tetum",
  TajikTajikiPersian = "TajikTajikiPersian",
  Tagalog = "Tagalog",
  Thai = "Thai",
  Tibetan = "Tibetan",
  Tigr = "Tigr",
  Tigrinya = "Tigrinya",
  Tiv = "Tiv",
  Tokelauan = "Tokelauan",
  KlingonTlhInganHol = "KlingonTlhInganHol",
  Tlingit = "Tlingit",
  Tamashek = "Tamashek",
  TongaNyasa = "TongaNyasa",
  Tongan = "Tongan",
  TokPisin = "TokPisin",
  Tsimshian = "Tsimshian",
  Tswana = "Tswana",
  Tsonga = "Tsonga",
  Turkmen = "Turkmen",
  Tumbuka = "Tumbuka",
  TupiLanguages = "TupiLanguages",
  Turkish = "Turkish",
  AltaicLanguages = "AltaicLanguages",
  Tuvaluan = "Tuvaluan",
  Twi = "Twi",
  Tuvinian = "Tuvinian",
  Tzotzil = "Tzotzil",
  Udmurt = "Udmurt",
  Ugaritic = "Ugaritic",
  UighurUyghur = "UighurUyghur",
  Ukrainian = "Ukrainian",
  Umbundu = "Umbundu",
  UndeterminedLanguage = "UndeterminedLanguage",
  Urdu = "Urdu",
  Uzbek = "Uzbek",
  Vai = "Vai",
  VenetianVenetan = "VenetianVenetan",
  Venda = "Venda",
  Vietnamese = "Vietnamese",
  VolapK = "VolapK",
  Votic = "Votic",
  WakashanLanguages = "WakashanLanguages",
  WolaittaWolaytta = "WolaittaWolaytta",
  Waray = "Waray",
  Washo = "Washo",
  Welsh = "Welsh",
  SorbianLanguages = "SorbianLanguages",
  Walloon = "Walloon",
  Wolof = "Wolof",
  Wymysorys = "Wymysorys",
  Kalmyk = "Kalmyk",
  Xhosa = "Xhosa",
  KhwedamKxoe = "KhwedamKxoe",
  Yao = "Yao",
  Yapese = "Yapese",
  Yiddish = "Yiddish",
  Yoruba = "Yoruba",
  YupikLanguages = "YupikLanguages",
  Cantonese = "Cantonese",
  Zapotec = "Zapotec",
  BlissymbolsBlissymbolicsBliss = "BlissymbolsBlissymbolicsBliss",
  Zenaga = "Zenaga",
  StandardMoroccanTamazight = "StandardMoroccanTamazight",
  ZhuangChuang = "ZhuangChuang",
  ZandeLanguages = "ZandeLanguages",
  Zulu = "Zulu",
  Zuni = "Zuni",
  NoLinguisticContent = "NoLinguisticContent",
  ZazaDimiliDimliKirdkiKirmanjkiZazaki = "ZazaDimiliDimliKirdkiKirmanjkiZazaki"
}
  