// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const MeasureType = {
  "01": "Height",
  "02": "Width",
  "03": "Thickness",
  "04": "PageTrimHeight",
  "05": "PageTrimWidth",
  "06": "UnitVolume",
  "07": "UnitCapacity",
  "08": "UnitWeight",
  "09": "DiameterSphere",
  "10": "UnfoldedUnrolledSheetHeight",
  "11": "UnfoldedUnrolledSheetWidth",
  "12": "DiameterTubeOrCylinder",
  "13": "RolledSheetPackageSideMeasure",
  "14": "UnpackagedHeight",
  "15": "UnpackagedWidth",
  "16": "UnpackagedThickness",
  "17": "TotalBatteryWeight",
  "18": "TotalWeightOfLithium",
  "19": "AssembledLength",
  "20": "AssembledWidth",
  "21": "AssembledHeight",
  "23": "CartonLength",
  "24": "CartonWidth",
  "25": "CartonHeight",
  "26": "CartonWeight",
  "27": "PalletLength",
  "28": "PalletWidth",
  "29": "PalletHeight",
  "30": "PalletWeight",
};

export enum MeasureTypeEnum {
  Height,
  Width,
  Thickness,
  PageTrimHeight,
  PageTrimWidth,
  UnitVolume,
  UnitCapacity,
  UnitWeight,
  DiameterSphere,
  UnfoldedUnrolledSheetHeight,
  UnfoldedUnrolledSheetWidth,
  DiameterTubeOrCylinder,
  RolledSheetPackageSideMeasure,
  UnpackagedHeight,
  UnpackagedWidth,
  UnpackagedThickness,
  TotalBatteryWeight,
  TotalWeightOfLithium,
  AssembledLength,
  AssembledWidth,
  AssembledHeight,
  CartonLength,
  CartonWidth,
  CartonHeight,
  CartonWeight,
  PalletLength,
  PalletWidth,
  PalletHeight,
  PalletWeight
}
  