export const NameIdentifierType = {
  "01": "Proprietary",
  "02": "Proprietary",
  "03": "DnbPublisherIdentifier",
  "04": "BRsenvereinVerkehrsnummer",
  "05": "GermanIsbnAgencyPublisherIdentifier",
  "06": "Gln",
  "07": "San",
  "08": "MarcOrganizationCode",
  "10": "CentraalBoekhuisRelatieId",
  "13": "FondscodeBoekenbank",
  "15": "YTunnus",
  "16": "Isni",
  "17": "Pnd",
  "18": "Naco",
  "19": "JapanesePublisherIdentifier",
  "20": "Gkd",
  "21": "Orcid",
  "22": "GappPublisherIdentifier",
  "23": "VatIdentityNumber",
  "24": "JpDistributionIdentifier",
  "25": "Gnd",
  "26": "Duns",
  "27": "RinggoldId",
  "28": "IdentifiantEditeurElectre",
  "29": "EidrPartyDoi",
  "30": "IdentifiantMarqueElectre",
  "31": "ViafId",
  "32": "FundRefDoi",
  "33": "BneCn",
  "34": "BnfControlNumber",
  "35": "Ark",
  "36": "NasjonaltAutoritetsregister",
  "37": "Grid",
  "38": "IdRef",
};

export enum NameIdentifierTypeEnum {
  Proprietary,
  Proprietary,
  DnbPublisherIdentifier,
  BRsenvereinVerkehrsnummer,
  GermanIsbnAgencyPublisherIdentifier,
  Gln,
  San,
  MarcOrganizationCode,
  CentraalBoekhuisRelatieId,
  FondscodeBoekenbank,
  YTunnus,
  Isni,
  Pnd,
  Naco,
  JapanesePublisherIdentifier,
  Gkd,
  Orcid,
  GappPublisherIdentifier,
  VatIdentityNumber,
  JpDistributionIdentifier,
  Gnd,
  Duns,
  RinggoldId,
  IdentifiantEditeurElectre,
  EidrPartyDoi,
  IdentifiantMarqueElectre,
  ViafId,
  FundRefDoi,
  BneCn,
  BnfControlNumber,
  Ark,
  NasjonaltAutoritetsregister,
  Grid,
  IdRef
}
