// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const NameIdentifierType = {
  "01": "Proprietary",
  "02": "Proprietary",
  "03": "DnbPublisherIdentifier",
  "04": "BRsenvereinVerkehrsnummer",
  "05": "GermanIsbnAgencyPublisherIdentifier",
  "06": "Gln",
  "07": "San",
  "08": "MarcOrganizationCode",
  "10": "CentraalBoekhuisRelatieId",
  "13": "FondscodeBoekenbank",
  "15": "YTunnus",
  "16": "Isni",
  "17": "Pnd",
  "18": "Naco",
  "19": "JapanesePublisherIdentifier",
  "20": "Gkd",
  "21": "Orcid",
  "22": "GappPublisherIdentifier",
  "23": "VatIdentityNumber",
  "24": "JpDistributionIdentifier",
  "25": "Gnd",
  "26": "Duns",
  "27": "RinggoldId",
  "28": "IdentifiantEditeurElectre",
  "29": "EidrPartyDoi",
  "30": "IdentifiantMarqueElectre",
  "31": "ViafId",
  "32": "FundRefDoi",
  "33": "BneCn",
  "34": "BnfControlNumber",
  "35": "Ark",
  "36": "NasjonaltAutoritetsregister",
  "37": "Grid",
  "38": "IdRef",
};

export enum NameIdentifierTypeEnum {
  Proprietary = "Proprietary",
  DnbPublisherIdentifier = "DnbPublisherIdentifier",
  BRsenvereinVerkehrsnummer = "BRsenvereinVerkehrsnummer",
  GermanIsbnAgencyPublisherIdentifier = "GermanIsbnAgencyPublisherIdentifier",
  Gln = "Gln",
  San = "San",
  MarcOrganizationCode = "MarcOrganizationCode",
  CentraalBoekhuisRelatieId = "CentraalBoekhuisRelatieId",
  FondscodeBoekenbank = "FondscodeBoekenbank",
  YTunnus = "YTunnus",
  Isni = "Isni",
  Pnd = "Pnd",
  Naco = "Naco",
  JapanesePublisherIdentifier = "JapanesePublisherIdentifier",
  Gkd = "Gkd",
  Orcid = "Orcid",
  GappPublisherIdentifier = "GappPublisherIdentifier",
  VatIdentityNumber = "VatIdentityNumber",
  JpDistributionIdentifier = "JpDistributionIdentifier",
  Gnd = "Gnd",
  Duns = "Duns",
  RinggoldId = "RinggoldId",
  IdentifiantEditeurElectre = "IdentifiantEditeurElectre",
  EidrPartyDoi = "EidrPartyDoi",
  IdentifiantMarqueElectre = "IdentifiantMarqueElectre",
  ViafId = "ViafId",
  FundRefDoi = "FundRefDoi",
  BneCn = "BneCn",
  BnfControlNumber = "BnfControlNumber",
  Ark = "Ark",
  NasjonaltAutoritetsregister = "NasjonaltAutoritetsregister",
  Grid = "Grid",
  IdRef = "IdRef"
}
  