// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const OnixRetailSalesOutletIDs = {
  "SYM": "24Symbols",
  "ACM": "ACMoore",
  "AAP": "AandP",
  "ADL": "Adlibris",
  "ACB": "Akademibokhandeln",
  "AKK": "AkateeminenKirjakauppa",
  "ALB": "AlbertsonS",
  "ALT": "AlmaTalent",
  "AMZ": "Amazon",
  "ANR": "AngusAndRobertson",
  "ANB": "Anobii",
  "APA": "Apabi",
  "APC": "Apple",
  "ASD": "Asda",
  "ASB": "AsiaBooks",
  "AUD": "Audible",
  "AUC": "AudiobooksCom",
  "ATK": "Audioteka",
  "BDL": "BDalton",
  "BNO": "BarnesAndNoble",
  "BDZ": "BdBuzz",
  "BBB": "BedBathAndBeyond",
  "BST": "BestBuy",
  "MMM": "Bibliotheca",
  "BIL": "Bilbary",
  "BLG": "Billigbook",
  "BJW": "BjSWholesaleClub",
  "BLA": "BlackstoneAudio",
  "BLK": "BlackwellS",
  "GOS": "Blinkbox",
  "BKU": "Bokus",
  "BLD": "Bolinda",
  "BCA": "BookClubAssociates",
  "BOO": "Bookbeat",
  "BSH": "Bookish",
  "BKP": "Bookpeople",
  "BRB": "BooksEtc",
  "BKM": "BooksAMillion",
  "BKS": "Bookshout",
  "BTP": "Booktopia",
  "BKY": "BookyFi",
  "BRD": "Borders",
  "BRT": "BritishBookshops",
  "CDL": "CasaDelLibro",
  "CDN": "CdonCom",
  "CEB": "Ceebo",
  "CHD": "ChristianbookCom",
  "CYM": "Citymarket",
  "CMX": "Comixology",
  "COP": "Copia",
  "CST": "Costco",
  "CRB": "CrateAndBarrel",
  "CVS": "CvsDrugStores",
  "CVM": "CvsMediatheques",
  "CYB": "Cyberlibris",
  "DEM": "DeMarque",
  "DSG": "DickSSportingGoods",
  "DIL": "Dilicom",
  "DYM": "Dymocks",
  "EPA": "EPagine",
  "ERD": "EReads",
  "ELC": "EarlyLearningCentre",
  "ESN": "Eason",
  "EBC": "EbooksCorp",
  "ECH": "EChristian",
  "ECI": "ElCorteInglS",
  "ELE": "Electre",
  "ELB": "ElibSe",
  "ELK": "ElisaKirjaKuukausitilaus",
  "ELS": "Elisa",
  "ELL": "EllibsCom",
  "EMP": "Empik",
  "ENH": "EnglishHeritage",
  "EPC": "Epic",
  "FDB": "FeedBooks",
  "FIN": "Findaway",
  "FSP": "Fishpond",
  "FLP": "FlipKart",
  "FNC": "Fnac",
  "FOL": "Follett",
  "FRY": "FrySElectronics",
  "GMS": "Gamestop",
  "GLO": "Glose",
  "GOO": "GoogleBooks",
  "HST": "HastingsEntertainment",
  "HMV": "Hmv",
  "HMD": "HomeDepot",
  "IMM": "ImmatRielFr",
  "IND": "IndigoChapters",
  "IBS": "InternetBookshopItalia",
  "IZN": "Izneo",
  "JBH": "JbHifi",
  "JSM": "JohnSmithAndSon",
  "KMT": "KMart",
  "KID": "KirjaIdea",
  "KPV": "Kirjastopalvelu",
  "KNB": "KnfbBlio",
  "KNO": "KnoInc",
  "KBO": "Kobo",
  "KOO": "Koorong",
  "KOR": "Kortext",
  "KRG": "Kroger",
  "LTP": "Lehtipiste",
  "LWE": "LoweS",
  "MAC": "Mackin",
  "MAG": "Magzter",
  "MKS": "MarksAndSpencer",
  "MAT": "Matras",
  "MMS": "MediaMarktSaturn",
  "ADP": "MessageriesAdp",
  "MCR": "Microcenter",
  "MSF": "Microsoft",
  "MOF": "Mofibo",
  "MRR": "Morrisons",
  "MTC": "Mothercare",
  "MYB": "MyBoox",
  "MYI": "MyiLibrary",
  "NTR": "NationalTrust",
  "NXT": "Nextory",
  "NUM": "Numilog",
  "OFD": "OfficeDepot",
  "OFM": "OfficeMax",
  "OLF": "Olf",
  "OVD": "OverDrive",
  "OYS": "Oyster",
  "PST": "PastTimes",
  "PTS": "PetSmart",
  "PTC": "Petco",
  "PLY": "PlayCom",
  "POK": "Pokkaritukku",
  "PTB": "PotteryBarn",
  "RDB": "Readbooks",
  "RCL": "ReadCloud",
  "RST": "RestorationHardware",
  "RET": "Rethink",
  "RTZ": "RitzCamera",
  "RMB": "RmBooks",
  "RBD": "Rosebud",
  "SGR": "SGroup",
  "SAF": "Safari",
  "SFW": "Safeway",
  "SNS": "SainsburyS",
  "SCR": "Scribd",
  "SLF": "Selfridges",
  "SEQ": "Sequencity",
  "SBT": "ShanghaiBookTraders",
  "SKB": "Skoobe",
  "SMW": "SmashWords",
  "SNY": "Sony",
  "STP": "Staples",
  "STT": "Storytel",
  "SKK": "SuomalainenKirjakauppa",
  "SPL": "SuomalainenPlus",
  "SUP": "Supla",
  "SSK": "SuuriSuomalainenKirjakerho",
  "TRG": "Target",
  "TES": "Tesco",
  "TEA": "TheEbookAlternative",
  "TOL": "Tolino",
  "TSR": "ToysRUs",
  "TSO": "TsoTheStationeryOffice",
  "TXR": "Txtr",
  "UBH": "UgglanBokhandel",
  "VRG": "VirginMegastores",
  "WHS": "WHSmith",
  "WTR": "Waitrose",
  "WLM": "WalMart",
  "WST": "WaterstoneS",
  "WHT": "WhitcoulS",
  "WLS": "WilliamsSonoma",
  "WLW": "Woolworths",
  "YOU": "Youboox",
  "ZVV": "Zavvi",
  "PUB": "PublisherSOwnDirectSales",
  "ZZZ": "Other",
};

export enum OnixRetailSalesOutletIDsEnum {
  "24Symbols" = "24Symbols",
  ACMoore = "ACMoore",
  AandP = "AandP",
  Adlibris = "Adlibris",
  Akademibokhandeln = "Akademibokhandeln",
  AkateeminenKirjakauppa = "AkateeminenKirjakauppa",
  AlbertsonS = "AlbertsonS",
  AlmaTalent = "AlmaTalent",
  Amazon = "Amazon",
  AngusAndRobertson = "AngusAndRobertson",
  Anobii = "Anobii",
  Apabi = "Apabi",
  Apple = "Apple",
  Asda = "Asda",
  AsiaBooks = "AsiaBooks",
  Audible = "Audible",
  AudiobooksCom = "AudiobooksCom",
  Audioteka = "Audioteka",
  BDalton = "BDalton",
  BarnesAndNoble = "BarnesAndNoble",
  BdBuzz = "BdBuzz",
  BedBathAndBeyond = "BedBathAndBeyond",
  BestBuy = "BestBuy",
  Bibliotheca = "Bibliotheca",
  Bilbary = "Bilbary",
  Billigbook = "Billigbook",
  BjSWholesaleClub = "BjSWholesaleClub",
  BlackstoneAudio = "BlackstoneAudio",
  BlackwellS = "BlackwellS",
  Blinkbox = "Blinkbox",
  Bokus = "Bokus",
  Bolinda = "Bolinda",
  BookClubAssociates = "BookClubAssociates",
  Bookbeat = "Bookbeat",
  Bookish = "Bookish",
  Bookpeople = "Bookpeople",
  BooksEtc = "BooksEtc",
  BooksAMillion = "BooksAMillion",
  Bookshout = "Bookshout",
  Booktopia = "Booktopia",
  BookyFi = "BookyFi",
  Borders = "Borders",
  BritishBookshops = "BritishBookshops",
  CasaDelLibro = "CasaDelLibro",
  CdonCom = "CdonCom",
  Ceebo = "Ceebo",
  ChristianbookCom = "ChristianbookCom",
  Citymarket = "Citymarket",
  Comixology = "Comixology",
  Copia = "Copia",
  Costco = "Costco",
  CrateAndBarrel = "CrateAndBarrel",
  CvsDrugStores = "CvsDrugStores",
  CvsMediatheques = "CvsMediatheques",
  Cyberlibris = "Cyberlibris",
  DeMarque = "DeMarque",
  DickSSportingGoods = "DickSSportingGoods",
  Dilicom = "Dilicom",
  Dymocks = "Dymocks",
  EPagine = "EPagine",
  EReads = "EReads",
  EarlyLearningCentre = "EarlyLearningCentre",
  Eason = "Eason",
  EbooksCorp = "EbooksCorp",
  EChristian = "EChristian",
  ElCorteInglS = "ElCorteInglS",
  Electre = "Electre",
  ElibSe = "ElibSe",
  ElisaKirjaKuukausitilaus = "ElisaKirjaKuukausitilaus",
  Elisa = "Elisa",
  EllibsCom = "EllibsCom",
  Empik = "Empik",
  EnglishHeritage = "EnglishHeritage",
  Epic = "Epic",
  FeedBooks = "FeedBooks",
  Findaway = "Findaway",
  Fishpond = "Fishpond",
  FlipKart = "FlipKart",
  Fnac = "Fnac",
  Follett = "Follett",
  FrySElectronics = "FrySElectronics",
  Gamestop = "Gamestop",
  Glose = "Glose",
  GoogleBooks = "GoogleBooks",
  HastingsEntertainment = "HastingsEntertainment",
  Hmv = "Hmv",
  HomeDepot = "HomeDepot",
  ImmatRielFr = "ImmatRielFr",
  IndigoChapters = "IndigoChapters",
  InternetBookshopItalia = "InternetBookshopItalia",
  Izneo = "Izneo",
  JbHifi = "JbHifi",
  JohnSmithAndSon = "JohnSmithAndSon",
  KMart = "KMart",
  KirjaIdea = "KirjaIdea",
  Kirjastopalvelu = "Kirjastopalvelu",
  KnfbBlio = "KnfbBlio",
  KnoInc = "KnoInc",
  Kobo = "Kobo",
  Koorong = "Koorong",
  Kortext = "Kortext",
  Kroger = "Kroger",
  Lehtipiste = "Lehtipiste",
  LoweS = "LoweS",
  Mackin = "Mackin",
  Magzter = "Magzter",
  MarksAndSpencer = "MarksAndSpencer",
  Matras = "Matras",
  MediaMarktSaturn = "MediaMarktSaturn",
  MessageriesAdp = "MessageriesAdp",
  Microcenter = "Microcenter",
  Microsoft = "Microsoft",
  Mofibo = "Mofibo",
  Morrisons = "Morrisons",
  Mothercare = "Mothercare",
  MyBoox = "MyBoox",
  MyiLibrary = "MyiLibrary",
  NationalTrust = "NationalTrust",
  Nextory = "Nextory",
  Numilog = "Numilog",
  OfficeDepot = "OfficeDepot",
  OfficeMax = "OfficeMax",
  Olf = "Olf",
  OverDrive = "OverDrive",
  Oyster = "Oyster",
  PastTimes = "PastTimes",
  PetSmart = "PetSmart",
  Petco = "Petco",
  PlayCom = "PlayCom",
  Pokkaritukku = "Pokkaritukku",
  PotteryBarn = "PotteryBarn",
  Readbooks = "Readbooks",
  ReadCloud = "ReadCloud",
  RestorationHardware = "RestorationHardware",
  Rethink = "Rethink",
  RitzCamera = "RitzCamera",
  RmBooks = "RmBooks",
  Rosebud = "Rosebud",
  SGroup = "SGroup",
  Safari = "Safari",
  Safeway = "Safeway",
  SainsburyS = "SainsburyS",
  Scribd = "Scribd",
  Selfridges = "Selfridges",
  Sequencity = "Sequencity",
  ShanghaiBookTraders = "ShanghaiBookTraders",
  Skoobe = "Skoobe",
  SmashWords = "SmashWords",
  Sony = "Sony",
  Staples = "Staples",
  Storytel = "Storytel",
  SuomalainenKirjakauppa = "SuomalainenKirjakauppa",
  SuomalainenPlus = "SuomalainenPlus",
  Supla = "Supla",
  SuuriSuomalainenKirjakerho = "SuuriSuomalainenKirjakerho",
  Target = "Target",
  Tesco = "Tesco",
  TheEbookAlternative = "TheEbookAlternative",
  Tolino = "Tolino",
  ToysRUs = "ToysRUs",
  TsoTheStationeryOffice = "TsoTheStationeryOffice",
  Txtr = "Txtr",
  UgglanBokhandel = "UgglanBokhandel",
  VirginMegastores = "VirginMegastores",
  WHSmith = "WHSmith",
  Waitrose = "Waitrose",
  WalMart = "WalMart",
  WaterstoneS = "WaterstoneS",
  WhitcoulS = "WhitcoulS",
  WilliamsSonoma = "WilliamsSonoma",
  Woolworths = "Woolworths",
  Youboox = "Youboox",
  Zavvi = "Zavvi",
  PublisherSOwnDirectSales = "PublisherSOwnDirectSales",
  Other = "Other"
}
  