export const OnixRetailSalesOutletIDs = {
  "SYM": "24Symbols",
  "ACM": "ACMoore",
  "AAP": "AandP",
  "ADL": "Adlibris",
  "ACB": "Akademibokhandeln",
  "AKK": "AkateeminenKirjakauppa",
  "ALB": "AlbertsonS",
  "ALT": "AlmaTalent",
  "AMZ": "Amazon",
  "ANR": "AngusAndRobertson",
  "ANB": "Anobii",
  "APA": "Apabi",
  "APC": "Apple",
  "ASD": "Asda",
  "ASB": "AsiaBooks",
  "AUD": "Audible",
  "AUC": "AudiobooksCom",
  "ATK": "Audioteka",
  "BDL": "BDalton",
  "BNO": "BarnesAndNoble",
  "BDZ": "BdBuzz",
  "BBB": "BedBathAndBeyond",
  "BST": "BestBuy",
  "MMM": "Bibliotheca",
  "BIL": "Bilbary",
  "BLG": "Billigbook",
  "BJW": "BjSWholesaleClub",
  "BLA": "BlackstoneAudio",
  "BLK": "BlackwellS",
  "GOS": "Blinkbox",
  "BKU": "Bokus",
  "BLD": "Bolinda",
  "BCA": "BookClubAssociates",
  "BOO": "Bookbeat",
  "BSH": "Bookish",
  "BKP": "Bookpeople",
  "BRB": "BooksEtc",
  "BKM": "BooksAMillion",
  "BKS": "Bookshout",
  "BTP": "Booktopia",
  "BKY": "BookyFi",
  "BRD": "Borders",
  "BRT": "BritishBookshops",
  "CDL": "CasaDelLibro",
  "CDN": "CdonCom",
  "CEB": "Ceebo",
  "CHD": "ChristianbookCom",
  "CYM": "Citymarket",
  "CMX": "Comixology",
  "COP": "Copia",
  "CST": "Costco",
  "CRB": "CrateAndBarrel",
  "CVS": "CvsDrugStores",
  "CVM": "CvsMediatheques",
  "CYB": "Cyberlibris",
  "DEM": "DeMarque",
  "DSG": "DickSSportingGoods",
  "DIL": "Dilicom",
  "DYM": "Dymocks",
  "EPA": "EPagine",
  "ERD": "EReads",
  "ELC": "EarlyLearningCentre",
  "ESN": "Eason",
  "EBC": "EbooksCorp",
  "ECH": "EChristian",
  "ECI": "ElCorteInglS",
  "ELE": "Electre",
  "ELB": "ElibSe",
  "ELK": "ElisaKirjaKuukausitilaus",
  "ELS": "Elisa",
  "ELL": "EllibsCom",
  "EMP": "Empik",
  "ENH": "EnglishHeritage",
  "EPC": "Epic",
  "FDB": "FeedBooks",
  "FIN": "Findaway",
  "FSP": "Fishpond",
  "FLP": "FlipKart",
  "FNC": "Fnac",
  "FOL": "Follett",
  "FRY": "FrySElectronics",
  "GMS": "Gamestop",
  "GLO": "Glose",
  "GOO": "GoogleBooks",
  "HST": "HastingsEntertainment",
  "HMV": "Hmv",
  "HMD": "HomeDepot",
  "IMM": "ImmatRielFr",
  "IND": "IndigoChapters",
  "IBS": "InternetBookshopItalia",
  "IZN": "Izneo",
  "JBH": "JbHifi",
  "JSM": "JohnSmithAndSon",
  "KMT": "KMart",
  "KID": "KirjaIdea",
  "KPV": "Kirjastopalvelu",
  "KNB": "KnfbBlio",
  "KNO": "KnoInc",
  "KBO": "Kobo",
  "KOO": "Koorong",
  "KOR": "Kortext",
  "KRG": "Kroger",
  "LTP": "Lehtipiste",
  "LWE": "LoweS",
  "MAC": "Mackin",
  "MAG": "Magzter",
  "MKS": "MarksAndSpencer",
  "MAT": "Matras",
  "MMS": "MediaMarktSaturn",
  "ADP": "MessageriesAdp",
  "MCR": "Microcenter",
  "MSF": "Microsoft",
  "MOF": "Mofibo",
  "MRR": "Morrisons",
  "MTC": "Mothercare",
  "MYB": "MyBoox",
  "MYI": "MyiLibrary",
  "NTR": "NationalTrust",
  "NXT": "Nextory",
  "NUM": "Numilog",
  "OFD": "OfficeDepot",
  "OFM": "OfficeMax",
  "OLF": "Olf",
  "OVD": "OverDrive",
  "OYS": "Oyster",
  "PST": "PastTimes",
  "PTS": "PetSmart",
  "PTC": "Petco",
  "PLY": "PlayCom",
  "POK": "Pokkaritukku",
  "PTB": "PotteryBarn",
  "RDB": "Readbooks",
  "RCL": "ReadCloud",
  "RST": "RestorationHardware",
  "RET": "Rethink",
  "RTZ": "RitzCamera",
  "RMB": "RmBooks",
  "RBD": "Rosebud",
  "SGR": "SGroup",
  "SAF": "Safari",
  "SFW": "Safeway",
  "SNS": "SainsburyS",
  "SCR": "Scribd",
  "SLF": "Selfridges",
  "SEQ": "Sequencity",
  "SBT": "ShanghaiBookTraders",
  "SKB": "Skoobe",
  "SMW": "SmashWords",
  "SNY": "Sony",
  "STP": "Staples",
  "STT": "Storytel",
  "SKK": "SuomalainenKirjakauppa",
  "SPL": "SuomalainenPlus",
  "SUP": "Supla",
  "SSK": "SuuriSuomalainenKirjakerho",
  "TRG": "Target",
  "TES": "Tesco",
  "TEA": "TheEbookAlternative",
  "TOL": "Tolino",
  "TSR": "ToysRUs",
  "TSO": "TsoTheStationeryOffice",
  "TXR": "Txtr",
  "UBH": "UgglanBokhandel",
  "VRG": "VirginMegastores",
  "WHS": "WHSmith",
  "WTR": "Waitrose",
  "WLM": "WalMart",
  "WST": "WaterstoneS",
  "WHT": "WhitcoulS",
  "WLS": "WilliamsSonoma",
  "WLW": "Woolworths",
  "YOU": "Youboox",
  "ZVV": "Zavvi",
  "PUB": "PublisherSOwnDirectSales",
  "ZZZ": "Other",
};

export enum OnixRetailSalesOutletIDsEnum {
  "24Symbols",
  ACMoore,
  AandP,
  Adlibris,
  Akademibokhandeln,
  AkateeminenKirjakauppa,
  AlbertsonS,
  AlmaTalent,
  Amazon,
  AngusAndRobertson,
  Anobii,
  Apabi,
  Apple,
  Asda,
  AsiaBooks,
  Audible,
  AudiobooksCom,
  Audioteka,
  BDalton,
  BarnesAndNoble,
  BdBuzz,
  BedBathAndBeyond,
  BestBuy,
  Bibliotheca,
  Bilbary,
  Billigbook,
  BjSWholesaleClub,
  BlackstoneAudio,
  BlackwellS,
  Blinkbox,
  Bokus,
  Bolinda,
  BookClubAssociates,
  Bookbeat,
  Bookish,
  Bookpeople,
  BooksEtc,
  BooksAMillion,
  Bookshout,
  Booktopia,
  BookyFi,
  Borders,
  BritishBookshops,
  CasaDelLibro,
  CdonCom,
  Ceebo,
  ChristianbookCom,
  Citymarket,
  Comixology,
  Copia,
  Costco,
  CrateAndBarrel,
  CvsDrugStores,
  CvsMediatheques,
  Cyberlibris,
  DeMarque,
  DickSSportingGoods,
  Dilicom,
  Dymocks,
  EPagine,
  EReads,
  EarlyLearningCentre,
  Eason,
  EbooksCorp,
  EChristian,
  ElCorteInglS,
  Electre,
  ElibSe,
  ElisaKirjaKuukausitilaus,
  Elisa,
  EllibsCom,
  Empik,
  EnglishHeritage,
  Epic,
  FeedBooks,
  Findaway,
  Fishpond,
  FlipKart,
  Fnac,
  Follett,
  FrySElectronics,
  Gamestop,
  Glose,
  GoogleBooks,
  HastingsEntertainment,
  Hmv,
  HomeDepot,
  ImmatRielFr,
  IndigoChapters,
  InternetBookshopItalia,
  Izneo,
  JbHifi,
  JohnSmithAndSon,
  KMart,
  KirjaIdea,
  Kirjastopalvelu,
  KnfbBlio,
  KnoInc,
  Kobo,
  Koorong,
  Kortext,
  Kroger,
  Lehtipiste,
  LoweS,
  Mackin,
  Magzter,
  MarksAndSpencer,
  Matras,
  MediaMarktSaturn,
  MessageriesAdp,
  Microcenter,
  Microsoft,
  Mofibo,
  Morrisons,
  Mothercare,
  MyBoox,
  MyiLibrary,
  NationalTrust,
  Nextory,
  Numilog,
  OfficeDepot,
  OfficeMax,
  Olf,
  OverDrive,
  Oyster,
  PastTimes,
  PetSmart,
  Petco,
  PlayCom,
  Pokkaritukku,
  PotteryBarn,
  Readbooks,
  ReadCloud,
  RestorationHardware,
  Rethink,
  RitzCamera,
  RmBooks,
  Rosebud,
  SGroup,
  Safari,
  Safeway,
  SainsburyS,
  Scribd,
  Selfridges,
  Sequencity,
  ShanghaiBookTraders,
  Skoobe,
  SmashWords,
  Sony,
  Staples,
  Storytel,
  SuomalainenKirjakauppa,
  SuomalainenPlus,
  Supla,
  SuuriSuomalainenKirjakerho,
  Target,
  Tesco,
  TheEbookAlternative,
  Tolino,
  ToysRUs,
  TsoTheStationeryOffice,
  Txtr,
  UgglanBokhandel,
  VirginMegastores,
  WHSmith,
  Waitrose,
  WalMart,
  WaterstoneS,
  WhitcoulS,
  WilliamsSonoma,
  Woolworths,
  Youboox,
  Zavvi,
  PublisherSOwnDirectSales,
  Other
}
