// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const PriceType = {
  "01": "RrpExcludingTax",
  "02": "RrpIncludingTax",
  "03": "FrpExcludingTax",
  "04": "FrpIncludingTax",
  "05": "SupplierSNetPriceExcludingTax",
  "06": "SupplierSNetPriceExcludingTaxRentalGoods",
  "07": "SupplierSNetPriceIncludingTax",
  "08": "SupplierSAlternativeNetPriceExcludingTax",
  "09": "SupplierSAlternativeNetPriceIncludingTax",
  "11": "SpecialSaleRrpExcludingTax",
  "12": "SpecialSaleRrpIncludingTax",
  "13": "SpecialSaleFixedRetailPriceExcludingTax",
  "14": "SpecialSaleFixedRetailPriceIncludingTax",
  "15": "SupplierSNetPriceForSpecialSaleExcludingTax",
  "17": "SupplierSNetPriceForSpecialSaleIncludingTax",
  "21": "PrePublicationRrpExcludingTax",
  "22": "PrePublicationRrpIncludingTax",
  "23": "PrePublicationFixedRetailPriceExcludingTax",
  "24": "PrePublicationFixedRetailPriceIncludingTax",
  "25": "SupplierSPrePublicationNetPriceExcludingTax",
  "27": "SupplierSPrePublicationNetPriceIncludingTax",
  "31": "FreightPassThroughRrpExcludingTax",
  "32": "FreightPassThroughBillingPriceExcludingTax",
  "33": "ImporterSFixedRetailPriceExcludingTax",
  "34": "ImporterSFixedRetailPriceIncludingTax",
  "41": "PublishersRetailPriceExcludingTax",
  "42": "PublishersRetailPriceIncludingTax",
};

export enum PriceTypeEnum {
  RrpExcludingTax = "RrpExcludingTax",
  RrpIncludingTax = "RrpIncludingTax",
  FrpExcludingTax = "FrpExcludingTax",
  FrpIncludingTax = "FrpIncludingTax",
  SupplierSNetPriceExcludingTax = "SupplierSNetPriceExcludingTax",
  SupplierSNetPriceExcludingTaxRentalGoods = "SupplierSNetPriceExcludingTaxRentalGoods",
  SupplierSNetPriceIncludingTax = "SupplierSNetPriceIncludingTax",
  SupplierSAlternativeNetPriceExcludingTax = "SupplierSAlternativeNetPriceExcludingTax",
  SupplierSAlternativeNetPriceIncludingTax = "SupplierSAlternativeNetPriceIncludingTax",
  SpecialSaleRrpExcludingTax = "SpecialSaleRrpExcludingTax",
  SpecialSaleRrpIncludingTax = "SpecialSaleRrpIncludingTax",
  SpecialSaleFixedRetailPriceExcludingTax = "SpecialSaleFixedRetailPriceExcludingTax",
  SpecialSaleFixedRetailPriceIncludingTax = "SpecialSaleFixedRetailPriceIncludingTax",
  SupplierSNetPriceForSpecialSaleExcludingTax = "SupplierSNetPriceForSpecialSaleExcludingTax",
  SupplierSNetPriceForSpecialSaleIncludingTax = "SupplierSNetPriceForSpecialSaleIncludingTax",
  PrePublicationRrpExcludingTax = "PrePublicationRrpExcludingTax",
  PrePublicationRrpIncludingTax = "PrePublicationRrpIncludingTax",
  PrePublicationFixedRetailPriceExcludingTax = "PrePublicationFixedRetailPriceExcludingTax",
  PrePublicationFixedRetailPriceIncludingTax = "PrePublicationFixedRetailPriceIncludingTax",
  SupplierSPrePublicationNetPriceExcludingTax = "SupplierSPrePublicationNetPriceExcludingTax",
  SupplierSPrePublicationNetPriceIncludingTax = "SupplierSPrePublicationNetPriceIncludingTax",
  FreightPassThroughRrpExcludingTax = "FreightPassThroughRrpExcludingTax",
  FreightPassThroughBillingPriceExcludingTax = "FreightPassThroughBillingPriceExcludingTax",
  ImporterSFixedRetailPriceExcludingTax = "ImporterSFixedRetailPriceExcludingTax",
  ImporterSFixedRetailPriceIncludingTax = "ImporterSFixedRetailPriceIncludingTax",
  PublishersRetailPriceExcludingTax = "PublishersRetailPriceExcludingTax",
  PublishersRetailPriceIncludingTax = "PublishersRetailPriceIncludingTax"
}
  