// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const ProductRelation = {
  "00": "Unspecified",
  "01": "Includes",
  "02": "IsPartOf",
  "03": "Replaces",
  "04": "HasCompanionProduct",
  "05": "ReplacedBy",
  "06": "AlternativeFormat",
  "07": "HasAncillaryProduct",
  "08": "IsAncillaryTo",
  "09": "IsRemainderedAs",
  "10": "IsRemainderOf",
  "11": "IsOtherLanguageVersionOf",
  "12": "PublisherSSuggestedAlternative",
  "13": "EpublicationBasedOnPrintProduct",
  "16": "PodReplacementFor",
  "17": "ReplacedByPod",
  "18": "IsSpecialEditionOf",
  "19": "HasSpecialEdition",
  "20": "IsPreboundEditionOf",
  "21": "IsOriginalOfPreboundEdition",
  "22": "ProductBySameAuthor",
  "23": "SimilarProduct",
  "24": "IsFacsimileOf",
  "25": "IsOriginalOfFacsimile",
  "26": "IsLicenseFor",
  "27": "ElectronicVersionAvailableAs",
  "28": "EnhancedVersionAvailableAs",
  "29": "BasicVersionAvailableAs",
  "30": "ProductInSameCollection",
  "31": "HasAlternativeInADifferentMarketSector",
  "32": "HasEquivalentIntendedForADifferentMarket",
  "33": "HasAlternativeIntendedForDifferentMarket",
  "34": "Cites",
  "35": "IsCitedBy",
  "37": "IsSignedVersionOf",
  "38": "HasSignedVersion",
  "39": "HasRelatedStudentMaterial",
  "40": "HasRelatedTeacherMaterial",
  "41": "SomeContentSharedWith",
  "42": "IsLaterEditionOfFirstEdition",
  "43": "AdaptedFrom",
  "44": "AdaptedAs",
};

export enum ProductRelationEnum {
  Unspecified = "Unspecified",
  Includes = "Includes",
  IsPartOf = "IsPartOf",
  Replaces = "Replaces",
  HasCompanionProduct = "HasCompanionProduct",
  ReplacedBy = "ReplacedBy",
  AlternativeFormat = "AlternativeFormat",
  HasAncillaryProduct = "HasAncillaryProduct",
  IsAncillaryTo = "IsAncillaryTo",
  IsRemainderedAs = "IsRemainderedAs",
  IsRemainderOf = "IsRemainderOf",
  IsOtherLanguageVersionOf = "IsOtherLanguageVersionOf",
  PublisherSSuggestedAlternative = "PublisherSSuggestedAlternative",
  EpublicationBasedOnPrintProduct = "EpublicationBasedOnPrintProduct",
  PodReplacementFor = "PodReplacementFor",
  ReplacedByPod = "ReplacedByPod",
  IsSpecialEditionOf = "IsSpecialEditionOf",
  HasSpecialEdition = "HasSpecialEdition",
  IsPreboundEditionOf = "IsPreboundEditionOf",
  IsOriginalOfPreboundEdition = "IsOriginalOfPreboundEdition",
  ProductBySameAuthor = "ProductBySameAuthor",
  SimilarProduct = "SimilarProduct",
  IsFacsimileOf = "IsFacsimileOf",
  IsOriginalOfFacsimile = "IsOriginalOfFacsimile",
  IsLicenseFor = "IsLicenseFor",
  ElectronicVersionAvailableAs = "ElectronicVersionAvailableAs",
  EnhancedVersionAvailableAs = "EnhancedVersionAvailableAs",
  BasicVersionAvailableAs = "BasicVersionAvailableAs",
  ProductInSameCollection = "ProductInSameCollection",
  HasAlternativeInADifferentMarketSector = "HasAlternativeInADifferentMarketSector",
  HasEquivalentIntendedForADifferentMarket = "HasEquivalentIntendedForADifferentMarket",
  HasAlternativeIntendedForDifferentMarket = "HasAlternativeIntendedForDifferentMarket",
  Cites = "Cites",
  IsCitedBy = "IsCitedBy",
  IsSignedVersionOf = "IsSignedVersionOf",
  HasSignedVersion = "HasSignedVersion",
  HasRelatedStudentMaterial = "HasRelatedStudentMaterial",
  HasRelatedTeacherMaterial = "HasRelatedTeacherMaterial",
  SomeContentSharedWith = "SomeContentSharedWith",
  IsLaterEditionOfFirstEdition = "IsLaterEditionOfFirstEdition",
  AdaptedFrom = "AdaptedFrom",
  AdaptedAs = "AdaptedAs"
}
  