// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const ProductFormFeatureType = {
  "01": "ColorOfCover",
  "02": "ColorOfPageEdge",
  "03": "TextFont",
  "04": "SpecialCoverMaterial",
  "05": "DvdRegion",
  "06": "OperatingSystemRequirements",
  "07": "OtherSystemRequirements",
  "08": "PointAndListenDeviceCompatibility",
  "09": "EPublicationAccessibilityDetail",
  "10": "EPublicationFormatVersion",
  "12": "UsCpsiaOrOtherInternationalHazardWarning",
  "13": "EuToySafetyHazardWarning",
  "14": "IataDangerousGoodsWarning",
  "15": "EPublicationFormatVersionCode",
  "16": "EPublicationFormatValidatorVersion",
  "17": "PointAndWatchDeviceAppCompatibility",
  "18": "EPublicationAuthenticationAndAccessControl",
  "19": "BatteryType",
  "20": "BatteryCapacity",
  "21": "DangerousGoods",
  "22": "GamePieces",
  "23": "GamePlayers",
  "24": "GamePlayTime",
  "25": "PersonalDataRequirements",
  "30": "NotFscOrPefcCertified",
  "31": "FscCertifiedPure",
  "32": "FscCertifiedMixedSources",
  "33": "FscCertifiedRecycled",
  "34": "PefcCertified",
  "35": "PefcRecycled",
  "36": "FscOrPefcCertifiedPreAndPostConsumerWastePcwPercentage",
  "37": "ClaimedPreAndPostConsumerWastePcwPercentage",
  "40": "PaperProducedByGreenTechnology",
};

export enum ProductFormFeatureTypeEnum {
  ColorOfCover = "ColorOfCover",
  ColorOfPageEdge = "ColorOfPageEdge",
  TextFont = "TextFont",
  SpecialCoverMaterial = "SpecialCoverMaterial",
  DvdRegion = "DvdRegion",
  OperatingSystemRequirements = "OperatingSystemRequirements",
  OtherSystemRequirements = "OtherSystemRequirements",
  PointAndListenDeviceCompatibility = "PointAndListenDeviceCompatibility",
  EPublicationAccessibilityDetail = "EPublicationAccessibilityDetail",
  EPublicationFormatVersion = "EPublicationFormatVersion",
  UsCpsiaOrOtherInternationalHazardWarning = "UsCpsiaOrOtherInternationalHazardWarning",
  EuToySafetyHazardWarning = "EuToySafetyHazardWarning",
  IataDangerousGoodsWarning = "IataDangerousGoodsWarning",
  EPublicationFormatVersionCode = "EPublicationFormatVersionCode",
  EPublicationFormatValidatorVersion = "EPublicationFormatValidatorVersion",
  PointAndWatchDeviceAppCompatibility = "PointAndWatchDeviceAppCompatibility",
  EPublicationAuthenticationAndAccessControl = "EPublicationAuthenticationAndAccessControl",
  BatteryType = "BatteryType",
  BatteryCapacity = "BatteryCapacity",
  DangerousGoods = "DangerousGoods",
  GamePieces = "GamePieces",
  GamePlayers = "GamePlayers",
  GamePlayTime = "GamePlayTime",
  PersonalDataRequirements = "PersonalDataRequirements",
  NotFscOrPefcCertified = "NotFscOrPefcCertified",
  FscCertifiedPure = "FscCertifiedPure",
  FscCertifiedMixedSources = "FscCertifiedMixedSources",
  FscCertifiedRecycled = "FscCertifiedRecycled",
  PefcCertified = "PefcCertified",
  PefcRecycled = "PefcRecycled",
  FscOrPefcCertifiedPreAndPostConsumerWastePcwPercentage = "FscOrPefcCertifiedPreAndPostConsumerWastePcwPercentage",
  ClaimedPreAndPostConsumerWastePcwPercentage = "ClaimedPreAndPostConsumerWastePcwPercentage",
  PaperProducedByGreenTechnology = "PaperProducedByGreenTechnology"
}
  