export const ProductForm = {
  "00": "Undefined",
  "AA": "Audio",
  "AB": "AudioCassette",
  "AC": "CdAudio",
  "AD": "Dat",
  "AE": "AudioDisc",
  "AF": "AudioTape",
  "AG": "MiniDisc",
  "AH": "CdExtra",
  "AI": "DvdAudio",
  "AJ": "DownloadableAudioFile",
  "AK": "PreRecordedDigitalAudioPlayer",
  "AL": "PreRecordedSdCard",
  "AM": "Lp",
  "AN": "DownloadableAndOnlineAudioFile",
  "AO": "OnlineAudioFile",
  "AZ": "OtherAudioFormat",
  "BA": "Book",
  "BB": "Hardback",
  "BC": "PaperbackSoftback",
  "BD": "LooseLeaf",
  "BE": "SpiralBound",
  "BF": "Pamphlet",
  "BG": "LeatherFineBinding",
  "BH": "BoardBook",
  "BI": "RagBook",
  "BJ": "BathBook",
  "BK": "NoveltyBook",
  "BL": "SlideBound",
  "BM": "BigBook",
  "BN": "PartWorkFascCulo",
  "BO": "FoldOutBookOrChart",
  "BP": "FoamBook",
  "BZ": "OtherBookFormat",
  "CA": "SheetMap",
  "CB": "SheetMapFolded",
  "CC": "SheetMapFlat",
  "CD": "SheetMapRolled",
  "CE": "Globe",
  "CZ": "OtherCartographic",
  "DA": "DigitalOnPhysicalCarrier",
  "DB": "CdRom",
  "DC": "CdI",
  "DE": "GameCartridge",
  "DF": "Diskette",
  "DI": "DvdRom",
  "DJ": "SecureDigitalSdMemoryCard",
  "DK": "CompactFlashMemoryCard",
  "DL": "MemoryStickMemoryCard",
  "DM": "UsbFlashDrive",
  "DN": "DoubleSidedCdDvd",
  "DO": "BrRom",
  "DZ": "OtherDigitalCarrier",
  "EA": "DigitalDeliveredElectronically",
  "EB": "DigitalDownloadAndOnline",
  "EC": "DigitalOnline",
  "ED": "DigitalDownload",
  "FA": "FilmOrTransparency",
  "FC": "Slides",
  "FD": "OhpTransparencies",
  "FE": "Filmstrip",
  "FF": "Film",
  "FZ": "OtherFilmOrTransparencyFormat",
  "LA": "DigitalProductLicense",
  "LB": "DigitalProductLicenseKey",
  "LC": "DigitalProductLicenseCode",
  "MA": "Microform",
  "MB": "Microfiche",
  "MC": "Microfilm",
  "MZ": "OtherMicroform",
  "PA": "MiscellaneousPrint",
  "PB": "AddressBook",
  "PC": "Calendar",
  "PD": "Cards",
  "PE": "Copymasters",
  "PF": "DiaryOrJournal",
  "PG": "Frieze",
  "PH": "Kit",
  "PI": "SheetMusic",
  "PJ": "PostcardBookOrPack",
  "PK": "Poster",
  "PL": "RecordBook",
  "PM": "WalletOrFolder",
  "PN": "PicturesOrPhotographs",
  "PO": "Wallchart",
  "PP": "Stickers",
  "PQ": "PlateLMina",
  "PR": "NotebookBlankBook",
  "PS": "Organizer",
  "PT": "Bookmark",
  "PU": "Leaflet",
  "PV": "BookPlates",
  "PZ": "OtherPrintedItem",
  "SA": "MultipleComponentRetailProduct",
  "SB": "MultipleComponentRetailProductBoxed",
  "SC": "MultipleComponentRetailProductSlipCased",
  "SD": "MultipleComponentRetailProductShrinkWrapped",
  "SE": "MultipleComponentRetailProductLoose",
  "SF": "MultipleComponentRetailProductPartSEnclosed",
  "VA": "Video",
  "VF": "Videodisc",
  "VI": "DvdVideo",
  "VJ": "VhsVideo",
  "VK": "BetamaxVideo",
  "VL": "Vcd",
  "VM": "Svcd",
  "VN": "HdDvd",
  "VO": "BluRay",
  "VP": "UmdVideo",
  "VQ": "Cbhd",
  "VZ": "OtherVideoFormat",
  "XA": "TradeOnlyMaterial",
  "XB": "DumpbinEmpty",
  "XC": "DumpbinFilled",
  "XD": "CounterpackEmpty",
  "XE": "CounterpackFilled",
  "XF": "PosterPromotional",
  "XG": "ShelfStrip",
  "XH": "WindowPiece",
  "XI": "Streamer",
  "XJ": "SpinnerEmpty",
  "XK": "LargeBookDisplay",
  "XL": "ShrinkWrappedPack",
  "XM": "BoxedPack",
  "XN": "PackOuterPackagingUnspecified",
  "XO": "SpinnerFilled",
  "XY": "OtherPointOfSaleIncludingRetailProduct",
  "XZ": "OtherPointOfSale",
  "ZA": "GeneralMerchandise",
  "ZB": "DollOrFigure",
  "ZC": "SoftToy",
  "ZD": "Toy",
  "ZE": "Game",
  "ZF": "TShirt",
  "ZG": "EBookReader",
  "ZH": "TabletComputer",
  "ZI": "AudiobookPlayer",
  "ZJ": "Jigsaw",
  "ZK": "Mug",
  "ZL": "ToteBag",
  "ZM": "Tableware",
  "ZN": "Umbrella",
  "ZO": "PaintsCrayonsPencils",
  "ZX": "OtherToyGameAccessories",
  "ZY": "OtherApparel",
  "ZZ": "OtherMerchandise",
};

export enum ProductFormEnum {
  Undefined,
  Audio,
  AudioCassette,
  CdAudio,
  Dat,
  AudioDisc,
  AudioTape,
  MiniDisc,
  CdExtra,
  DvdAudio,
  DownloadableAudioFile,
  PreRecordedDigitalAudioPlayer,
  PreRecordedSdCard,
  Lp,
  DownloadableAndOnlineAudioFile,
  OnlineAudioFile,
  OtherAudioFormat,
  Book,
  Hardback,
  PaperbackSoftback,
  LooseLeaf,
  SpiralBound,
  Pamphlet,
  LeatherFineBinding,
  BoardBook,
  RagBook,
  BathBook,
  NoveltyBook,
  SlideBound,
  BigBook,
  PartWorkFascCulo,
  FoldOutBookOrChart,
  FoamBook,
  OtherBookFormat,
  SheetMap,
  SheetMapFolded,
  SheetMapFlat,
  SheetMapRolled,
  Globe,
  OtherCartographic,
  DigitalOnPhysicalCarrier,
  CdRom,
  CdI,
  GameCartridge,
  Diskette,
  DvdRom,
  SecureDigitalSdMemoryCard,
  CompactFlashMemoryCard,
  MemoryStickMemoryCard,
  UsbFlashDrive,
  DoubleSidedCdDvd,
  BrRom,
  OtherDigitalCarrier,
  DigitalDeliveredElectronically,
  DigitalDownloadAndOnline,
  DigitalOnline,
  DigitalDownload,
  FilmOrTransparency,
  Slides,
  OhpTransparencies,
  Filmstrip,
  Film,
  OtherFilmOrTransparencyFormat,
  DigitalProductLicense,
  DigitalProductLicenseKey,
  DigitalProductLicenseCode,
  Microform,
  Microfiche,
  Microfilm,
  OtherMicroform,
  MiscellaneousPrint,
  AddressBook,
  Calendar,
  Cards,
  Copymasters,
  DiaryOrJournal,
  Frieze,
  Kit,
  SheetMusic,
  PostcardBookOrPack,
  Poster,
  RecordBook,
  WalletOrFolder,
  PicturesOrPhotographs,
  Wallchart,
  Stickers,
  PlateLMina,
  NotebookBlankBook,
  Organizer,
  Bookmark,
  Leaflet,
  BookPlates,
  OtherPrintedItem,
  MultipleComponentRetailProduct,
  MultipleComponentRetailProductBoxed,
  MultipleComponentRetailProductSlipCased,
  MultipleComponentRetailProductShrinkWrapped,
  MultipleComponentRetailProductLoose,
  MultipleComponentRetailProductPartSEnclosed,
  Video,
  Videodisc,
  DvdVideo,
  VhsVideo,
  BetamaxVideo,
  Vcd,
  Svcd,
  HdDvd,
  BluRay,
  UmdVideo,
  Cbhd,
  OtherVideoFormat,
  TradeOnlyMaterial,
  DumpbinEmpty,
  DumpbinFilled,
  CounterpackEmpty,
  CounterpackFilled,
  PosterPromotional,
  ShelfStrip,
  WindowPiece,
  Streamer,
  SpinnerEmpty,
  LargeBookDisplay,
  ShrinkWrappedPack,
  BoxedPack,
  PackOuterPackagingUnspecified,
  SpinnerFilled,
  OtherPointOfSaleIncludingRetailProduct,
  OtherPointOfSale,
  GeneralMerchandise,
  DollOrFigure,
  SoftToy,
  Toy,
  Game,
  TShirt,
  EBookReader,
  TabletComputer,
  AudiobookPlayer,
  Jigsaw,
  Mug,
  ToteBag,
  Tableware,
  Umbrella,
  PaintsCrayonsPencils,
  OtherToyGameAccessories,
  OtherApparel,
  OtherMerchandise
}
