// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const ProductFormDetail = {
  "A101": "CdStandardAudioFormat",
  "A102": "SacdSuperAudioFormat",
  "A103": "Mp3Format",
  "A104": "WavFormat",
  "A105": "RealAudioFormat",
  "A106": "Wma",
  "A107": "Aac",
  "A108": "OggVorbis",
  "A109": "Audible",
  "A110": "Flac",
  "A111": "Aiff",
  "A112": "Alac",
  "A113": "W3CAudiobookFormat",
  "A201": "Daisy_2FullAudioWithTitleOnlyNoNavigation",
  "A202": "Daisy_2FullAudioWithNavigationNoText",
  "A203": "Daisy_2FullAudioWithNavigationAndPartialText",
  "A204": "Daisy_2FullAudioWithNavigationAndFullText",
  "A205": "Daisy_2FullTextWithNavigationAndPartialAudio",
  "A206": "Daisy_2FullTextWithNavigationAndNoAudio",
  "A207": "Daisy_3FullAudioWithTitleOnlyNoNavigation",
  "A208": "Daisy_3FullAudioWithNavigationNoText",
  "A209": "Daisy_3FullAudioWithNavigationAndPartialText",
  "A210": "Daisy_3FullAudioWithNavigationAndFullText",
  "A211": "Daisy_3FullTextWithNavigationAndPartialAudio",
  "A212": "Daisy_3FullTextWithNavigationAndNoAudio",
  "A301": "StandaloneAudio",
  "A302": "ReadalongAudio",
  "A303": "PlayalongAudio",
  "A304": "SpeakalongAudio",
  "A305": "SynchronisedAudio",
  "A310": "SoundEffects",
  "A311": "BackgroundMusic",
  "A410": "Mono",
  "A420": "Stereo",
  "A421": "Stereo_2_1",
  "A441": "Surround_4_1",
  "A451": "Surround_5_1",
  "B101": "MassMarketRackPaperback",
  "B102": "TradePaperbackUs",
  "B103": "DigestFormatPaperback",
  "B104": "AFormatPaperback",
  "B105": "BFormatPaperback",
  "B106": "TradePaperbackUk",
  "B107": "TallRackPaperbackUs",
  "B108": "A5SizeTankobon",
  "B109": "JisB5SizeTankobon",
  "B110": "JisB6SizeTankobon",
  "B111": "A6SizeBunko",
  "B112": "B40DoriShinsho",
  "B113": "PocketSwedenNorwayFrance",
  "B114": "StorpocketSweden",
  "B115": "KartonnageSweden",
  "B116": "FlexbandSweden",
  "B117": "MookBookazine",
  "B118": "Dwarsligger",
  "B119": "46Size",
  "B120": "46HenkeiSize",
  "B121": "A4",
  "B122": "A4HenkeiSize",
  "B123": "A5HenkeiSize",
  "B124": "B5HenkeiSize",
  "B125": "B6HenkeiSize",
  "B126": "AbSize",
  "B127": "JisB7Size",
  "B128": "KikuSize",
  "B129": "KikuHenkeiSize",
  "B130": "JisB4Size",
  "B131": "PaperbackDe",
  "B132": "LibroDeBolsillo",
  "B133": "PocketSized",
  "B134": "A5",
  "B135": "MassMarketMaxPaperback",
  "B201": "ColoringJoinTheDotBook",
  "B202": "LiftTheFlapBook",
  "B204": "MiniatureBook",
  "B205": "MovingPictureFlickerBook",
  "B206": "PopUpBook",
  "B207": "ScentedSmellyBook",
  "B208": "SoundStoryNoisyBook",
  "B209": "StickerBook",
  "B210": "TouchAndFeelBook",
  "B212": "DieCutBook",
  "B213": "BookAsToy",
  "B214": "SoftToTouchBook",
  "B215": "FuzzyFeltBook",
  "B216": "PressOutPuzzlePieces",
  "B221": "PictureBook",
  "B222": "CarouselBook",
  "B223": "PullTheTabBook",
  "B301": "LooseLeafOrPartworkSheetsPartsAndBinderWallet",
  "B302": "LooseLeafOrPartworkBinderWalletOnly",
  "B303": "LooseLeafOrPartworkSheetsPartsOnly",
  "B304": "Sewn",
  "B305": "UnsewnAdhesiveBound",
  "B306": "LibraryBinding",
  "B307": "ReinforcedBinding",
  "B308": "HalfBound",
  "B309": "QuarterBound",
  "B310": "SaddleSewn",
  "B311": "CombBound",
  "B312": "WireO",
  "B313": "ConcealedWire",
  "B314": "CoiledWireBound",
  "B315": "TradeBinding",
  "B316": "SwissBinding",
  "B317": "NotchedBinding",
  "B400": "SelfCovered",
  "B401": "ClothOverBoards",
  "B402": "PaperOverBoards",
  "B403": "LeatherReal",
  "B404": "LeatherImitation",
  "B405": "LeatherBonded",
  "B406": "Vellum",
  "B409": "Cloth",
  "B410": "ImitationCloth",
  "B411": "Velvet",
  "B412": "FlexiblePlasticVinylCover",
  "B413": "PlasticCovered",
  "B414": "VinylCovered",
  "B415": "LaminatedCover",
  "B416": "CardCover",
  "B417": "DuplexPrintedCover",
  "B501": "WithDustJacket",
  "B502": "WithPrintedDustJacket",
  "B503": "WithTranslucentDustCover",
  "B504": "WithFlaps",
  "B505": "WithThumbIndex",
  "B506": "WithRibbonMarkerS",
  "B507": "WithZipFastener",
  "B508": "WithButtonSnapFastener",
  "B509": "WithLeatherEdgeLining",
  "B510": "RoughFront",
  "B511": "Foldout",
  "B512": "WideMargin",
  "B513": "WithFasteningStrap",
  "B514": "WithPerforatedPages",
  "B515": "AcidFreePaper",
  "B516": "ArchivalPaper",
  "B517": "WithElasticatedStrap",
  "B518": "WithSerializedAuthenticityToken",
  "B519": "WithDustJacketPoster",
  "B601": "TurnAroundBook",
  "B602": "UnflippedMangaFormat",
  "B603": "BackToBackBook",
  "B610": "Syllabification",
  "B701": "UkUncontractedBraille",
  "B702": "UkContractedBraille",
  "B703": "UsBraille",
  "B704": "UsUncontractedBraille",
  "B705": "UsContractedBraille",
  "B706": "UnifiedEnglishBraille",
  "B707": "Moon",
  "B708": "UnifiedEnglishUncontractedBraille",
  "B709": "UnifiedEnglishContractedBraille",
  "D101": "RealVideoFormat",
  "D102": "QuicktimeFormat",
  "D103": "AviFormat",
  "D104": "WindowsMediaVideoFormat",
  "D105": "Mpeg_4",
  "D201": "MsDos",
  "D202": "Windows",
  "D203": "Macintosh",
  "D204": "UnixLinux",
  "D205": "OtherOperatingSystemS",
  "D206": "PalmOs",
  "D207": "WindowsMobile",
  "D301": "MicrosoftXBox",
  "D302": "NintendoGameboyColor",
  "D303": "NintendoGameboyAdvanced",
  "D304": "NintendoGameboy",
  "D305": "NintendoGamecube",
  "D306": "Nintendo_64",
  "D307": "SegaDreamcast",
  "D308": "SegaGenesisMegadrive",
  "D309": "SegaSaturn",
  "D310": "SonyPlayStation_1",
  "D311": "SonyPlayStation_2",
  "D312": "NintendoDualScreen",
  "D313": "SonyPlayStation_3",
  "D314": "MicrosoftXbox_360",
  "D315": "NintendoWii",
  "D316": "SonyPlayStationPortablePsp",
  "D317": "SonyPlayStation_3",
  "D318": "SonyPlayStation_4",
  "D319": "SonyPlayStationVita",
  "D320": "MicrosoftXboxOne",
  "D321": "NintendoSwitch",
  "D322": "NintendoWiiU",
  "D323": "SonyPlayStation_5",
  "D324": "MicrosoftXboxSeriesXS",
  "E100": "Other",
  "E101": "Epub",
  "E102": "Oeb",
  "E103": "Doc",
  "E104": "Docx",
  "E105": "Html",
  "E106": "Odf",
  "E107": "Pdf",
  "E108": "PdfA",
  "E109": "Rtf",
  "E110": "Sgml",
  "E111": "Tcr",
  "E112": "Txt",
  "E113": "Xhtml",
  "E114": "ZTxt",
  "E115": "Xps",
  "E116": "AmazonKindle",
  "E117": "BBeB",
  "E118": "DxReader",
  "E119": "Ebl",
  "E120": "Ebrary",
  "E121": "EReader",
  "E122": "Exebook",
  "E123": "FranklinEBookman",
  "E124": "GemstarRocketbook",
  "E125": "ISilo",
  "E126": "MicrosoftReader",
  "E127": "Mobipocket",
  "E128": "MyiLibrary",
  "E129": "NetLibrary",
  "E130": "Plucker",
  "E131": "VitalBook",
  "E132": "Vook",
  "E133": "GoogleEdition",
  "E134": "BookAppForIOs",
  "E135": "BookAppForAndroid",
  "E136": "BookAppForOtherOperatingSystem",
  "E139": "Ceb",
  "E140": "Cebx",
  "E141": "IBook",
  "E142": "EPib",
  "E143": "Scorm",
  "E144": "Ebp",
  "E145": "PagePerfect",
  "E146": "Brf",
  "E147": "Erudit",
  "E148": "AmazonKindlePrintReplica",
  "E149": "ComicBookArchive",
  "E200": "Reflowable",
  "E201": "FixedFormat",
  "E202": "ReadableOffline",
  "E203": "RequiresNetworkConnection",
  "E204": "ContentRemoved",
  "E210": "Landscape",
  "E211": "Portrait",
  "E221": "5_4",
  "E222": "4_3",
  "E223": "3_2",
  "E224": "16_10",
  "E225": "16_9",
  "L101": "Laminated",
  "P101": "DeskCalendarOrDiary",
  "P102": "MiniCalendarOrPocketDiary",
  "P103": "EngagementCalendarOrAppointmentDiary",
  "P104": "DayByDayCalendar",
  "P105": "PosterCalendar",
  "P106": "WallCalendar",
  "P107": "PerpetualCalendarOrDiary",
  "P108": "AdventCalendar",
  "P109": "BookmarkCalendar",
  "P110": "StudentOrAcademicCalendarOrDiary",
  "P111": "ProjectCalendar",
  "P112": "AlmanacCalendar",
  "P113": "OtherCalendarDiaryOrOrganiser",
  "P114": "OtherCalendarOrOrganiserProduct",
  "P115": "FamilyPlanner",
  "P116": "PostcardCalendar",
  "P120": "PictureStoryCards",
  "P121": "FlashCards",
  "P122": "ReferenceCards",
  "P123": "RecreationCards",
  "P124": "Postcards",
  "P125": "GreetingCards",
  "P126": "GiftCards",
  "P201": "HardbackStationery",
  "P202": "PaperbackSoftbackStationery",
  "P203": "SpiralBoundStationery",
  "P204": "LeatherFineBindingStationery",
  "P301": "WithHangingStrips",
  "V201": "Pal",
  "V202": "Ntsc",
  "V203": "Secam",
  "V205": "Hd",
  "V206": "Uhd",
  "V207": "3DVideo",
  "V220": "HomeUse",
  "V221": "ClassroomUse",
  "Z101": "Wooden",
  "Z102": "Plastic",
  "Z103": "Board",
  "Z111": "3DPuzzle",
  "Z112": "NoisyKitPuzzleToy",
  "Z113": "Puppet",
  "Z121": "ExtraLargePieces",
};

export enum ProductFormDetailEnum {
  CdStandardAudioFormat = "CdStandardAudioFormat",
  SacdSuperAudioFormat = "SacdSuperAudioFormat",
  Mp3Format = "Mp3Format",
  WavFormat = "WavFormat",
  RealAudioFormat = "RealAudioFormat",
  Wma = "Wma",
  Aac = "Aac",
  OggVorbis = "OggVorbis",
  Audible = "Audible",
  Flac = "Flac",
  Aiff = "Aiff",
  Alac = "Alac",
  W3CAudiobookFormat = "W3CAudiobookFormat",
  Daisy_2FullAudioWithTitleOnlyNoNavigation = "Daisy_2FullAudioWithTitleOnlyNoNavigation",
  Daisy_2FullAudioWithNavigationNoText = "Daisy_2FullAudioWithNavigationNoText",
  Daisy_2FullAudioWithNavigationAndPartialText = "Daisy_2FullAudioWithNavigationAndPartialText",
  Daisy_2FullAudioWithNavigationAndFullText = "Daisy_2FullAudioWithNavigationAndFullText",
  Daisy_2FullTextWithNavigationAndPartialAudio = "Daisy_2FullTextWithNavigationAndPartialAudio",
  Daisy_2FullTextWithNavigationAndNoAudio = "Daisy_2FullTextWithNavigationAndNoAudio",
  Daisy_3FullAudioWithTitleOnlyNoNavigation = "Daisy_3FullAudioWithTitleOnlyNoNavigation",
  Daisy_3FullAudioWithNavigationNoText = "Daisy_3FullAudioWithNavigationNoText",
  Daisy_3FullAudioWithNavigationAndPartialText = "Daisy_3FullAudioWithNavigationAndPartialText",
  Daisy_3FullAudioWithNavigationAndFullText = "Daisy_3FullAudioWithNavigationAndFullText",
  Daisy_3FullTextWithNavigationAndPartialAudio = "Daisy_3FullTextWithNavigationAndPartialAudio",
  Daisy_3FullTextWithNavigationAndNoAudio = "Daisy_3FullTextWithNavigationAndNoAudio",
  StandaloneAudio = "StandaloneAudio",
  ReadalongAudio = "ReadalongAudio",
  PlayalongAudio = "PlayalongAudio",
  SpeakalongAudio = "SpeakalongAudio",
  SynchronisedAudio = "SynchronisedAudio",
  SoundEffects = "SoundEffects",
  BackgroundMusic = "BackgroundMusic",
  Mono = "Mono",
  Stereo = "Stereo",
  Stereo_2_1 = "Stereo_2_1",
  Surround_4_1 = "Surround_4_1",
  Surround_5_1 = "Surround_5_1",
  MassMarketRackPaperback = "MassMarketRackPaperback",
  TradePaperbackUs = "TradePaperbackUs",
  DigestFormatPaperback = "DigestFormatPaperback",
  AFormatPaperback = "AFormatPaperback",
  BFormatPaperback = "BFormatPaperback",
  TradePaperbackUk = "TradePaperbackUk",
  TallRackPaperbackUs = "TallRackPaperbackUs",
  A5SizeTankobon = "A5SizeTankobon",
  JisB5SizeTankobon = "JisB5SizeTankobon",
  JisB6SizeTankobon = "JisB6SizeTankobon",
  A6SizeBunko = "A6SizeBunko",
  B40DoriShinsho = "B40DoriShinsho",
  PocketSwedenNorwayFrance = "PocketSwedenNorwayFrance",
  StorpocketSweden = "StorpocketSweden",
  KartonnageSweden = "KartonnageSweden",
  FlexbandSweden = "FlexbandSweden",
  MookBookazine = "MookBookazine",
  Dwarsligger = "Dwarsligger",
  "46Size" = "46Size",
  "46HenkeiSize" = "46HenkeiSize",
  A4 = "A4",
  A4HenkeiSize = "A4HenkeiSize",
  A5HenkeiSize = "A5HenkeiSize",
  B5HenkeiSize = "B5HenkeiSize",
  B6HenkeiSize = "B6HenkeiSize",
  AbSize = "AbSize",
  JisB7Size = "JisB7Size",
  KikuSize = "KikuSize",
  KikuHenkeiSize = "KikuHenkeiSize",
  JisB4Size = "JisB4Size",
  PaperbackDe = "PaperbackDe",
  LibroDeBolsillo = "LibroDeBolsillo",
  PocketSized = "PocketSized",
  A5 = "A5",
  MassMarketMaxPaperback = "MassMarketMaxPaperback",
  ColoringJoinTheDotBook = "ColoringJoinTheDotBook",
  LiftTheFlapBook = "LiftTheFlapBook",
  MiniatureBook = "MiniatureBook",
  MovingPictureFlickerBook = "MovingPictureFlickerBook",
  PopUpBook = "PopUpBook",
  ScentedSmellyBook = "ScentedSmellyBook",
  SoundStoryNoisyBook = "SoundStoryNoisyBook",
  StickerBook = "StickerBook",
  TouchAndFeelBook = "TouchAndFeelBook",
  DieCutBook = "DieCutBook",
  BookAsToy = "BookAsToy",
  SoftToTouchBook = "SoftToTouchBook",
  FuzzyFeltBook = "FuzzyFeltBook",
  PressOutPuzzlePieces = "PressOutPuzzlePieces",
  PictureBook = "PictureBook",
  CarouselBook = "CarouselBook",
  PullTheTabBook = "PullTheTabBook",
  LooseLeafOrPartworkSheetsPartsAndBinderWallet = "LooseLeafOrPartworkSheetsPartsAndBinderWallet",
  LooseLeafOrPartworkBinderWalletOnly = "LooseLeafOrPartworkBinderWalletOnly",
  LooseLeafOrPartworkSheetsPartsOnly = "LooseLeafOrPartworkSheetsPartsOnly",
  Sewn = "Sewn",
  UnsewnAdhesiveBound = "UnsewnAdhesiveBound",
  LibraryBinding = "LibraryBinding",
  ReinforcedBinding = "ReinforcedBinding",
  HalfBound = "HalfBound",
  QuarterBound = "QuarterBound",
  SaddleSewn = "SaddleSewn",
  CombBound = "CombBound",
  WireO = "WireO",
  ConcealedWire = "ConcealedWire",
  CoiledWireBound = "CoiledWireBound",
  TradeBinding = "TradeBinding",
  SwissBinding = "SwissBinding",
  NotchedBinding = "NotchedBinding",
  SelfCovered = "SelfCovered",
  ClothOverBoards = "ClothOverBoards",
  PaperOverBoards = "PaperOverBoards",
  LeatherReal = "LeatherReal",
  LeatherImitation = "LeatherImitation",
  LeatherBonded = "LeatherBonded",
  Vellum = "Vellum",
  Cloth = "Cloth",
  ImitationCloth = "ImitationCloth",
  Velvet = "Velvet",
  FlexiblePlasticVinylCover = "FlexiblePlasticVinylCover",
  PlasticCovered = "PlasticCovered",
  VinylCovered = "VinylCovered",
  LaminatedCover = "LaminatedCover",
  CardCover = "CardCover",
  DuplexPrintedCover = "DuplexPrintedCover",
  WithDustJacket = "WithDustJacket",
  WithPrintedDustJacket = "WithPrintedDustJacket",
  WithTranslucentDustCover = "WithTranslucentDustCover",
  WithFlaps = "WithFlaps",
  WithThumbIndex = "WithThumbIndex",
  WithRibbonMarkerS = "WithRibbonMarkerS",
  WithZipFastener = "WithZipFastener",
  WithButtonSnapFastener = "WithButtonSnapFastener",
  WithLeatherEdgeLining = "WithLeatherEdgeLining",
  RoughFront = "RoughFront",
  Foldout = "Foldout",
  WideMargin = "WideMargin",
  WithFasteningStrap = "WithFasteningStrap",
  WithPerforatedPages = "WithPerforatedPages",
  AcidFreePaper = "AcidFreePaper",
  ArchivalPaper = "ArchivalPaper",
  WithElasticatedStrap = "WithElasticatedStrap",
  WithSerializedAuthenticityToken = "WithSerializedAuthenticityToken",
  WithDustJacketPoster = "WithDustJacketPoster",
  TurnAroundBook = "TurnAroundBook",
  UnflippedMangaFormat = "UnflippedMangaFormat",
  BackToBackBook = "BackToBackBook",
  Syllabification = "Syllabification",
  UkUncontractedBraille = "UkUncontractedBraille",
  UkContractedBraille = "UkContractedBraille",
  UsBraille = "UsBraille",
  UsUncontractedBraille = "UsUncontractedBraille",
  UsContractedBraille = "UsContractedBraille",
  UnifiedEnglishBraille = "UnifiedEnglishBraille",
  Moon = "Moon",
  UnifiedEnglishUncontractedBraille = "UnifiedEnglishUncontractedBraille",
  UnifiedEnglishContractedBraille = "UnifiedEnglishContractedBraille",
  RealVideoFormat = "RealVideoFormat",
  QuicktimeFormat = "QuicktimeFormat",
  AviFormat = "AviFormat",
  WindowsMediaVideoFormat = "WindowsMediaVideoFormat",
  Mpeg_4 = "Mpeg_4",
  MsDos = "MsDos",
  Windows = "Windows",
  Macintosh = "Macintosh",
  UnixLinux = "UnixLinux",
  OtherOperatingSystemS = "OtherOperatingSystemS",
  PalmOs = "PalmOs",
  WindowsMobile = "WindowsMobile",
  MicrosoftXBox = "MicrosoftXBox",
  NintendoGameboyColor = "NintendoGameboyColor",
  NintendoGameboyAdvanced = "NintendoGameboyAdvanced",
  NintendoGameboy = "NintendoGameboy",
  NintendoGamecube = "NintendoGamecube",
  Nintendo_64 = "Nintendo_64",
  SegaDreamcast = "SegaDreamcast",
  SegaGenesisMegadrive = "SegaGenesisMegadrive",
  SegaSaturn = "SegaSaturn",
  SonyPlayStation_1 = "SonyPlayStation_1",
  SonyPlayStation_2 = "SonyPlayStation_2",
  NintendoDualScreen = "NintendoDualScreen",
  SonyPlayStation_3 = "SonyPlayStation_3",
  MicrosoftXbox_360 = "MicrosoftXbox_360",
  NintendoWii = "NintendoWii",
  SonyPlayStationPortablePsp = "SonyPlayStationPortablePsp",
  SonyPlayStation_4 = "SonyPlayStation_4",
  SonyPlayStationVita = "SonyPlayStationVita",
  MicrosoftXboxOne = "MicrosoftXboxOne",
  NintendoSwitch = "NintendoSwitch",
  NintendoWiiU = "NintendoWiiU",
  SonyPlayStation_5 = "SonyPlayStation_5",
  MicrosoftXboxSeriesXS = "MicrosoftXboxSeriesXS",
  Other = "Other",
  Epub = "Epub",
  Oeb = "Oeb",
  Doc = "Doc",
  Docx = "Docx",
  Html = "Html",
  Odf = "Odf",
  Pdf = "Pdf",
  PdfA = "PdfA",
  Rtf = "Rtf",
  Sgml = "Sgml",
  Tcr = "Tcr",
  Txt = "Txt",
  Xhtml = "Xhtml",
  ZTxt = "ZTxt",
  Xps = "Xps",
  AmazonKindle = "AmazonKindle",
  BBeB = "BBeB",
  DxReader = "DxReader",
  Ebl = "Ebl",
  Ebrary = "Ebrary",
  EReader = "EReader",
  Exebook = "Exebook",
  FranklinEBookman = "FranklinEBookman",
  GemstarRocketbook = "GemstarRocketbook",
  ISilo = "ISilo",
  MicrosoftReader = "MicrosoftReader",
  Mobipocket = "Mobipocket",
  MyiLibrary = "MyiLibrary",
  NetLibrary = "NetLibrary",
  Plucker = "Plucker",
  VitalBook = "VitalBook",
  Vook = "Vook",
  GoogleEdition = "GoogleEdition",
  BookAppForIOs = "BookAppForIOs",
  BookAppForAndroid = "BookAppForAndroid",
  BookAppForOtherOperatingSystem = "BookAppForOtherOperatingSystem",
  Ceb = "Ceb",
  Cebx = "Cebx",
  IBook = "IBook",
  EPib = "EPib",
  Scorm = "Scorm",
  Ebp = "Ebp",
  PagePerfect = "PagePerfect",
  Brf = "Brf",
  Erudit = "Erudit",
  AmazonKindlePrintReplica = "AmazonKindlePrintReplica",
  ComicBookArchive = "ComicBookArchive",
  Reflowable = "Reflowable",
  FixedFormat = "FixedFormat",
  ReadableOffline = "ReadableOffline",
  RequiresNetworkConnection = "RequiresNetworkConnection",
  ContentRemoved = "ContentRemoved",
  Landscape = "Landscape",
  Portrait = "Portrait",
  "5_4" = "5_4",
  "4_3" = "4_3",
  "3_2" = "3_2",
  "16_10" = "16_10",
  "16_9" = "16_9",
  Laminated = "Laminated",
  DeskCalendarOrDiary = "DeskCalendarOrDiary",
  MiniCalendarOrPocketDiary = "MiniCalendarOrPocketDiary",
  EngagementCalendarOrAppointmentDiary = "EngagementCalendarOrAppointmentDiary",
  DayByDayCalendar = "DayByDayCalendar",
  PosterCalendar = "PosterCalendar",
  WallCalendar = "WallCalendar",
  PerpetualCalendarOrDiary = "PerpetualCalendarOrDiary",
  AdventCalendar = "AdventCalendar",
  BookmarkCalendar = "BookmarkCalendar",
  StudentOrAcademicCalendarOrDiary = "StudentOrAcademicCalendarOrDiary",
  ProjectCalendar = "ProjectCalendar",
  AlmanacCalendar = "AlmanacCalendar",
  OtherCalendarDiaryOrOrganiser = "OtherCalendarDiaryOrOrganiser",
  OtherCalendarOrOrganiserProduct = "OtherCalendarOrOrganiserProduct",
  FamilyPlanner = "FamilyPlanner",
  PostcardCalendar = "PostcardCalendar",
  PictureStoryCards = "PictureStoryCards",
  FlashCards = "FlashCards",
  ReferenceCards = "ReferenceCards",
  RecreationCards = "RecreationCards",
  Postcards = "Postcards",
  GreetingCards = "GreetingCards",
  GiftCards = "GiftCards",
  HardbackStationery = "HardbackStationery",
  PaperbackSoftbackStationery = "PaperbackSoftbackStationery",
  SpiralBoundStationery = "SpiralBoundStationery",
  LeatherFineBindingStationery = "LeatherFineBindingStationery",
  WithHangingStrips = "WithHangingStrips",
  Pal = "Pal",
  Ntsc = "Ntsc",
  Secam = "Secam",
  Hd = "Hd",
  Uhd = "Uhd",
  "3DVideo" = "3DVideo",
  HomeUse = "HomeUse",
  ClassroomUse = "ClassroomUse",
  Wooden = "Wooden",
  Plastic = "Plastic",
  Board = "Board",
  "3DPuzzle" = "3DPuzzle",
  NoisyKitPuzzleToy = "NoisyKitPuzzleToy",
  Puppet = "Puppet",
  ExtraLargePieces = "ExtraLargePieces"
}
  