// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const ProductContentType = {
  "10": "TextEyeReadable",
  "15": "ExtensiveLinksBetweenInternalContent",
  "14": "ExtensiveLinksToExternalContent",
  "16": "AdditionalEyeReadableTextNotPartOfMainWork",
  "41": "AdditionalEyeReadableLinksToExternalContent",
  "17": "PromotionalTextForOtherBookProduct",
  "11": "MusicalNotation",
  "07": "StillImagesGraphics",
  "18": "Photographs",
  "19": "FiguresDiagramsChartsGraphs",
  "20": "AdditionalImagesGraphicsNotPartOfMainWork",
  "12": "MapsAndOrOtherCartographicContent",
  "42": "AssessmentMaterial",
  "01": "Audiobook",
  "02": "PerformanceSpokenWord",
  "13": "OtherSpeechContent",
  "03": "MusicRecording",
  "04": "OtherAudio",
  "21": "PartialPerformanceSpokenWord",
  "22": "AdditionalAudioContentNotPartOfMainWork",
  "23": "PromotionalAudioForOtherBookProduct",
  "06": "Video",
  "26": "VideoRecordingOfAReading",
  "27": "PerformanceVisual",
  "24": "AnimatedInteractiveIllustrations",
  "25": "NarrativeAnimation",
  "28": "OtherVideo",
  "29": "PartialPerformanceVideo",
  "30": "AdditionalVideoContentNotPartOfMainWork",
  "31": "PromotionalVideoForOtherBookProduct",
  "05": "GamePuzzle",
  "32": "Contest",
  "08": "Software",
  "09": "Data",
  "33": "DataSetPlusSoftware",
  "34": "BlankPagesOrSpaces",
  "35": "AdvertisingContent",
  "37": "AdvertisingFirstParty",
  "36": "AdvertisingCoupons",
  "38": "AdvertisingThirdPartyDisplay",
  "39": "AdvertisingThirdPartyTextual",
  "40": "Scripting",
  "43": "ScriptedPopUps",
};

export enum ProductContentTypeEnum {
  TextEyeReadable = "TextEyeReadable",
  ExtensiveLinksBetweenInternalContent = "ExtensiveLinksBetweenInternalContent",
  ExtensiveLinksToExternalContent = "ExtensiveLinksToExternalContent",
  AdditionalEyeReadableTextNotPartOfMainWork = "AdditionalEyeReadableTextNotPartOfMainWork",
  AdditionalEyeReadableLinksToExternalContent = "AdditionalEyeReadableLinksToExternalContent",
  PromotionalTextForOtherBookProduct = "PromotionalTextForOtherBookProduct",
  MusicalNotation = "MusicalNotation",
  StillImagesGraphics = "StillImagesGraphics",
  Photographs = "Photographs",
  FiguresDiagramsChartsGraphs = "FiguresDiagramsChartsGraphs",
  AdditionalImagesGraphicsNotPartOfMainWork = "AdditionalImagesGraphicsNotPartOfMainWork",
  MapsAndOrOtherCartographicContent = "MapsAndOrOtherCartographicContent",
  AssessmentMaterial = "AssessmentMaterial",
  Audiobook = "Audiobook",
  PerformanceSpokenWord = "PerformanceSpokenWord",
  OtherSpeechContent = "OtherSpeechContent",
  MusicRecording = "MusicRecording",
  OtherAudio = "OtherAudio",
  PartialPerformanceSpokenWord = "PartialPerformanceSpokenWord",
  AdditionalAudioContentNotPartOfMainWork = "AdditionalAudioContentNotPartOfMainWork",
  PromotionalAudioForOtherBookProduct = "PromotionalAudioForOtherBookProduct",
  Video = "Video",
  VideoRecordingOfAReading = "VideoRecordingOfAReading",
  PerformanceVisual = "PerformanceVisual",
  AnimatedInteractiveIllustrations = "AnimatedInteractiveIllustrations",
  NarrativeAnimation = "NarrativeAnimation",
  OtherVideo = "OtherVideo",
  PartialPerformanceVideo = "PartialPerformanceVideo",
  AdditionalVideoContentNotPartOfMainWork = "AdditionalVideoContentNotPartOfMainWork",
  PromotionalVideoForOtherBookProduct = "PromotionalVideoForOtherBookProduct",
  GamePuzzle = "GamePuzzle",
  Contest = "Contest",
  Software = "Software",
  Data = "Data",
  DataSetPlusSoftware = "DataSetPlusSoftware",
  BlankPagesOrSpaces = "BlankPagesOrSpaces",
  AdvertisingContent = "AdvertisingContent",
  AdvertisingFirstParty = "AdvertisingFirstParty",
  AdvertisingCoupons = "AdvertisingCoupons",
  AdvertisingThirdPartyDisplay = "AdvertisingThirdPartyDisplay",
  AdvertisingThirdPartyTextual = "AdvertisingThirdPartyTextual",
  Scripting = "Scripting",
  ScriptedPopUps = "ScriptedPopUps"
}
  