// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const ProductForm = {
  "00": "Undefined",
  "AA": "Audio",
  "AB": "AudioCassette",
  "AC": "CdAudio",
  "AD": "Dat",
  "AE": "AudioDisc",
  "AF": "AudioTape",
  "AG": "MiniDisc",
  "AH": "CdExtra",
  "AI": "DvdAudio",
  "AJ": "DownloadableAudioFile",
  "AK": "PreRecordedDigitalAudioPlayer",
  "AL": "PreRecordedSdCard",
  "AM": "Lp",
  "AN": "DownloadableAndOnlineAudioFile",
  "AO": "OnlineAudioFile",
  "AZ": "OtherAudioFormat",
  "BA": "Book",
  "BB": "Hardback",
  "BC": "PaperbackSoftback",
  "BD": "LooseLeaf",
  "BE": "SpiralBound",
  "BF": "Pamphlet",
  "BG": "LeatherFineBinding",
  "BH": "BoardBook",
  "BI": "RagBook",
  "BJ": "BathBook",
  "BK": "NoveltyBook",
  "BL": "SlideBound",
  "BM": "BigBook",
  "BN": "PartWorkFascCulo",
  "BO": "FoldOutBookOrChart",
  "BP": "FoamBook",
  "BZ": "OtherBookFormat",
  "CA": "SheetMap",
  "CB": "SheetMapFolded",
  "CC": "SheetMapFlat",
  "CD": "SheetMapRolled",
  "CE": "Globe",
  "CZ": "OtherCartographic",
  "DA": "DigitalOnPhysicalCarrier",
  "DB": "CdRom",
  "DC": "CdI",
  "DE": "GameCartridge",
  "DF": "Diskette",
  "DI": "DvdRom",
  "DJ": "SecureDigitalSdMemoryCard",
  "DK": "CompactFlashMemoryCard",
  "DL": "MemoryStickMemoryCard",
  "DM": "UsbFlashDrive",
  "DN": "DoubleSidedCdDvd",
  "DO": "BrRom",
  "DZ": "OtherDigitalCarrier",
  "EA": "DigitalDeliveredElectronically",
  "EB": "DigitalDownloadAndOnline",
  "EC": "DigitalOnline",
  "ED": "DigitalDownload",
  "FA": "FilmOrTransparency",
  "FC": "Slides",
  "FD": "OhpTransparencies",
  "FE": "Filmstrip",
  "FF": "Film",
  "FZ": "OtherFilmOrTransparencyFormat",
  "LA": "DigitalProductLicense",
  "LB": "DigitalProductLicenseKey",
  "LC": "DigitalProductLicenseCode",
  "MA": "Microform",
  "MB": "Microfiche",
  "MC": "Microfilm",
  "MZ": "OtherMicroform",
  "PA": "MiscellaneousPrint",
  "PB": "AddressBook",
  "PC": "Calendar",
  "PD": "Cards",
  "PE": "Copymasters",
  "PF": "DiaryOrJournal",
  "PG": "Frieze",
  "PH": "Kit",
  "PI": "SheetMusic",
  "PJ": "PostcardBookOrPack",
  "PK": "Poster",
  "PL": "RecordBook",
  "PM": "WalletOrFolder",
  "PN": "PicturesOrPhotographs",
  "PO": "Wallchart",
  "PP": "Stickers",
  "PQ": "PlateLMina",
  "PR": "NotebookBlankBook",
  "PS": "Organizer",
  "PT": "Bookmark",
  "PU": "Leaflet",
  "PV": "BookPlates",
  "PZ": "OtherPrintedItem",
  "SA": "MultipleComponentRetailProduct",
  "SB": "MultipleComponentRetailProductBoxed",
  "SC": "MultipleComponentRetailProductSlipCased",
  "SD": "MultipleComponentRetailProductShrinkWrapped",
  "SE": "MultipleComponentRetailProductLoose",
  "SF": "MultipleComponentRetailProductPartSEnclosed",
  "VA": "Video",
  "VF": "Videodisc",
  "VI": "DvdVideo",
  "VJ": "VhsVideo",
  "VK": "BetamaxVideo",
  "VL": "Vcd",
  "VM": "Svcd",
  "VN": "HdDvd",
  "VO": "BluRay",
  "VP": "UmdVideo",
  "VQ": "Cbhd",
  "VZ": "OtherVideoFormat",
  "XA": "TradeOnlyMaterial",
  "XB": "DumpbinEmpty",
  "XC": "DumpbinFilled",
  "XD": "CounterpackEmpty",
  "XE": "CounterpackFilled",
  "XF": "PosterPromotional",
  "XG": "ShelfStrip",
  "XH": "WindowPiece",
  "XI": "Streamer",
  "XJ": "SpinnerEmpty",
  "XK": "LargeBookDisplay",
  "XL": "ShrinkWrappedPack",
  "XM": "BoxedPack",
  "XN": "PackOuterPackagingUnspecified",
  "XO": "SpinnerFilled",
  "XY": "OtherPointOfSaleIncludingRetailProduct",
  "XZ": "OtherPointOfSale",
  "ZA": "GeneralMerchandise",
  "ZB": "DollOrFigure",
  "ZC": "SoftToy",
  "ZD": "Toy",
  "ZE": "Game",
  "ZF": "TShirt",
  "ZG": "EBookReader",
  "ZH": "TabletComputer",
  "ZI": "AudiobookPlayer",
  "ZJ": "Jigsaw",
  "ZK": "Mug",
  "ZL": "ToteBag",
  "ZM": "Tableware",
  "ZN": "Umbrella",
  "ZO": "PaintsCrayonsPencils",
  "ZX": "OtherToyGameAccessories",
  "ZY": "OtherApparel",
  "ZZ": "OtherMerchandise",
};

export enum ProductFormEnum {
  Undefined = "Undefined",
  Audio = "Audio",
  AudioCassette = "AudioCassette",
  CdAudio = "CdAudio",
  Dat = "Dat",
  AudioDisc = "AudioDisc",
  AudioTape = "AudioTape",
  MiniDisc = "MiniDisc",
  CdExtra = "CdExtra",
  DvdAudio = "DvdAudio",
  DownloadableAudioFile = "DownloadableAudioFile",
  PreRecordedDigitalAudioPlayer = "PreRecordedDigitalAudioPlayer",
  PreRecordedSdCard = "PreRecordedSdCard",
  Lp = "Lp",
  DownloadableAndOnlineAudioFile = "DownloadableAndOnlineAudioFile",
  OnlineAudioFile = "OnlineAudioFile",
  OtherAudioFormat = "OtherAudioFormat",
  Book = "Book",
  Hardback = "Hardback",
  PaperbackSoftback = "PaperbackSoftback",
  LooseLeaf = "LooseLeaf",
  SpiralBound = "SpiralBound",
  Pamphlet = "Pamphlet",
  LeatherFineBinding = "LeatherFineBinding",
  BoardBook = "BoardBook",
  RagBook = "RagBook",
  BathBook = "BathBook",
  NoveltyBook = "NoveltyBook",
  SlideBound = "SlideBound",
  BigBook = "BigBook",
  PartWorkFascCulo = "PartWorkFascCulo",
  FoldOutBookOrChart = "FoldOutBookOrChart",
  FoamBook = "FoamBook",
  OtherBookFormat = "OtherBookFormat",
  SheetMap = "SheetMap",
  SheetMapFolded = "SheetMapFolded",
  SheetMapFlat = "SheetMapFlat",
  SheetMapRolled = "SheetMapRolled",
  Globe = "Globe",
  OtherCartographic = "OtherCartographic",
  DigitalOnPhysicalCarrier = "DigitalOnPhysicalCarrier",
  CdRom = "CdRom",
  CdI = "CdI",
  GameCartridge = "GameCartridge",
  Diskette = "Diskette",
  DvdRom = "DvdRom",
  SecureDigitalSdMemoryCard = "SecureDigitalSdMemoryCard",
  CompactFlashMemoryCard = "CompactFlashMemoryCard",
  MemoryStickMemoryCard = "MemoryStickMemoryCard",
  UsbFlashDrive = "UsbFlashDrive",
  DoubleSidedCdDvd = "DoubleSidedCdDvd",
  BrRom = "BrRom",
  OtherDigitalCarrier = "OtherDigitalCarrier",
  DigitalDeliveredElectronically = "DigitalDeliveredElectronically",
  DigitalDownloadAndOnline = "DigitalDownloadAndOnline",
  DigitalOnline = "DigitalOnline",
  DigitalDownload = "DigitalDownload",
  FilmOrTransparency = "FilmOrTransparency",
  Slides = "Slides",
  OhpTransparencies = "OhpTransparencies",
  Filmstrip = "Filmstrip",
  Film = "Film",
  OtherFilmOrTransparencyFormat = "OtherFilmOrTransparencyFormat",
  DigitalProductLicense = "DigitalProductLicense",
  DigitalProductLicenseKey = "DigitalProductLicenseKey",
  DigitalProductLicenseCode = "DigitalProductLicenseCode",
  Microform = "Microform",
  Microfiche = "Microfiche",
  Microfilm = "Microfilm",
  OtherMicroform = "OtherMicroform",
  MiscellaneousPrint = "MiscellaneousPrint",
  AddressBook = "AddressBook",
  Calendar = "Calendar",
  Cards = "Cards",
  Copymasters = "Copymasters",
  DiaryOrJournal = "DiaryOrJournal",
  Frieze = "Frieze",
  Kit = "Kit",
  SheetMusic = "SheetMusic",
  PostcardBookOrPack = "PostcardBookOrPack",
  Poster = "Poster",
  RecordBook = "RecordBook",
  WalletOrFolder = "WalletOrFolder",
  PicturesOrPhotographs = "PicturesOrPhotographs",
  Wallchart = "Wallchart",
  Stickers = "Stickers",
  PlateLMina = "PlateLMina",
  NotebookBlankBook = "NotebookBlankBook",
  Organizer = "Organizer",
  Bookmark = "Bookmark",
  Leaflet = "Leaflet",
  BookPlates = "BookPlates",
  OtherPrintedItem = "OtherPrintedItem",
  MultipleComponentRetailProduct = "MultipleComponentRetailProduct",
  MultipleComponentRetailProductBoxed = "MultipleComponentRetailProductBoxed",
  MultipleComponentRetailProductSlipCased = "MultipleComponentRetailProductSlipCased",
  MultipleComponentRetailProductShrinkWrapped = "MultipleComponentRetailProductShrinkWrapped",
  MultipleComponentRetailProductLoose = "MultipleComponentRetailProductLoose",
  MultipleComponentRetailProductPartSEnclosed = "MultipleComponentRetailProductPartSEnclosed",
  Video = "Video",
  Videodisc = "Videodisc",
  DvdVideo = "DvdVideo",
  VhsVideo = "VhsVideo",
  BetamaxVideo = "BetamaxVideo",
  Vcd = "Vcd",
  Svcd = "Svcd",
  HdDvd = "HdDvd",
  BluRay = "BluRay",
  UmdVideo = "UmdVideo",
  Cbhd = "Cbhd",
  OtherVideoFormat = "OtherVideoFormat",
  TradeOnlyMaterial = "TradeOnlyMaterial",
  DumpbinEmpty = "DumpbinEmpty",
  DumpbinFilled = "DumpbinFilled",
  CounterpackEmpty = "CounterpackEmpty",
  CounterpackFilled = "CounterpackFilled",
  PosterPromotional = "PosterPromotional",
  ShelfStrip = "ShelfStrip",
  WindowPiece = "WindowPiece",
  Streamer = "Streamer",
  SpinnerEmpty = "SpinnerEmpty",
  LargeBookDisplay = "LargeBookDisplay",
  ShrinkWrappedPack = "ShrinkWrappedPack",
  BoxedPack = "BoxedPack",
  PackOuterPackagingUnspecified = "PackOuterPackagingUnspecified",
  SpinnerFilled = "SpinnerFilled",
  OtherPointOfSaleIncludingRetailProduct = "OtherPointOfSaleIncludingRetailProduct",
  OtherPointOfSale = "OtherPointOfSale",
  GeneralMerchandise = "GeneralMerchandise",
  DollOrFigure = "DollOrFigure",
  SoftToy = "SoftToy",
  Toy = "Toy",
  Game = "Game",
  TShirt = "TShirt",
  EBookReader = "EBookReader",
  TabletComputer = "TabletComputer",
  AudiobookPlayer = "AudiobookPlayer",
  Jigsaw = "Jigsaw",
  Mug = "Mug",
  ToteBag = "ToteBag",
  Tableware = "Tableware",
  Umbrella = "Umbrella",
  PaintsCrayonsPencils = "PaintsCrayonsPencils",
  OtherToyGameAccessories = "OtherToyGameAccessories",
  OtherApparel = "OtherApparel",
  OtherMerchandise = "OtherMerchandise"
}
  