// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const RegionBasedOnIso_3166_2 = {
  "AU-CT": "AustralianCapitalTerritory",
  "AU-NS": "NewSouthWales",
  "AU-NT": "NorthernTerritory",
  "AU-QL": "Queensland",
  "AU-SA": "SouthAustralia",
  "AU-TS": "Tasmania",
  "AU-VI": "Victoria",
  "AU-WA": "WesternAustralia",
  "BE-BRU": "BrusselsCapitalRegion",
  "BE-VLG": "FlemishRegion",
  "BE-WAL": "WalloonRegion",
  "CA-AB": "Alberta",
  "CA-BC": "BritishColumbia",
  "CA-MB": "Manitoba",
  "CA-NB": "NewBrunswick",
  "CA-NL": "NewfoundlandAndLabrador",
  "CA-NS": "NovaScotia",
  "CA-NT": "NorthwestTerritories",
  "CA-NU": "Nunavut",
  "CA-ON": "Ontario",
  "CA-PE": "PrinceEdwardIsland",
  "CA-QC": "Quebec",
  "CA-SK": "Saskatchewan",
  "CA-YT": "YukonTerritory",
  "CN-BJ": "BeijingMunicipality",
  "CN-TJ": "TianjinMunicipality",
  "CN-HE": "HebeiProvince",
  "CN-SX": "ShanxiProvince",
  "CN-NM": "InnerMongoliaAutonomousRegion",
  "CN-LN": "LiaoningProvince",
  "CN-JL": "JilinProvince",
  "CN-HL": "HeilongjiangProvince",
  "CN-SH": "ShanghaiMunicipality",
  "CN-JS": "JiangsuProvince",
  "CN-ZJ": "ZhejiangProvince",
  "CN-AH": "AnhuiProvince",
  "CN-FJ": "FujianProvince",
  "CN-JX": "JiangxiProvince",
  "CN-SD": "ShandongProvince",
  "CN-HA": "HenanProvince",
  "CN-HB": "HubeiProvince",
  "CN-HN": "HunanProvince",
  "CN-GD": "GuangdongProvince",
  "CN-GX": "GuangxiZhuangAutonomousRegion",
  "CN-HI": "HainanProvince",
  "CN-CQ": "ChongqingMunicipality",
  "CN-SC": "SichuanProvince",
  "CN-GZ": "GuizhouProvince",
  "CN-YN": "YunnanProvince",
  "CN-XZ": "TibetAutonomousRegion",
  "CN-SN": "ShaanxiProvince",
  "CN-GS": "GansuProvince",
  "CN-QH": "QinghaiProvince",
  "CN-NX": "NingxiaHuiAutonomousRegion",
  "CN-XJ": "XinjiangUyghurAutonomousRegion",
  "CN-TW": "TaiwanProvince",
  "CN-HK": "HongKongSpecialAdministrativeRegion",
  "CN-MO": "MacauSpecialAdministrativeRegion",
  "CN-11": "BeijingMunicipality",
  "CN-12": "TianjinMunicipality",
  "CN-13": "HebeiProvince",
  "CN-14": "ShanxiProvince",
  "CN-15": "InnerMongoliaAutonomousRegion",
  "CN-21": "LiaoningProvince",
  "CN-22": "JilinProvince",
  "CN-23": "HeilongjiangProvince",
  "CN-31": "ShanghaiMunicipality",
  "CN-32": "JiangsuProvince",
  "CN-33": "ZhejiangProvince",
  "CN-34": "AnhuiProvince",
  "CN-35": "FujianProvince",
  "CN-36": "JiangxiProvince",
  "CN-37": "ShandongProvince",
  "CN-41": "HenanProvince",
  "CN-42": "HubeiProvince",
  "CN-43": "HunanProvince",
  "CN-44": "GuangdongProvince",
  "CN-45": "GuangxiZhuangAutonomousRegion",
  "CN-46": "HainanProvince",
  "CN-50": "ChongqingMunicipality",
  "CN-51": "SichuanProvince",
  "CN-52": "GuizhouProvince",
  "CN-53": "YunnanProvince",
  "CN-54": "TibetAutonomousRegion",
  "CN-61": "ShaanxiProvince",
  "CN-62": "GansuProvince",
  "CN-63": "QinghaiProvince",
  "CN-64": "NingxiaHuiAutonomousRegion",
  "CN-65": "XinjiangUyghurAutonomousRegion",
  "CN-71": "TaiwanProvince",
  "CN-91": "HongKongSpecialAdministrativeRegion",
  "CN-92": "MacauSpecialAdministrativeRegion",
  "ES-CN": "CanaryIslands",
  "FR-H": "Corsica",
  "GB-AIR": "UkAirside",
  "GB-APS": "UkAirports",
  "GB-CHA": "ChannelIslands",
  "GB-ENG": "England",
  "GB-EWS": "EnglandWalesScotland",
  "GB-IOM": "IsleOfMan",
  "GB-NIR": "NorthernIreland",
  "GB-SCT": "Scotland",
  "GB-WLS": "Wales",
  "IE-AIR": "IrelandAirside",
  "IT-AG": "Agrigento",
  "IT-AL": "Alessandria",
  "IT-AN": "Ancona",
  "IT-AO": "Aosta",
  "IT-AR": "Arezzo",
  "IT-AP": "AscoliPiceno",
  "IT-AT": "Asti",
  "IT-AV": "Avellino",
  "IT-BA": "Bari",
  "IT-BT": "BarlettaAndriaTrani",
  "IT-BL": "Belluno",
  "IT-BN": "Benevento",
  "IT-BG": "Bergamo",
  "IT-BI": "Biella",
  "IT-BO": "Bologna",
  "IT-BZ": "Bolzano",
  "IT-BS": "Brescia",
  "IT-BR": "Brindisi",
  "IT-CA": "Cagliari",
  "IT-CL": "Caltanissetta",
  "IT-CB": "Campobasso",
  "IT-CI": "CarboniaIglesias",
  "IT-CE": "Caserta",
  "IT-CT": "Catania",
  "IT-CZ": "Catanzaro",
  "IT-CH": "Chieti",
  "IT-CO": "Como",
  "IT-CS": "Cosenza",
  "IT-CR": "Cremona",
  "IT-KR": "Crotone",
  "IT-CN": "Cuneo",
  "IT-EN": "Enna",
  "IT-FM": "Fermo",
  "IT-FE": "Ferrara",
  "IT-FI": "Firenze",
  "IT-FG": "Foggia",
  "IT-FC": "ForlCesena",
  "IT-FR": "Frosinone",
  "IT-GE": "Genova",
  "IT-GO": "Gorizia",
  "IT-GR": "Grosseto",
  "IT-IM": "Imperia",
  "IT-IS": "Isernia",
  "IT-SP": "LaSpezia",
  "IT-AQ": "LAquila",
  "IT-LT": "Latina",
  "IT-LE": "Lecce",
  "IT-LC": "Lecco",
  "IT-LI": "Livorno",
  "IT-LO": "Lodi",
  "IT-LU": "Lucca",
  "IT-MC": "Macerata",
  "IT-MN": "Mantova",
  "IT-MS": "MassaCarrara",
  "IT-MT": "Matera",
  "IT-VS": "MedioCampidano",
  "IT-ME": "Messina",
  "IT-MI": "Milano",
  "IT-MO": "Modena",
  "IT-MB": "MonzaEBrianza",
  "IT-NA": "Napoli",
  "IT-NO": "Novara",
  "IT-NU": "Nuoro",
  "IT-OG": "Ogliastra",
  "IT-OT": "OlbiaTempio",
  "IT-OR": "Oristano",
  "IT-PD": "Padova",
  "IT-PA": "Palermo",
  "IT-PR": "Parma",
  "IT-PV": "Pavia",
  "IT-PG": "Perugia",
  "IT-PU": "PesaroEUrbino",
  "IT-PE": "Pescara",
  "IT-PC": "Piacenza",
  "IT-PI": "Pisa",
  "IT-PT": "Pistoia",
  "IT-PN": "Pordenone",
  "IT-PZ": "Potenza",
  "IT-PO": "Prato",
  "IT-RG": "Ragusa",
  "IT-RA": "Ravenna",
  "IT-RC": "ReggioCalabria",
  "IT-RE": "ReggioEmilia",
  "IT-RI": "Rieti",
  "IT-RN": "Rimini",
  "IT-RM": "Roma",
  "IT-RO": "Rovigo",
  "IT-SA": "Salerno",
  "IT-SS": "Sassari",
  "IT-SV": "Savona",
  "IT-SI": "Siena",
  "IT-SR": "Siracusa",
  "IT-SO": "Sondrio",
  "IT-TA": "Taranto",
  "IT-TE": "Teramo",
  "IT-TR": "Terni",
  "IT-TO": "Torino",
  "IT-TP": "Trapani",
  "IT-TN": "Trento",
  "IT-TV": "Treviso",
  "IT-TS": "Trieste",
  "IT-UD": "Udine",
  "IT-VA": "Varese",
  "IT-VE": "Venezia",
  "IT-VB": "VerbanoCusioOssola",
  "IT-VC": "Vercelli",
  "IT-VR": "Verona",
  "IT-VV": "ViboValentia",
  "IT-VI": "Vicenza",
  "IT-VT": "Viterbo",
  "RS-KM": "KosovoMetohija",
  "RS-VO": "Vojvodina",
  "RU-AD": "RepublicOfAdygeya",
  "RU-AL": "RepublicOfAltay",
  "RU-BA": "RepublicOfBashkortostan",
  "RU-BU": "RepublicOfBuryatiya",
  "RU-CE": "ChechenskayaRepublic",
  "RU-CU": "ChuvashskayaRepublic",
  "RU-DA": "RepublicOfDagestan",
  "RU-IN": "RepublicOfIngushetiya",
  "RU-KB": "KabardinoBalkarskayaRepublic",
  "RU-KL": "RepublicOfKalmykiya",
  "RU-KC": "KarachayevoCherkesskayaRepublic",
  "RU-KR": "RepublicOfKareliya",
  "RU-KK": "RepublicOfKhakasiya",
  "RU-KO": "RepublicOfKomi",
  "RU-ME": "RepublicOfMariyEl",
  "RU-MO": "RepublicOfMordoviya",
  "RU-SA": "RepublicOfSakhaYakutiya",
  "RU-SE": "RepublicOfSevernayaOsetiyaAlaniya",
  "RU-TA": "RepublicOfTatarstan",
  "RU-TY": "RepublicOfTyvaTuva",
  "RU-UD": "UdmurtskayaRepublic",
  "RU-ALT": "AltayskiyAdministrativeTerritory",
  "RU-KAM": "KamchatskiyAdministrativeTerritory",
  "RU-KHA": "KhabarovskiyAdministrativeTerritory",
  "RU-KDA": "KrasnodarskiyAdministrativeTerritory",
  "RU-KYA": "KrasnoyarskiyAdministrativeTerritory",
  "RU-PER": "PermskiyAdministrativeTerritory",
  "RU-PRI": "PrimorskiyAdministrativeTerritory",
  "RU-STA": "StavropolSkiyAdministrativeTerritory",
  "RU-ZAB": "ZabaykalSkiyAdministrativeTerritory",
  "RU-AMU": "AmurskayaAdministrativeRegion",
  "RU-ARK": "ArkhangelSkayaAdministrativeRegion",
  "RU-AST": "AstrakhanskayaAdministrativeRegion",
  "RU-BEL": "BelgorodskayaAdministrativeRegion",
  "RU-BRY": "BryanskayaAdministrativeRegion",
  "RU-CHE": "ChelyabinskayaAdministrativeRegion",
  "RU-IRK": "IrkutskayaAdministrativeRegion",
  "RU-IVA": "IvanovskayaAdministrativeRegion",
  "RU-KGD": "KaliningradskayaAdministrativeRegion",
  "RU-KLU": "KaluzhskayaAdministrativeRegion",
  "RU-KEM": "KemerovskayaAdministrativeRegion",
  "RU-KIR": "KirovskayaAdministrativeRegion",
  "RU-KOS": "KostromskayaAdministrativeRegion",
  "RU-KGN": "KurganskayaAdministrativeRegion",
  "RU-KRS": "KurskayaAdministrativeRegion",
  "RU-LEN": "LeningradskayaAdministrativeRegion",
  "RU-LIP": "LipetskayaAdministrativeRegion",
  "RU-MAG": "MagadanskayaAdministrativeRegion",
  "RU-MOS": "MoskovskayaAdministrativeRegion",
  "RU-MUR": "MurmanskayaAdministrativeRegion",
  "RU-NIZ": "NizhegorodskayaAdministrativeRegion",
  "RU-NGR": "NovgorodskayaAdministrativeRegion",
  "RU-NVS": "NovosibirskayaAdministrativeRegion",
  "RU-OMS": "OmskayaAdministrativeRegion",
  "RU-ORE": "OrenburgskayaAdministrativeRegion",
  "RU-ORL": "OrlovskayaAdministrativeRegion",
  "RU-PNZ": "PenzenskayaAdministrativeRegion",
  "RU-PSK": "PskovskayaAdministrativeRegion",
  "RU-ROS": "RostovskayaAdministrativeRegion",
  "RU-RYA": "RyazanskayaAdministrativeRegion",
  "RU-SAK": "SakhalinskayaAdministrativeRegion",
  "RU-SAM": "SamarskayaAdministrativeRegion",
  "RU-SAR": "SaratovskayaAdministrativeRegion",
  "RU-SMO": "SmolenskayaAdministrativeRegion",
  "RU-SVE": "SverdlovskayaAdministrativeRegion",
  "RU-TAM": "TambovskayaAdministrativeRegion",
  "RU-TOM": "TomskayaAdministrativeRegion",
  "RU-TUL": "TulSkayaAdministrativeRegion",
  "RU-TVE": "TverskayaAdministrativeRegion",
  "RU-TYU": "TyumenskayaAdministrativeRegion",
  "RU-ULY": "UlYanovskayaAdministrativeRegion",
  "RU-VLA": "VladimirskayaAdministrativeRegion",
  "RU-VGG": "VolgogradskayaAdministrativeRegion",
  "RU-VLG": "VologodskayaAdministrativeRegion",
  "RU-VOR": "VoronezhskayaAdministrativeRegion",
  "RU-YAR": "YaroslavskayaAdministrativeRegion",
  "RU-MOW": "MoskvaCity",
  "RU-SPE": "SanktPeterburgCity",
  "RU-YEV": "YevreyskayaAutonomousAdministrativeRegion",
  "RU-CHU": "ChukotskiyAutonomousDistrict",
  "RU-KHM": "KhantyMansiyskiyAutonomousDistrict",
  "RU-NEN": "NenetskiyAutonomousDistrict",
  "RU-YAN": "YamaloNenetskiyAutonomousDistrict",
  "US-AK": "Alaska",
  "US-AL": "Alabama",
  "US-AR": "Arkansas",
  "US-AZ": "Arizona",
  "US-CA": "California",
  "US-CO": "Colorado",
  "US-CT": "Connecticut",
  "US-DC": "DistrictOfColumbia",
  "US-DE": "Delaware",
  "US-FL": "Florida",
  "US-GA": "Georgia",
  "US-HI": "Hawaii",
  "US-IA": "Iowa",
  "US-ID": "Idaho",
  "US-IL": "Illinois",
  "US-IN": "Indiana",
  "US-KS": "Kansas",
  "US-KY": "Kentucky",
  "US-LA": "Louisiana",
  "US-MA": "Massachusetts",
  "US-MD": "Maryland",
  "US-ME": "Maine",
  "US-MI": "Michigan",
  "US-MN": "Minnesota",
  "US-MO": "Missouri",
  "US-MS": "Mississippi",
  "US-MT": "Montana",
  "US-NC": "NorthCarolina",
  "US-ND": "NorthDakota",
  "US-NE": "Nebraska",
  "US-NH": "NewHampshire",
  "US-NJ": "NewJersey",
  "US-NM": "NewMexico",
  "US-NV": "Nevada",
  "US-NY": "NewYork",
  "US-OH": "Ohio",
  "US-OK": "Oklahoma",
  "US-OR": "Oregon",
  "US-PA": "Pennsylvania",
  "US-RI": "RhodeIsland",
  "US-SC": "SouthCarolina",
  "US-SD": "SouthDakota",
  "US-TN": "Tennessee",
  "US-TX": "Texas",
  "US-UT": "Utah",
  "US-VA": "Virginia",
  "US-VT": "Vermont",
  "US-WA": "Washington",
  "US-WI": "Wisconsin",
  "US-WV": "WestVirginia",
  "US-WY": "Wyoming",
  "ECZ": "Eurozone",
  "WORLD": "World",
};

export enum RegionBasedOnIso_3166_2Enum {
  AustralianCapitalTerritory = "AustralianCapitalTerritory",
  NewSouthWales = "NewSouthWales",
  NorthernTerritory = "NorthernTerritory",
  Queensland = "Queensland",
  SouthAustralia = "SouthAustralia",
  Tasmania = "Tasmania",
  Victoria = "Victoria",
  WesternAustralia = "WesternAustralia",
  BrusselsCapitalRegion = "BrusselsCapitalRegion",
  FlemishRegion = "FlemishRegion",
  WalloonRegion = "WalloonRegion",
  Alberta = "Alberta",
  BritishColumbia = "BritishColumbia",
  Manitoba = "Manitoba",
  NewBrunswick = "NewBrunswick",
  NewfoundlandAndLabrador = "NewfoundlandAndLabrador",
  NovaScotia = "NovaScotia",
  NorthwestTerritories = "NorthwestTerritories",
  Nunavut = "Nunavut",
  Ontario = "Ontario",
  PrinceEdwardIsland = "PrinceEdwardIsland",
  Quebec = "Quebec",
  Saskatchewan = "Saskatchewan",
  YukonTerritory = "YukonTerritory",
  BeijingMunicipality = "BeijingMunicipality",
  TianjinMunicipality = "TianjinMunicipality",
  HebeiProvince = "HebeiProvince",
  ShanxiProvince = "ShanxiProvince",
  InnerMongoliaAutonomousRegion = "InnerMongoliaAutonomousRegion",
  LiaoningProvince = "LiaoningProvince",
  JilinProvince = "JilinProvince",
  HeilongjiangProvince = "HeilongjiangProvince",
  ShanghaiMunicipality = "ShanghaiMunicipality",
  JiangsuProvince = "JiangsuProvince",
  ZhejiangProvince = "ZhejiangProvince",
  AnhuiProvince = "AnhuiProvince",
  FujianProvince = "FujianProvince",
  JiangxiProvince = "JiangxiProvince",
  ShandongProvince = "ShandongProvince",
  HenanProvince = "HenanProvince",
  HubeiProvince = "HubeiProvince",
  HunanProvince = "HunanProvince",
  GuangdongProvince = "GuangdongProvince",
  GuangxiZhuangAutonomousRegion = "GuangxiZhuangAutonomousRegion",
  HainanProvince = "HainanProvince",
  ChongqingMunicipality = "ChongqingMunicipality",
  SichuanProvince = "SichuanProvince",
  GuizhouProvince = "GuizhouProvince",
  YunnanProvince = "YunnanProvince",
  TibetAutonomousRegion = "TibetAutonomousRegion",
  ShaanxiProvince = "ShaanxiProvince",
  GansuProvince = "GansuProvince",
  QinghaiProvince = "QinghaiProvince",
  NingxiaHuiAutonomousRegion = "NingxiaHuiAutonomousRegion",
  XinjiangUyghurAutonomousRegion = "XinjiangUyghurAutonomousRegion",
  TaiwanProvince = "TaiwanProvince",
  HongKongSpecialAdministrativeRegion = "HongKongSpecialAdministrativeRegion",
  MacauSpecialAdministrativeRegion = "MacauSpecialAdministrativeRegion",
  CanaryIslands = "CanaryIslands",
  Corsica = "Corsica",
  UkAirside = "UkAirside",
  UkAirports = "UkAirports",
  ChannelIslands = "ChannelIslands",
  England = "England",
  EnglandWalesScotland = "EnglandWalesScotland",
  IsleOfMan = "IsleOfMan",
  NorthernIreland = "NorthernIreland",
  Scotland = "Scotland",
  Wales = "Wales",
  IrelandAirside = "IrelandAirside",
  Agrigento = "Agrigento",
  Alessandria = "Alessandria",
  Ancona = "Ancona",
  Aosta = "Aosta",
  Arezzo = "Arezzo",
  AscoliPiceno = "AscoliPiceno",
  Asti = "Asti",
  Avellino = "Avellino",
  Bari = "Bari",
  BarlettaAndriaTrani = "BarlettaAndriaTrani",
  Belluno = "Belluno",
  Benevento = "Benevento",
  Bergamo = "Bergamo",
  Biella = "Biella",
  Bologna = "Bologna",
  Bolzano = "Bolzano",
  Brescia = "Brescia",
  Brindisi = "Brindisi",
  Cagliari = "Cagliari",
  Caltanissetta = "Caltanissetta",
  Campobasso = "Campobasso",
  CarboniaIglesias = "CarboniaIglesias",
  Caserta = "Caserta",
  Catania = "Catania",
  Catanzaro = "Catanzaro",
  Chieti = "Chieti",
  Como = "Como",
  Cosenza = "Cosenza",
  Cremona = "Cremona",
  Crotone = "Crotone",
  Cuneo = "Cuneo",
  Enna = "Enna",
  Fermo = "Fermo",
  Ferrara = "Ferrara",
  Firenze = "Firenze",
  Foggia = "Foggia",
  ForlCesena = "ForlCesena",
  Frosinone = "Frosinone",
  Genova = "Genova",
  Gorizia = "Gorizia",
  Grosseto = "Grosseto",
  Imperia = "Imperia",
  Isernia = "Isernia",
  LaSpezia = "LaSpezia",
  LAquila = "LAquila",
  Latina = "Latina",
  Lecce = "Lecce",
  Lecco = "Lecco",
  Livorno = "Livorno",
  Lodi = "Lodi",
  Lucca = "Lucca",
  Macerata = "Macerata",
  Mantova = "Mantova",
  MassaCarrara = "MassaCarrara",
  Matera = "Matera",
  MedioCampidano = "MedioCampidano",
  Messina = "Messina",
  Milano = "Milano",
  Modena = "Modena",
  MonzaEBrianza = "MonzaEBrianza",
  Napoli = "Napoli",
  Novara = "Novara",
  Nuoro = "Nuoro",
  Ogliastra = "Ogliastra",
  OlbiaTempio = "OlbiaTempio",
  Oristano = "Oristano",
  Padova = "Padova",
  Palermo = "Palermo",
  Parma = "Parma",
  Pavia = "Pavia",
  Perugia = "Perugia",
  PesaroEUrbino = "PesaroEUrbino",
  Pescara = "Pescara",
  Piacenza = "Piacenza",
  Pisa = "Pisa",
  Pistoia = "Pistoia",
  Pordenone = "Pordenone",
  Potenza = "Potenza",
  Prato = "Prato",
  Ragusa = "Ragusa",
  Ravenna = "Ravenna",
  ReggioCalabria = "ReggioCalabria",
  ReggioEmilia = "ReggioEmilia",
  Rieti = "Rieti",
  Rimini = "Rimini",
  Roma = "Roma",
  Rovigo = "Rovigo",
  Salerno = "Salerno",
  Sassari = "Sassari",
  Savona = "Savona",
  Siena = "Siena",
  Siracusa = "Siracusa",
  Sondrio = "Sondrio",
  Taranto = "Taranto",
  Teramo = "Teramo",
  Terni = "Terni",
  Torino = "Torino",
  Trapani = "Trapani",
  Trento = "Trento",
  Treviso = "Treviso",
  Trieste = "Trieste",
  Udine = "Udine",
  Varese = "Varese",
  Venezia = "Venezia",
  VerbanoCusioOssola = "VerbanoCusioOssola",
  Vercelli = "Vercelli",
  Verona = "Verona",
  ViboValentia = "ViboValentia",
  Vicenza = "Vicenza",
  Viterbo = "Viterbo",
  KosovoMetohija = "KosovoMetohija",
  Vojvodina = "Vojvodina",
  RepublicOfAdygeya = "RepublicOfAdygeya",
  RepublicOfAltay = "RepublicOfAltay",
  RepublicOfBashkortostan = "RepublicOfBashkortostan",
  RepublicOfBuryatiya = "RepublicOfBuryatiya",
  ChechenskayaRepublic = "ChechenskayaRepublic",
  ChuvashskayaRepublic = "ChuvashskayaRepublic",
  RepublicOfDagestan = "RepublicOfDagestan",
  RepublicOfIngushetiya = "RepublicOfIngushetiya",
  KabardinoBalkarskayaRepublic = "KabardinoBalkarskayaRepublic",
  RepublicOfKalmykiya = "RepublicOfKalmykiya",
  KarachayevoCherkesskayaRepublic = "KarachayevoCherkesskayaRepublic",
  RepublicOfKareliya = "RepublicOfKareliya",
  RepublicOfKhakasiya = "RepublicOfKhakasiya",
  RepublicOfKomi = "RepublicOfKomi",
  RepublicOfMariyEl = "RepublicOfMariyEl",
  RepublicOfMordoviya = "RepublicOfMordoviya",
  RepublicOfSakhaYakutiya = "RepublicOfSakhaYakutiya",
  RepublicOfSevernayaOsetiyaAlaniya = "RepublicOfSevernayaOsetiyaAlaniya",
  RepublicOfTatarstan = "RepublicOfTatarstan",
  RepublicOfTyvaTuva = "RepublicOfTyvaTuva",
  UdmurtskayaRepublic = "UdmurtskayaRepublic",
  AltayskiyAdministrativeTerritory = "AltayskiyAdministrativeTerritory",
  KamchatskiyAdministrativeTerritory = "KamchatskiyAdministrativeTerritory",
  KhabarovskiyAdministrativeTerritory = "KhabarovskiyAdministrativeTerritory",
  KrasnodarskiyAdministrativeTerritory = "KrasnodarskiyAdministrativeTerritory",
  KrasnoyarskiyAdministrativeTerritory = "KrasnoyarskiyAdministrativeTerritory",
  PermskiyAdministrativeTerritory = "PermskiyAdministrativeTerritory",
  PrimorskiyAdministrativeTerritory = "PrimorskiyAdministrativeTerritory",
  StavropolSkiyAdministrativeTerritory = "StavropolSkiyAdministrativeTerritory",
  ZabaykalSkiyAdministrativeTerritory = "ZabaykalSkiyAdministrativeTerritory",
  AmurskayaAdministrativeRegion = "AmurskayaAdministrativeRegion",
  ArkhangelSkayaAdministrativeRegion = "ArkhangelSkayaAdministrativeRegion",
  AstrakhanskayaAdministrativeRegion = "AstrakhanskayaAdministrativeRegion",
  BelgorodskayaAdministrativeRegion = "BelgorodskayaAdministrativeRegion",
  BryanskayaAdministrativeRegion = "BryanskayaAdministrativeRegion",
  ChelyabinskayaAdministrativeRegion = "ChelyabinskayaAdministrativeRegion",
  IrkutskayaAdministrativeRegion = "IrkutskayaAdministrativeRegion",
  IvanovskayaAdministrativeRegion = "IvanovskayaAdministrativeRegion",
  KaliningradskayaAdministrativeRegion = "KaliningradskayaAdministrativeRegion",
  KaluzhskayaAdministrativeRegion = "KaluzhskayaAdministrativeRegion",
  KemerovskayaAdministrativeRegion = "KemerovskayaAdministrativeRegion",
  KirovskayaAdministrativeRegion = "KirovskayaAdministrativeRegion",
  KostromskayaAdministrativeRegion = "KostromskayaAdministrativeRegion",
  KurganskayaAdministrativeRegion = "KurganskayaAdministrativeRegion",
  KurskayaAdministrativeRegion = "KurskayaAdministrativeRegion",
  LeningradskayaAdministrativeRegion = "LeningradskayaAdministrativeRegion",
  LipetskayaAdministrativeRegion = "LipetskayaAdministrativeRegion",
  MagadanskayaAdministrativeRegion = "MagadanskayaAdministrativeRegion",
  MoskovskayaAdministrativeRegion = "MoskovskayaAdministrativeRegion",
  MurmanskayaAdministrativeRegion = "MurmanskayaAdministrativeRegion",
  NizhegorodskayaAdministrativeRegion = "NizhegorodskayaAdministrativeRegion",
  NovgorodskayaAdministrativeRegion = "NovgorodskayaAdministrativeRegion",
  NovosibirskayaAdministrativeRegion = "NovosibirskayaAdministrativeRegion",
  OmskayaAdministrativeRegion = "OmskayaAdministrativeRegion",
  OrenburgskayaAdministrativeRegion = "OrenburgskayaAdministrativeRegion",
  OrlovskayaAdministrativeRegion = "OrlovskayaAdministrativeRegion",
  PenzenskayaAdministrativeRegion = "PenzenskayaAdministrativeRegion",
  PskovskayaAdministrativeRegion = "PskovskayaAdministrativeRegion",
  RostovskayaAdministrativeRegion = "RostovskayaAdministrativeRegion",
  RyazanskayaAdministrativeRegion = "RyazanskayaAdministrativeRegion",
  SakhalinskayaAdministrativeRegion = "SakhalinskayaAdministrativeRegion",
  SamarskayaAdministrativeRegion = "SamarskayaAdministrativeRegion",
  SaratovskayaAdministrativeRegion = "SaratovskayaAdministrativeRegion",
  SmolenskayaAdministrativeRegion = "SmolenskayaAdministrativeRegion",
  SverdlovskayaAdministrativeRegion = "SverdlovskayaAdministrativeRegion",
  TambovskayaAdministrativeRegion = "TambovskayaAdministrativeRegion",
  TomskayaAdministrativeRegion = "TomskayaAdministrativeRegion",
  TulSkayaAdministrativeRegion = "TulSkayaAdministrativeRegion",
  TverskayaAdministrativeRegion = "TverskayaAdministrativeRegion",
  TyumenskayaAdministrativeRegion = "TyumenskayaAdministrativeRegion",
  UlYanovskayaAdministrativeRegion = "UlYanovskayaAdministrativeRegion",
  VladimirskayaAdministrativeRegion = "VladimirskayaAdministrativeRegion",
  VolgogradskayaAdministrativeRegion = "VolgogradskayaAdministrativeRegion",
  VologodskayaAdministrativeRegion = "VologodskayaAdministrativeRegion",
  VoronezhskayaAdministrativeRegion = "VoronezhskayaAdministrativeRegion",
  YaroslavskayaAdministrativeRegion = "YaroslavskayaAdministrativeRegion",
  MoskvaCity = "MoskvaCity",
  SanktPeterburgCity = "SanktPeterburgCity",
  YevreyskayaAutonomousAdministrativeRegion = "YevreyskayaAutonomousAdministrativeRegion",
  ChukotskiyAutonomousDistrict = "ChukotskiyAutonomousDistrict",
  KhantyMansiyskiyAutonomousDistrict = "KhantyMansiyskiyAutonomousDistrict",
  NenetskiyAutonomousDistrict = "NenetskiyAutonomousDistrict",
  YamaloNenetskiyAutonomousDistrict = "YamaloNenetskiyAutonomousDistrict",
  Alaska = "Alaska",
  Alabama = "Alabama",
  Arkansas = "Arkansas",
  Arizona = "Arizona",
  California = "California",
  Colorado = "Colorado",
  Connecticut = "Connecticut",
  DistrictOfColumbia = "DistrictOfColumbia",
  Delaware = "Delaware",
  Florida = "Florida",
  Georgia = "Georgia",
  Hawaii = "Hawaii",
  Iowa = "Iowa",
  Idaho = "Idaho",
  Illinois = "Illinois",
  Indiana = "Indiana",
  Kansas = "Kansas",
  Kentucky = "Kentucky",
  Louisiana = "Louisiana",
  Massachusetts = "Massachusetts",
  Maryland = "Maryland",
  Maine = "Maine",
  Michigan = "Michigan",
  Minnesota = "Minnesota",
  Missouri = "Missouri",
  Mississippi = "Mississippi",
  Montana = "Montana",
  NorthCarolina = "NorthCarolina",
  NorthDakota = "NorthDakota",
  Nebraska = "Nebraska",
  NewHampshire = "NewHampshire",
  NewJersey = "NewJersey",
  NewMexico = "NewMexico",
  Nevada = "Nevada",
  NewYork = "NewYork",
  Ohio = "Ohio",
  Oklahoma = "Oklahoma",
  Oregon = "Oregon",
  Pennsylvania = "Pennsylvania",
  RhodeIsland = "RhodeIsland",
  SouthCarolina = "SouthCarolina",
  SouthDakota = "SouthDakota",
  Tennessee = "Tennessee",
  Texas = "Texas",
  Utah = "Utah",
  Virginia = "Virginia",
  Vermont = "Vermont",
  Washington = "Washington",
  Wisconsin = "Wisconsin",
  WestVirginia = "WestVirginia",
  Wyoming = "Wyoming",
  Eurozone = "Eurozone",
  World = "World"
}
  