export const ResourceFeatureCode = {
  "01": "ImageShowsProductInPackaging",
  "02": "ImageShowsProductWithoutPackaging",
  "03": "ImageShowsProductAndAccessories",
  "04": "ImageShowsAssembledProduct",
  "05": "ImageShowsProductInUse",
  "06": "ImageShowsMultipleProducts",
  "07": "ImageShowsDetailOfProduct",
  "21": "3DPerspectiveFront",
  "22": "3DPerspectiveBack",
  "23": "3DPerspectiveFrontForedge",
  "24": "3DPerspectiveBackForedge",
  "33": "3DPerspectiveFrontLow",
  "34": "3DPerspectiveBackLow",
  "35": "3DPerspectiveFrontForedgeLow",
  "36": "3DPerspectiveBackForedgeLow",
  "41": "2DFront",
  "42": "2DBack",
  "43": "2DSpine",
  "47": "3DPerspectiveHorizontal",
  "48": "3DPerspectiveVertical",
};

export enum ResourceFeatureCodeEnum {
  ImageShowsProductInPackaging,
  ImageShowsProductWithoutPackaging,
  ImageShowsProductAndAccessories,
  ImageShowsAssembledProduct,
  ImageShowsProductInUse,
  ImageShowsMultipleProducts,
  ImageShowsDetailOfProduct,
  "3DPerspectiveFront",
  "3DPerspectiveBack",
  "3DPerspectiveFrontForedge",
  "3DPerspectiveBackForedge",
  "3DPerspectiveFrontLow",
  "3DPerspectiveBackLow",
  "3DPerspectiveFrontForedgeLow",
  "3DPerspectiveBackForedgeLow",
  "2DFront",
  "2DBack",
  "2DSpine",
  "3DPerspectiveHorizontal",
  "3DPerspectiveVertical"
}
