export const ResourceContentType = {
  "01": "FrontCover",
  "02": "BackCover",
  "03": "CoverPack",
  "04": "ContributorPicture",
  "05": "SeriesImageArtwork",
  "06": "SeriesLogo",
  "07": "ProductImageArtwork",
  "08": "ProductLogo",
  "09": "PublisherLogo",
  "10": "ImprintLogo",
  "11": "ContributorInterview",
  "12": "ContributorPresentation",
  "13": "ContributorReading",
  "14": "ContributorEventSchedule",
  "15": "SampleContent",
  "16": "Widget",
  "17": "Review",
  "18": "CommentaryDiscussion",
  "19": "ReadingGroupGuide",
  "20": "TeacherSGuide",
  "21": "FeatureArticle",
  "22": "CharacterInterview",
  "23": "WallpaperScreensaver",
  "24": "PressRelease",
  "25": "TableOfContents",
  "26": "Trailer",
  "27": "CoverThumbnail",
  "28": "FullContent",
  "29": "FullCover",
  "30": "MasterBrandLogo",
  "31": "Description",
  "32": "Index",
  "33": "StudentSGuide",
  "34": "PublisherSCatalogue",
  "35": "OnlineAdvertisementPanel",
  "36": "OnlineAdvertisementPage",
  "37": "PromotionalEventMaterial",
  "38": "DigitalReviewCopy",
  "39": "InstructionalMaterial",
  "40": "Errata",
  "41": "Introduction",
  "42": "CollectionDescription",
  "43": "Bibliography",
  "44": "Abstract",
  "45": "CoverHoldingImage",
  "46": "RulesOrInstructions",
  "47": "Transcript",
  "99": "License",
};

export enum ResourceContentTypeEnum {
  FrontCover,
  BackCover,
  CoverPack,
  ContributorPicture,
  SeriesImageArtwork,
  SeriesLogo,
  ProductImageArtwork,
  ProductLogo,
  PublisherLogo,
  ImprintLogo,
  ContributorInterview,
  ContributorPresentation,
  ContributorReading,
  ContributorEventSchedule,
  SampleContent,
  Widget,
  Review,
  CommentaryDiscussion,
  ReadingGroupGuide,
  TeacherSGuide,
  FeatureArticle,
  CharacterInterview,
  WallpaperScreensaver,
  PressRelease,
  TableOfContents,
  Trailer,
  CoverThumbnail,
  FullContent,
  FullCover,
  MasterBrandLogo,
  Description,
  Index,
  StudentSGuide,
  PublisherSCatalogue,
  OnlineAdvertisementPanel,
  OnlineAdvertisementPage,
  PromotionalEventMaterial,
  DigitalReviewCopy,
  InstructionalMaterial,
  Errata,
  Introduction,
  CollectionDescription,
  Bibliography,
  Abstract,
  CoverHoldingImage,
  RulesOrInstructions,
  Transcript,
  License
}
