// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const ResourceContentType = {
  "01": "FrontCover",
  "02": "BackCover",
  "03": "CoverPack",
  "04": "ContributorPicture",
  "05": "SeriesImageArtwork",
  "06": "SeriesLogo",
  "07": "ProductImageArtwork",
  "08": "ProductLogo",
  "09": "PublisherLogo",
  "10": "ImprintLogo",
  "11": "ContributorInterview",
  "12": "ContributorPresentation",
  "13": "ContributorReading",
  "14": "ContributorEventSchedule",
  "15": "SampleContent",
  "16": "Widget",
  "17": "Review",
  "18": "CommentaryDiscussion",
  "19": "ReadingGroupGuide",
  "20": "TeacherSGuide",
  "21": "FeatureArticle",
  "22": "CharacterInterview",
  "23": "WallpaperScreensaver",
  "24": "PressRelease",
  "25": "TableOfContents",
  "26": "Trailer",
  "27": "CoverThumbnail",
  "28": "FullContent",
  "29": "FullCover",
  "30": "MasterBrandLogo",
  "31": "Description",
  "32": "Index",
  "33": "StudentSGuide",
  "34": "PublisherSCatalogue",
  "35": "OnlineAdvertisementPanel",
  "36": "OnlineAdvertisementPage",
  "37": "PromotionalEventMaterial",
  "38": "DigitalReviewCopy",
  "39": "InstructionalMaterial",
  "40": "Errata",
  "41": "Introduction",
  "42": "CollectionDescription",
  "43": "Bibliography",
  "44": "Abstract",
  "45": "CoverHoldingImage",
  "46": "RulesOrInstructions",
  "47": "Transcript",
  "99": "License",
};

export enum ResourceContentTypeEnum {
  FrontCover = "FrontCover",
  BackCover = "BackCover",
  CoverPack = "CoverPack",
  ContributorPicture = "ContributorPicture",
  SeriesImageArtwork = "SeriesImageArtwork",
  SeriesLogo = "SeriesLogo",
  ProductImageArtwork = "ProductImageArtwork",
  ProductLogo = "ProductLogo",
  PublisherLogo = "PublisherLogo",
  ImprintLogo = "ImprintLogo",
  ContributorInterview = "ContributorInterview",
  ContributorPresentation = "ContributorPresentation",
  ContributorReading = "ContributorReading",
  ContributorEventSchedule = "ContributorEventSchedule",
  SampleContent = "SampleContent",
  Widget = "Widget",
  Review = "Review",
  CommentaryDiscussion = "CommentaryDiscussion",
  ReadingGroupGuide = "ReadingGroupGuide",
  TeacherSGuide = "TeacherSGuide",
  FeatureArticle = "FeatureArticle",
  CharacterInterview = "CharacterInterview",
  WallpaperScreensaver = "WallpaperScreensaver",
  PressRelease = "PressRelease",
  TableOfContents = "TableOfContents",
  Trailer = "Trailer",
  CoverThumbnail = "CoverThumbnail",
  FullContent = "FullContent",
  FullCover = "FullCover",
  MasterBrandLogo = "MasterBrandLogo",
  Description = "Description",
  Index = "Index",
  StudentSGuide = "StudentSGuide",
  PublisherSCatalogue = "PublisherSCatalogue",
  OnlineAdvertisementPanel = "OnlineAdvertisementPanel",
  OnlineAdvertisementPage = "OnlineAdvertisementPage",
  PromotionalEventMaterial = "PromotionalEventMaterial",
  DigitalReviewCopy = "DigitalReviewCopy",
  InstructionalMaterial = "InstructionalMaterial",
  Errata = "Errata",
  Introduction = "Introduction",
  CollectionDescription = "CollectionDescription",
  Bibliography = "Bibliography",
  Abstract = "Abstract",
  CoverHoldingImage = "CoverHoldingImage",
  RulesOrInstructions = "RulesOrInstructions",
  Transcript = "Transcript",
  License = "License"
}
  