export const SalesRestrictionType = {
    "00": "UnspecifiedSeeText",
    "01": "RetailerExclusiveOwnBrand",
    "02": "ThroughOfficeSuppliesOutletsOnly",
    "03": "InternalPublisherUseOnlyDoNotList",
    "04": "RetailerExclusive",
    "05": "RetailerOwnBrand",
    "06": "ToLibrariesOnly",
    "07": "ToSchoolsOnly",
    "08": "Indiziert",
    "09": "ExceptToLibraries",
    "10": "ThroughNewsOutletsOnly",
    "11": "RetailerException",
    "12": "ExceptToSubscriptionServices",
    "13": "ToSubscriptionServicesOnly",
    "14": "ExceptThroughOnlineRetail",
    "15": "ThroughOnlineRetailOnly",
    "16": "ExceptToSchools",
    "17": "ThroughInventorylessPod",
    "18": "ThroughStockProtectionPod",
    "19": "ExceptThroughPod",
    "99": "NoRestrictionsOnSales"
};
