// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const SpecialCoverMaterial = {
  "01": "BerkshireLeather",
  "02": "Calfskin",
  "03": "FrenchMorocco",
  "04": "Morocco",
  "05": "BondedBuffaloGrain",
  "06": "BondedCalfGrain",
  "07": "BondedCordova",
  "08": "BondedEelskin",
  "09": "BondedOstraleg",
  "10": "BondedOstrich",
  "11": "BondedReptileGrain",
  "12": "BondedLeather",
  "13": "Cowhide",
  "14": "Eelskin",
  "15": "Kivar",
  "16": "Leatherflex",
  "17": "Moleskin",
  "18": "SofthideLeather",
  "19": "Metal",
  "20": "Velvet",
  "21": "MotherOfPearl",
  "22": "Papyrus",
  "23": "GLtexWibalin",
  "24": "GuaflexSkivertex",
  "25": "ImitationLeather",
  "26": "Pigskin",
  "27": "Goatskin",
};

export enum SpecialCoverMaterialEnum {
  BerkshireLeather = "BerkshireLeather",
  Calfskin = "Calfskin",
  FrenchMorocco = "FrenchMorocco",
  Morocco = "Morocco",
  BondedBuffaloGrain = "BondedBuffaloGrain",
  BondedCalfGrain = "BondedCalfGrain",
  BondedCordova = "BondedCordova",
  BondedEelskin = "BondedEelskin",
  BondedOstraleg = "BondedOstraleg",
  BondedOstrich = "BondedOstrich",
  BondedReptileGrain = "BondedReptileGrain",
  BondedLeather = "BondedLeather",
  Cowhide = "Cowhide",
  Eelskin = "Eelskin",
  Kivar = "Kivar",
  Leatherflex = "Leatherflex",
  Moleskin = "Moleskin",
  SofthideLeather = "SofthideLeather",
  Metal = "Metal",
  Velvet = "Velvet",
  MotherOfPearl = "MotherOfPearl",
  Papyrus = "Papyrus",
  GLtexWibalin = "GLtexWibalin",
  GuaflexSkivertex = "GuaflexSkivertex",
  ImitationLeather = "ImitationLeather",
  Pigskin = "Pigskin",
  Goatskin = "Goatskin"
}
  