// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const SubjectSchemeIdentifier = {
  "01": "Dewey",
  "02": "AbridgedDewey",
  "03": "LcClassification",
  "04": "LcSubjectHeading",
  "05": "NlmClassification",
  "06": "MeShHeading",
  "07": "NalSubjectHeading",
  "08": "Aat",
  "09": "Udc",
  "10": "BisacSubjectHeading",
  "11": "BisacRegionalTheme",
  "12": "BicSubjectCategory",
  "13": "BicGeographicalQualifier",
  "14": "BicLanguageQualifierLanguageAsSubject",
  "15": "BicTimePeriodQualifier",
  "16": "BicEducationalPurposeQualifier",
  "17": "BicReadingLevelAndSpecialInterestQualifier",
  "18": "DdcSachgruppenDerDeutschenNationalbibliografie",
  "19": "LcFictionGenreHeading",
  "20": "Keywords",
  "21": "BicChildrenSBookMarketingCategory",
  "22": "BisacMerchandisingTheme",
  "23": "PublisherSOwnCategoryCode",
  "24": "ProprietarySubjectScheme",
  "25": "TablaDeMateriasIsbn",
  "26": "WarengruppenSystematikDesDeutschenBuchhandels",
  "27": "Swd",
  "28": "ThMesElectre",
  "29": "ClilClassificationThMatique",
  "30": "DnbSachgruppen",
  "31": "Nugi",
  "32": "Nur",
  "33": "EcpaChristianBookCategory",
  "34": "Siso",
  "35": "KoreanDecimalClassificationKdc",
  "36": "DdcDeutsch_22",
  "37": "Bokgrupper",
  "38": "Varegrupper",
  "39": "LReplanerKl06",
  "40": "NipponDecimalClassification",
  "41": "Bsq",
  "42": "AneleMaterias",
  "43": "Utdanningsprogram",
  "44": "ProgramomrDe",
  "45": "Undervisningsmateriell",
  "46": "NorskDdk",
  "47": "Varugrupper",
  "48": "Sab",
  "49": "LRomedelstyp",
  "50": "FRhandsbeskrivning",
  "51": "SpanishIsbnUdcSubset",
  "52": "EciSubjectCategories",
  "53": "SoggettoCce",
  "54": "QualificatoreGeograficoCce",
  "55": "QualificatoreDiLinguaCce",
  "56": "QualificatoreDiPeriodoStoricoCce",
  "57": "QualificatoreDiLivelloScolasticoCce",
  "58": "QualificatoreDiEtDiLetturaCce",
  "59": "VdSBildungsmedienFCher",
  "60": "Fagkoder",
  "61": "JelClassification",
  "62": "Csh",
  "63": "Rvm",
  "64": "Ysa",
  "65": "AllRs",
  "66": "Ykl",
  "67": "Musa",
  "68": "Cilla",
  "69": "Kaunokki",
  "70": "Bella",
  "71": "Yso",
  "72": "PaikkatietoOntologia",
  "73": "SuomalainenKirjaAlanLuokitus",
  "74": "Sears",
  "75": "BicE4L",
  "76": "Csr",
  "77": "SuomalainenOppiaineluokitus",
  "78": "JapaneseBookTradeCCode",
  "79": "JapaneseBookTradeGenreCode",
  "80": "FiktiivisenAineistonLisLuokitus",
  "81": "ArabicSubjectHeadingScheme",
  "82": "ArabizedBicSubjectCategory",
  "83": "ArabizedLcSubjectHeadings",
  "84": "BibliothecaAlexandrinaSubjectHeadings",
  "85": "PostalCode",
  "86": "GeoNamesId",
  "87": "NewBooksSubjectClassification",
  "88": "ChineseLibraryClassification",
  "89": "NtcpdsacClassification",
  "90": "SeasonAndEventIndicator",
  "91": "Gnd",
  "92": "BicUkslc",
  "93": "ThemaSubjectCategory",
  "94": "ThemaPlaceQualifier",
  "95": "ThemaLanguageQualifier",
  "96": "ThemaTimePeriodQualifier",
  "97": "ThemaEducationalPurposeQualifier",
  "98": "ThemaInterestAgeSpecialInterestQualifier",
  "99": "ThemaStyleQualifier",
  "A2": "Mnesord",
  "A3": "StatystykaKsiEkPapierowychMWionychIElektronicznych",
  "A4": "Ccss",
  "A5": "Rameau",
  "A6": "NomenclatureDisciplineScolaire",
  "A7": "Isic",
  "A8": "LcChildrenSSubjectHeadings",
  "A9": "NyLRomedel",
  "B0": "EuroVoc",
  "B1": "BisgEducationalTaxonomy",
  "B2": "KeywordsNotForDisplay",
  "B3": "NomenclatureDiplMe",
  "B4": "KeyCharacterNames",
  "B5": "KeyPlaceNames",
  "B6": "Fast",
  "B7": "Ngss",
  "B8": "MvbLesemotive",
  "B9": "Lops21SubjectModule",
  "C0": "LReplanerLk20",
  "C1": "KompetansemLLk20",
  "C2": "KompetansemLsettLk20",
  "C3": "TverrfagligeTemaerLk20",
  "C4": "ClilTypeDArticleScolaire",
  "C5": "GarTypePDagogique",
};

export enum SubjectSchemeIdentifierEnum {
  Dewey = "Dewey",
  AbridgedDewey = "AbridgedDewey",
  LcClassification = "LcClassification",
  LcSubjectHeading = "LcSubjectHeading",
  NlmClassification = "NlmClassification",
  MeShHeading = "MeShHeading",
  NalSubjectHeading = "NalSubjectHeading",
  Aat = "Aat",
  Udc = "Udc",
  BisacSubjectHeading = "BisacSubjectHeading",
  BisacRegionalTheme = "BisacRegionalTheme",
  BicSubjectCategory = "BicSubjectCategory",
  BicGeographicalQualifier = "BicGeographicalQualifier",
  BicLanguageQualifierLanguageAsSubject = "BicLanguageQualifierLanguageAsSubject",
  BicTimePeriodQualifier = "BicTimePeriodQualifier",
  BicEducationalPurposeQualifier = "BicEducationalPurposeQualifier",
  BicReadingLevelAndSpecialInterestQualifier = "BicReadingLevelAndSpecialInterestQualifier",
  DdcSachgruppenDerDeutschenNationalbibliografie = "DdcSachgruppenDerDeutschenNationalbibliografie",
  LcFictionGenreHeading = "LcFictionGenreHeading",
  Keywords = "Keywords",
  BicChildrenSBookMarketingCategory = "BicChildrenSBookMarketingCategory",
  BisacMerchandisingTheme = "BisacMerchandisingTheme",
  PublisherSOwnCategoryCode = "PublisherSOwnCategoryCode",
  ProprietarySubjectScheme = "ProprietarySubjectScheme",
  TablaDeMateriasIsbn = "TablaDeMateriasIsbn",
  WarengruppenSystematikDesDeutschenBuchhandels = "WarengruppenSystematikDesDeutschenBuchhandels",
  Swd = "Swd",
  ThMesElectre = "ThMesElectre",
  ClilClassificationThMatique = "ClilClassificationThMatique",
  DnbSachgruppen = "DnbSachgruppen",
  Nugi = "Nugi",
  Nur = "Nur",
  EcpaChristianBookCategory = "EcpaChristianBookCategory",
  Siso = "Siso",
  KoreanDecimalClassificationKdc = "KoreanDecimalClassificationKdc",
  DdcDeutsch_22 = "DdcDeutsch_22",
  Bokgrupper = "Bokgrupper",
  Varegrupper = "Varegrupper",
  LReplanerKl06 = "LReplanerKl06",
  NipponDecimalClassification = "NipponDecimalClassification",
  Bsq = "Bsq",
  AneleMaterias = "AneleMaterias",
  Utdanningsprogram = "Utdanningsprogram",
  ProgramomrDe = "ProgramomrDe",
  Undervisningsmateriell = "Undervisningsmateriell",
  NorskDdk = "NorskDdk",
  Varugrupper = "Varugrupper",
  Sab = "Sab",
  LRomedelstyp = "LRomedelstyp",
  FRhandsbeskrivning = "FRhandsbeskrivning",
  SpanishIsbnUdcSubset = "SpanishIsbnUdcSubset",
  EciSubjectCategories = "EciSubjectCategories",
  SoggettoCce = "SoggettoCce",
  QualificatoreGeograficoCce = "QualificatoreGeograficoCce",
  QualificatoreDiLinguaCce = "QualificatoreDiLinguaCce",
  QualificatoreDiPeriodoStoricoCce = "QualificatoreDiPeriodoStoricoCce",
  QualificatoreDiLivelloScolasticoCce = "QualificatoreDiLivelloScolasticoCce",
  QualificatoreDiEtDiLetturaCce = "QualificatoreDiEtDiLetturaCce",
  VdSBildungsmedienFCher = "VdSBildungsmedienFCher",
  Fagkoder = "Fagkoder",
  JelClassification = "JelClassification",
  Csh = "Csh",
  Rvm = "Rvm",
  Ysa = "Ysa",
  AllRs = "AllRs",
  Ykl = "Ykl",
  Musa = "Musa",
  Cilla = "Cilla",
  Kaunokki = "Kaunokki",
  Bella = "Bella",
  Yso = "Yso",
  PaikkatietoOntologia = "PaikkatietoOntologia",
  SuomalainenKirjaAlanLuokitus = "SuomalainenKirjaAlanLuokitus",
  Sears = "Sears",
  BicE4L = "BicE4L",
  Csr = "Csr",
  SuomalainenOppiaineluokitus = "SuomalainenOppiaineluokitus",
  JapaneseBookTradeCCode = "JapaneseBookTradeCCode",
  JapaneseBookTradeGenreCode = "JapaneseBookTradeGenreCode",
  FiktiivisenAineistonLisLuokitus = "FiktiivisenAineistonLisLuokitus",
  ArabicSubjectHeadingScheme = "ArabicSubjectHeadingScheme",
  ArabizedBicSubjectCategory = "ArabizedBicSubjectCategory",
  ArabizedLcSubjectHeadings = "ArabizedLcSubjectHeadings",
  BibliothecaAlexandrinaSubjectHeadings = "BibliothecaAlexandrinaSubjectHeadings",
  PostalCode = "PostalCode",
  GeoNamesId = "GeoNamesId",
  NewBooksSubjectClassification = "NewBooksSubjectClassification",
  ChineseLibraryClassification = "ChineseLibraryClassification",
  NtcpdsacClassification = "NtcpdsacClassification",
  SeasonAndEventIndicator = "SeasonAndEventIndicator",
  Gnd = "Gnd",
  BicUkslc = "BicUkslc",
  ThemaSubjectCategory = "ThemaSubjectCategory",
  ThemaPlaceQualifier = "ThemaPlaceQualifier",
  ThemaLanguageQualifier = "ThemaLanguageQualifier",
  ThemaTimePeriodQualifier = "ThemaTimePeriodQualifier",
  ThemaEducationalPurposeQualifier = "ThemaEducationalPurposeQualifier",
  ThemaInterestAgeSpecialInterestQualifier = "ThemaInterestAgeSpecialInterestQualifier",
  ThemaStyleQualifier = "ThemaStyleQualifier",
  Mnesord = "Mnesord",
  StatystykaKsiEkPapierowychMWionychIElektronicznych = "StatystykaKsiEkPapierowychMWionychIElektronicznych",
  Ccss = "Ccss",
  Rameau = "Rameau",
  NomenclatureDisciplineScolaire = "NomenclatureDisciplineScolaire",
  Isic = "Isic",
  LcChildrenSSubjectHeadings = "LcChildrenSSubjectHeadings",
  NyLRomedel = "NyLRomedel",
  EuroVoc = "EuroVoc",
  BisgEducationalTaxonomy = "BisgEducationalTaxonomy",
  KeywordsNotForDisplay = "KeywordsNotForDisplay",
  NomenclatureDiplMe = "NomenclatureDiplMe",
  KeyCharacterNames = "KeyCharacterNames",
  KeyPlaceNames = "KeyPlaceNames",
  Fast = "Fast",
  Ngss = "Ngss",
  MvbLesemotive = "MvbLesemotive",
  Lops21SubjectModule = "Lops21SubjectModule",
  LReplanerLk20 = "LReplanerLk20",
  KompetansemLLk20 = "KompetansemLLk20",
  KompetansemLsettLk20 = "KompetansemLsettLk20",
  TverrfagligeTemaerLk20 = "TverrfagligeTemaerLk20",
  ClilTypeDArticleScolaire = "ClilTypeDArticleScolaire",
  GarTypePDagogique = "GarTypePDagogique"
}
  