// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const SupportingResourceFileFormat = {
  "A103": "Mp3",
  "A104": "Wav",
  "A105": "RealAudio",
  "A106": "Wma",
  "A107": "Aac",
  "A108": "OggVorbis",
  "A111": "Aiff",
  "D101": "RealVideo",
  "D102": "Quicktime",
  "D103": "Avi",
  "D104": "Wmv",
  "D105": "Mpeg_4",
  "D106": "Flv",
  "D107": "Swf",
  "D108": "3Gp",
  "D109": "WebM",
  "D401": "Pdf",
  "D501": "Gif",
  "D502": "Jpeg",
  "D503": "Png",
  "D504": "Tiff",
  "D505": "Bmp",
  "D506": "Jp2",
  "D507": "Psd",
  "D508": "Eps",
  "E101": "Epub",
  "E105": "Html",
  "E107": "Pdf",
  "E112": "Txt",
  "E113": "Xhtml",
  "E115": "Xps",
  "E116": "AmazonKindle",
  "E139": "Ceb",
  "E140": "Cebx",
};

export enum SupportingResourceFileFormatEnum {
  Mp3,
  Wav,
  RealAudio,
  Wma,
  Aac,
  OggVorbis,
  Aiff,
  RealVideo,
  Quicktime,
  Avi,
  Wmv,
  Mpeg_4,
  Flv,
  Swf,
  "3Gp",
  WebM,
  Pdf,
  Gif,
  Jpeg,
  Png,
  Tiff,
  Bmp,
  Jp2,
  Psd,
  Eps,
  Epub,
  Html,
  Txt,
  Xhtml,
  Xps,
  AmazonKindle,
  Ceb,
  Cebx
}
  