// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const SupportingResourceFileFormat = {
  "A103": "Mp3",
  "A104": "Wav",
  "A105": "RealAudio",
  "A106": "Wma",
  "A107": "Aac",
  "A108": "OggVorbis",
  "A111": "Aiff",
  "D101": "RealVideo",
  "D102": "Quicktime",
  "D103": "Avi",
  "D104": "Wmv",
  "D105": "Mpeg_4",
  "D106": "Flv",
  "D107": "Swf",
  "D108": "3Gp",
  "D109": "WebM",
  "D401": "Pdf",
  "D501": "Gif",
  "D502": "Jpeg",
  "D503": "Png",
  "D504": "Tiff",
  "D505": "Bmp",
  "D506": "Jp2",
  "D507": "Psd",
  "D508": "Eps",
  "E101": "Epub",
  "E105": "Html",
  "E107": "Pdf",
  "E112": "Txt",
  "E113": "Xhtml",
  "E115": "Xps",
  "E116": "AmazonKindle",
  "E139": "Ceb",
  "E140": "Cebx",
};

export enum SupportingResourceFileFormatEnum {
  Mp3 = "Mp3",
  Wav = "Wav",
  RealAudio = "RealAudio",
  Wma = "Wma",
  Aac = "Aac",
  OggVorbis = "OggVorbis",
  Aiff = "Aiff",
  RealVideo = "RealVideo",
  Quicktime = "Quicktime",
  Avi = "Avi",
  Wmv = "Wmv",
  Mpeg_4 = "Mpeg_4",
  Flv = "Flv",
  Swf = "Swf",
  "3Gp" = "3Gp",
  WebM = "WebM",
  Pdf = "Pdf",
  Gif = "Gif",
  Jpeg = "Jpeg",
  Png = "Png",
  Tiff = "Tiff",
  Bmp = "Bmp",
  Jp2 = "Jp2",
  Psd = "Psd",
  Eps = "Eps",
  Epub = "Epub",
  Html = "Html",
  Txt = "Txt",
  Xhtml = "Xhtml",
  Xps = "Xps",
  AmazonKindle = "AmazonKindle",
  Ceb = "Ceb",
  Cebx = "Cebx"
}
  