// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const TextScriptBasedOnIso_15924 = {
  "Adlm": "Adlam",
  "Afak": "Afaka",
  "Aghb": "CaucasianAlbanian",
  "Ahom": "AhomTaiAhom",
  "Arab": "Arabic",
  "Aran": "ArabicNastaliqVariant",
  "Armi": "ImperialAramaic",
  "Armn": "Armenian",
  "Avst": "Avestan",
  "Bali": "Balinese",
  "Bamu": "Bamun",
  "Bass": "BassaVah",
  "Batk": "Batak",
  "Beng": "BengaliBangla",
  "Bhks": "Bhaiksuki",
  "Blis": "Blissymbols",
  "Bopo": "Bopomofo",
  "Brah": "Brahmi",
  "Brai": "Braille",
  "Bugi": "Buginese",
  "Buhd": "Buhid",
  "Cakm": "Chakma",
  "Cans": "UnifiedCanadianAboriginalSyllabics",
  "Cari": "Carian",
  "Cham": "Cham",
  "Cher": "Cherokee",
  "Cirt": "Cirth",
  "Copt": "Coptic",
  "Cprt": "Cypriot",
  "Cyrl": "Cyrillic",
  "Cyrs": "CyrillicOldChurchSlavonicVariant",
  "Deva": "DevanagariNagari",
  "Dogr": "Dogra",
  "Dsrt": "DeseretMormon",
  "Dupl": "DuployanShorthandDuployanStenography",
  "Egyd": "EgyptianDemotic",
  "Egyh": "EgyptianHieratic",
  "Egyp": "EgyptianHieroglyphs",
  "Elba": "Elbasan",
  "Ethi": "EthiopicGeEz",
  "Geok": "KhutsuriAsomtavruliAndKhutsuri",
  "Geor": "GeorgianMkhedruliAndMtavruli",
  "Glag": "Glagolitic",
  "Gong": "GunjalaGondi",
  "Gonm": "MasaramGondi",
  "Goth": "Gothic",
  "Gran": "Grantha",
  "Grek": "Greek",
  "Gujr": "Gujarati",
  "Guru": "Gurmukhi",
  "Hanb": "HanWithBopomofo",
  "Hang": "HangulHangLHangeul",
  "Hani": "HanHanziKanjiHanja",
  "Hano": "HanunooHanunO",
  "Hans": "HanSimplifiedVariant",
  "Hant": "HanTraditionalVariant",
  "Hatr": "Hatran",
  "Hebr": "Hebrew",
  "Hira": "Hiragana",
  "Hluw": "AnatolianHieroglyphsLuwianHieroglyphsHittiteHieroglyphs",
  "Hmng": "PahawhHmong",
  "Hrkt": "JapaneseSyllabariesAliasForHiraganaKatakana",
  "Hung": "OldHungarianHungarianRunic",
  "Inds": "IndusHarappan",
  "Ital": "OldItalicEtruscanOscanEtc",
  "Jamo": "JamoAliasForJamoSubsetOfHangul",
  "Java": "Javanese",
  "Jpan": "JapaneseAliasForHanHiraganaKatakana",
  "Jurc": "Jurchen",
  "Kali": "KayahLi",
  "Kana": "Katakana",
  "Khar": "Kharoshthi",
  "Khmr": "Khmer",
  "Khoj": "Khojki",
  "Kitl": "KhitanLargeScript",
  "Kits": "KhitanSmallScript",
  "Knda": "Kannada",
  "Kore": "KoreanAliasForHangulHan",
  "Kpel": "Kpelle",
  "Kthi": "Kaithi",
  "Lana": "TaiThamLanna",
  "Laoo": "Lao",
  "Latf": "LatinFrakturVariant",
  "Latg": "LatinGaelicVariant",
  "Latn": "Latin",
  "Leke": "Leke",
  "Lepc": "LepchaRNg",
  "Limb": "Limbu",
  "Lina": "LinearA",
  "Linb": "LinearB",
  "Lisu": "LisuFraser",
  "Loma": "Loma",
  "Lyci": "Lycian",
  "Lydi": "Lydian",
  "Mahj": "Mahajani",
  "Maka": "Makasar",
  "Mand": "MandaicMandaean",
  "Mani": "Manichaean",
  "Marc": "Marchen",
  "Maya": "MayanHieroglyphs",
  "Medf": "MedefaidrinOberiOkaimeOberiKaim",
  "Mend": "MendeKikakui",
  "Merc": "MeroiticCursive",
  "Mero": "MeroiticHieroglyphs",
  "Mlym": "Malayalam",
  "Modi": "ModiMo",
  "Mong": "Mongolian",
  "Moon": "MoonMoonCodeMoonScriptMoonType",
  "Mroo": "MroMru",
  "Mtei": "MeiteiMayekMeitheiMeetei",
  "Mult": "Multani",
  "Mymr": "MyanmarBurmese",
  "Narb": "OldNorthArabianAncientNorthArabian",
  "Nbat": "Nabatean",
  "Newa": "NewaNewarNewariNepLaLipi",
  "Nkgb": "NakhiGebaNaKhiGgBawNaxiGeba",
  "Nkoo": "NKo",
  "Nshu": "NShu",
  "Ogam": "Ogham",
  "Olck": "OlChikiOlCemetOlSantali",
  "Orkh": "OldTurkicOrkhonRunic",
  "Orya": "OriyaOdia",
  "Osge": "Osage",
  "Osma": "Osmanya",
  "Palm": "Palmyrene",
  "Pauc": "PauCinHau",
  "Perm": "OldPermic",
  "Phag": "PhagsPa",
  "Phli": "InscriptionalPahlavi",
  "Phlp": "PsalterPahlavi",
  "Phlv": "BookPahlavi",
  "Phnx": "Phoenician",
  "Plrd": "MiaoPollard",
  "Piqd": "KlingonKliPlqaD",
  "Prti": "InscriptionalParthian",
  "Qaaa": "ReservedForPrivateUseStart",
  "Qabx": "ReservedForPrivateUseEnd",
  "Rjng": "RejangRedjangKaganga",
  "Roro": "Rongorongo",
  "Runr": "Runic",
  "Samr": "Samaritan",
  "Sara": "Sarati",
  "Sarb": "OldSouthArabian",
  "Saur": "Saurashtra",
  "Sgnw": "SignWriting",
  "Shaw": "ShavianShaw",
  "Shrd": "SharadaRad",
  "Sidd": "SiddhamSiddhaSiddhamTK",
  "Sind": "KhudawadiSindhi",
  "Sinh": "Sinhala",
  "Sora": "SoraSompeng",
  "Soyo": "Soyombo",
  "Sund": "Sundanese",
  "Sylo": "SylotiNagri",
  "Syrc": "Syriac",
  "Syre": "SyriacEstrangeloVariant",
  "Syrj": "SyriacWesternVariant",
  "Syrn": "SyriacEasternVariant",
  "Tagb": "Tagbanwa",
  "Takr": "TakriKrKr",
  "Tale": "TaiLe",
  "Talu": "NewTaiLue",
  "Taml": "Tamil",
  "Tang": "Tangut",
  "Tavt": "TaiViet",
  "Telu": "Telugu",
  "Teng": "Tengwar",
  "Tfng": "TifinaghBerber",
  "Tglg": "TagalogBaybayinAlibata",
  "Thaa": "Thaana",
  "Thai": "Thai",
  "Tibt": "Tibetan",
  "Tirh": "Tirhuta",
  "Ugar": "Ugaritic",
  "Vaii": "Vai",
  "Visp": "VisibleSpeech",
  "Wara": "WarangCitiVarangKshiti",
  "Wole": "Woleai",
  "Xpeo": "OldPersian",
  "Xsux": "CuneiformSumeroAkkadian",
  "Yiii": "Yi",
  "Zanb": "ZanabazarSquareZanabazarinDRbLjinUsegXewteeDRbLjinBicigHorizontalSquareScript",
  "Zinh": "CodeForInheritedScript",
  "Zmth": "MathematicalNotation",
  "Zsye": "SymbolsEmojiVariant",
  "Zsym": "Symbols",
  "Zxxx": "CodeForUnwrittenDocuments",
  "Zyyy": "CodeForUndeterminedScript",
  "Zzzz": "CodeForUncodedScript",
};

export enum TextScriptBasedOnIso_15924Enum {
  Adlam,
  Afaka,
  CaucasianAlbanian,
  AhomTaiAhom,
  Arabic,
  ArabicNastaliqVariant,
  ImperialAramaic,
  Armenian,
  Avestan,
  Balinese,
  Bamun,
  BassaVah,
  Batak,
  BengaliBangla,
  Bhaiksuki,
  Blissymbols,
  Bopomofo,
  Brahmi,
  Braille,
  Buginese,
  Buhid,
  Chakma,
  UnifiedCanadianAboriginalSyllabics,
  Carian,
  Cham,
  Cherokee,
  Cirth,
  Coptic,
  Cypriot,
  Cyrillic,
  CyrillicOldChurchSlavonicVariant,
  DevanagariNagari,
  Dogra,
  DeseretMormon,
  DuployanShorthandDuployanStenography,
  EgyptianDemotic,
  EgyptianHieratic,
  EgyptianHieroglyphs,
  Elbasan,
  EthiopicGeEz,
  KhutsuriAsomtavruliAndKhutsuri,
  GeorgianMkhedruliAndMtavruli,
  Glagolitic,
  GunjalaGondi,
  MasaramGondi,
  Gothic,
  Grantha,
  Greek,
  Gujarati,
  Gurmukhi,
  HanWithBopomofo,
  HangulHangLHangeul,
  HanHanziKanjiHanja,
  HanunooHanunO,
  HanSimplifiedVariant,
  HanTraditionalVariant,
  Hatran,
  Hebrew,
  Hiragana,
  AnatolianHieroglyphsLuwianHieroglyphsHittiteHieroglyphs,
  PahawhHmong,
  JapaneseSyllabariesAliasForHiraganaKatakana,
  OldHungarianHungarianRunic,
  IndusHarappan,
  OldItalicEtruscanOscanEtc,
  JamoAliasForJamoSubsetOfHangul,
  Javanese,
  JapaneseAliasForHanHiraganaKatakana,
  Jurchen,
  KayahLi,
  Katakana,
  Kharoshthi,
  Khmer,
  Khojki,
  KhitanLargeScript,
  KhitanSmallScript,
  Kannada,
  KoreanAliasForHangulHan,
  Kpelle,
  Kaithi,
  TaiThamLanna,
  Lao,
  LatinFrakturVariant,
  LatinGaelicVariant,
  Latin,
  Leke,
  LepchaRNg,
  Limbu,
  LinearA,
  LinearB,
  LisuFraser,
  Loma,
  Lycian,
  Lydian,
  Mahajani,
  Makasar,
  MandaicMandaean,
  Manichaean,
  Marchen,
  MayanHieroglyphs,
  MedefaidrinOberiOkaimeOberiKaim,
  MendeKikakui,
  MeroiticCursive,
  MeroiticHieroglyphs,
  Malayalam,
  ModiMo,
  Mongolian,
  MoonMoonCodeMoonScriptMoonType,
  MroMru,
  MeiteiMayekMeitheiMeetei,
  Multani,
  MyanmarBurmese,
  OldNorthArabianAncientNorthArabian,
  Nabatean,
  NewaNewarNewariNepLaLipi,
  NakhiGebaNaKhiGgBawNaxiGeba,
  NKo,
  NShu,
  Ogham,
  OlChikiOlCemetOlSantali,
  OldTurkicOrkhonRunic,
  OriyaOdia,
  Osage,
  Osmanya,
  Palmyrene,
  PauCinHau,
  OldPermic,
  PhagsPa,
  InscriptionalPahlavi,
  PsalterPahlavi,
  BookPahlavi,
  Phoenician,
  MiaoPollard,
  KlingonKliPlqaD,
  InscriptionalParthian,
  ReservedForPrivateUseStart,
  ReservedForPrivateUseEnd,
  RejangRedjangKaganga,
  Rongorongo,
  Runic,
  Samaritan,
  Sarati,
  OldSouthArabian,
  Saurashtra,
  SignWriting,
  ShavianShaw,
  SharadaRad,
  SiddhamSiddhaSiddhamTK,
  KhudawadiSindhi,
  Sinhala,
  SoraSompeng,
  Soyombo,
  Sundanese,
  SylotiNagri,
  Syriac,
  SyriacEstrangeloVariant,
  SyriacWesternVariant,
  SyriacEasternVariant,
  Tagbanwa,
  TakriKrKr,
  TaiLe,
  NewTaiLue,
  Tamil,
  Tangut,
  TaiViet,
  Telugu,
  Tengwar,
  TifinaghBerber,
  TagalogBaybayinAlibata,
  Thaana,
  Thai,
  Tibetan,
  Tirhuta,
  Ugaritic,
  Vai,
  VisibleSpeech,
  WarangCitiVarangKshiti,
  Woleai,
  OldPersian,
  CuneiformSumeroAkkadian,
  Yi,
  ZanabazarSquareZanabazarinDRbLjinUsegXewteeDRbLjinBicigHorizontalSquareScript,
  CodeForInheritedScript,
  MathematicalNotation,
  SymbolsEmojiVariant,
  Symbols,
  CodeForUnwrittenDocuments,
  CodeForUndeterminedScript,
  CodeForUncodedScript
}
  