// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const TextType = {
  "01": "SenderDefinedText",
  "02": "ShortDescriptionAnnotation",
  "03": "Description",
  "04": "TableOfContents",
  "05": "PrimaryCoverCopy",
  "06": "ReviewQuote",
  "07": "ReviewQuotePreviousEdition",
  "08": "ReviewQuotePreviousWork",
  "09": "Endorsement",
  "10": "PromotionalHeadline",
  "11": "Feature",
  "12": "BiographicalNote",
  "13": "PublisherSNotice",
  "14": "Excerpt",
  "15": "Index",
  "16": "ShortDescriptionAnnotationForCollection",
  "17": "DescriptionForCollection",
  "18": "NewFeature",
  "19": "VersionHistory",
  "20": "OpenAccessStatement",
  "21": "DigitalExclusivityStatement",
  "22": "OfficialRecommendation",
  "23": "JbpaDescription",
  "24": "SchemaOrgSnippet",
  "25": "Errata",
  "26": "Introduction",
  "27": "SecondaryCoverCopy",
  "28": "FullCastAndCreditList",
  "29": "Bibliography",
  "30": "Abstract",
  "31": "RulesOrInstructions",
  "32": "ListOfContents",
};

export enum TextTypeEnum {
  SenderDefinedText = "SenderDefinedText",
  ShortDescriptionAnnotation = "ShortDescriptionAnnotation",
  Description = "Description",
  TableOfContents = "TableOfContents",
  PrimaryCoverCopy = "PrimaryCoverCopy",
  ReviewQuote = "ReviewQuote",
  ReviewQuotePreviousEdition = "ReviewQuotePreviousEdition",
  ReviewQuotePreviousWork = "ReviewQuotePreviousWork",
  Endorsement = "Endorsement",
  PromotionalHeadline = "PromotionalHeadline",
  Feature = "Feature",
  BiographicalNote = "BiographicalNote",
  PublisherSNotice = "PublisherSNotice",
  Excerpt = "Excerpt",
  Index = "Index",
  ShortDescriptionAnnotationForCollection = "ShortDescriptionAnnotationForCollection",
  DescriptionForCollection = "DescriptionForCollection",
  NewFeature = "NewFeature",
  VersionHistory = "VersionHistory",
  OpenAccessStatement = "OpenAccessStatement",
  DigitalExclusivityStatement = "DigitalExclusivityStatement",
  OfficialRecommendation = "OfficialRecommendation",
  JbpaDescription = "JbpaDescription",
  SchemaOrgSnippet = "SchemaOrgSnippet",
  Errata = "Errata",
  Introduction = "Introduction",
  SecondaryCoverCopy = "SecondaryCoverCopy",
  FullCastAndCreditList = "FullCastAndCreditList",
  Bibliography = "Bibliography",
  Abstract = "Abstract",
  RulesOrInstructions = "RulesOrInstructions",
  ListOfContents = "ListOfContents"
}
  