// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const TextScriptBasedOnIso_15924 = {
  "Adlm": "Adlam",
  "Afak": "Afaka",
  "Aghb": "CaucasianAlbanian",
  "Ahom": "AhomTaiAhom",
  "Arab": "Arabic",
  "Aran": "ArabicNastaliqVariant",
  "Armi": "ImperialAramaic",
  "Armn": "Armenian",
  "Avst": "Avestan",
  "Bali": "Balinese",
  "Bamu": "Bamun",
  "Bass": "BassaVah",
  "Batk": "Batak",
  "Beng": "BengaliBangla",
  "Bhks": "Bhaiksuki",
  "Blis": "Blissymbols",
  "Bopo": "Bopomofo",
  "Brah": "Brahmi",
  "Brai": "Braille",
  "Bugi": "Buginese",
  "Buhd": "Buhid",
  "Cakm": "Chakma",
  "Cans": "UnifiedCanadianAboriginalSyllabics",
  "Cari": "Carian",
  "Cham": "Cham",
  "Cher": "Cherokee",
  "Cirt": "Cirth",
  "Copt": "Coptic",
  "Cprt": "Cypriot",
  "Cyrl": "Cyrillic",
  "Cyrs": "CyrillicOldChurchSlavonicVariant",
  "Deva": "DevanagariNagari",
  "Dogr": "Dogra",
  "Dsrt": "DeseretMormon",
  "Dupl": "DuployanShorthandDuployanStenography",
  "Egyd": "EgyptianDemotic",
  "Egyh": "EgyptianHieratic",
  "Egyp": "EgyptianHieroglyphs",
  "Elba": "Elbasan",
  "Ethi": "EthiopicGeEz",
  "Geok": "KhutsuriAsomtavruliAndKhutsuri",
  "Geor": "GeorgianMkhedruliAndMtavruli",
  "Glag": "Glagolitic",
  "Gong": "GunjalaGondi",
  "Gonm": "MasaramGondi",
  "Goth": "Gothic",
  "Gran": "Grantha",
  "Grek": "Greek",
  "Gujr": "Gujarati",
  "Guru": "Gurmukhi",
  "Hanb": "HanWithBopomofo",
  "Hang": "HangulHangLHangeul",
  "Hani": "HanHanziKanjiHanja",
  "Hano": "HanunooHanunO",
  "Hans": "HanSimplifiedVariant",
  "Hant": "HanTraditionalVariant",
  "Hatr": "Hatran",
  "Hebr": "Hebrew",
  "Hira": "Hiragana",
  "Hluw": "AnatolianHieroglyphsLuwianHieroglyphsHittiteHieroglyphs",
  "Hmng": "PahawhHmong",
  "Hrkt": "JapaneseSyllabariesAliasForHiraganaKatakana",
  "Hung": "OldHungarianHungarianRunic",
  "Inds": "IndusHarappan",
  "Ital": "OldItalicEtruscanOscanEtc",
  "Jamo": "JamoAliasForJamoSubsetOfHangul",
  "Java": "Javanese",
  "Jpan": "JapaneseAliasForHanHiraganaKatakana",
  "Jurc": "Jurchen",
  "Kali": "KayahLi",
  "Kana": "Katakana",
  "Khar": "Kharoshthi",
  "Khmr": "Khmer",
  "Khoj": "Khojki",
  "Kitl": "KhitanLargeScript",
  "Kits": "KhitanSmallScript",
  "Knda": "Kannada",
  "Kore": "KoreanAliasForHangulHan",
  "Kpel": "Kpelle",
  "Kthi": "Kaithi",
  "Lana": "TaiThamLanna",
  "Laoo": "Lao",
  "Latf": "LatinFrakturVariant",
  "Latg": "LatinGaelicVariant",
  "Latn": "Latin",
  "Leke": "Leke",
  "Lepc": "LepchaRNg",
  "Limb": "Limbu",
  "Lina": "LinearA",
  "Linb": "LinearB",
  "Lisu": "LisuFraser",
  "Loma": "Loma",
  "Lyci": "Lycian",
  "Lydi": "Lydian",
  "Mahj": "Mahajani",
  "Maka": "Makasar",
  "Mand": "MandaicMandaean",
  "Mani": "Manichaean",
  "Marc": "Marchen",
  "Maya": "MayanHieroglyphs",
  "Medf": "MedefaidrinOberiOkaimeOberiKaim",
  "Mend": "MendeKikakui",
  "Merc": "MeroiticCursive",
  "Mero": "MeroiticHieroglyphs",
  "Mlym": "Malayalam",
  "Modi": "ModiMo",
  "Mong": "Mongolian",
  "Moon": "MoonMoonCodeMoonScriptMoonType",
  "Mroo": "MroMru",
  "Mtei": "MeiteiMayekMeitheiMeetei",
  "Mult": "Multani",
  "Mymr": "MyanmarBurmese",
  "Narb": "OldNorthArabianAncientNorthArabian",
  "Nbat": "Nabatean",
  "Newa": "NewaNewarNewariNepLaLipi",
  "Nkgb": "NakhiGebaNaKhiGgBawNaxiGeba",
  "Nkoo": "NKo",
  "Nshu": "NShu",
  "Ogam": "Ogham",
  "Olck": "OlChikiOlCemetOlSantali",
  "Orkh": "OldTurkicOrkhonRunic",
  "Orya": "OriyaOdia",
  "Osge": "Osage",
  "Osma": "Osmanya",
  "Palm": "Palmyrene",
  "Pauc": "PauCinHau",
  "Perm": "OldPermic",
  "Phag": "PhagsPa",
  "Phli": "InscriptionalPahlavi",
  "Phlp": "PsalterPahlavi",
  "Phlv": "BookPahlavi",
  "Phnx": "Phoenician",
  "Plrd": "MiaoPollard",
  "Piqd": "KlingonKliPlqaD",
  "Prti": "InscriptionalParthian",
  "Qaaa": "ReservedForPrivateUseStart",
  "Qabx": "ReservedForPrivateUseEnd",
  "Rjng": "RejangRedjangKaganga",
  "Roro": "Rongorongo",
  "Runr": "Runic",
  "Samr": "Samaritan",
  "Sara": "Sarati",
  "Sarb": "OldSouthArabian",
  "Saur": "Saurashtra",
  "Sgnw": "SignWriting",
  "Shaw": "ShavianShaw",
  "Shrd": "SharadaRad",
  "Sidd": "SiddhamSiddhaSiddhamTK",
  "Sind": "KhudawadiSindhi",
  "Sinh": "Sinhala",
  "Sora": "SoraSompeng",
  "Soyo": "Soyombo",
  "Sund": "Sundanese",
  "Sylo": "SylotiNagri",
  "Syrc": "Syriac",
  "Syre": "SyriacEstrangeloVariant",
  "Syrj": "SyriacWesternVariant",
  "Syrn": "SyriacEasternVariant",
  "Tagb": "Tagbanwa",
  "Takr": "TakriKrKr",
  "Tale": "TaiLe",
  "Talu": "NewTaiLue",
  "Taml": "Tamil",
  "Tang": "Tangut",
  "Tavt": "TaiViet",
  "Telu": "Telugu",
  "Teng": "Tengwar",
  "Tfng": "TifinaghBerber",
  "Tglg": "TagalogBaybayinAlibata",
  "Thaa": "Thaana",
  "Thai": "Thai",
  "Tibt": "Tibetan",
  "Tirh": "Tirhuta",
  "Ugar": "Ugaritic",
  "Vaii": "Vai",
  "Visp": "VisibleSpeech",
  "Wara": "WarangCitiVarangKshiti",
  "Wole": "Woleai",
  "Xpeo": "OldPersian",
  "Xsux": "CuneiformSumeroAkkadian",
  "Yiii": "Yi",
  "Zanb": "ZanabazarSquareZanabazarinDRbLjinUsegXewteeDRbLjinBicigHorizontalSquareScript",
  "Zinh": "CodeForInheritedScript",
  "Zmth": "MathematicalNotation",
  "Zsye": "SymbolsEmojiVariant",
  "Zsym": "Symbols",
  "Zxxx": "CodeForUnwrittenDocuments",
  "Zyyy": "CodeForUndeterminedScript",
  "Zzzz": "CodeForUncodedScript",
};

export enum TextScriptBasedOnIso_15924Enum {
  Adlam = "Adlam",
  Afaka = "Afaka",
  CaucasianAlbanian = "CaucasianAlbanian",
  AhomTaiAhom = "AhomTaiAhom",
  Arabic = "Arabic",
  ArabicNastaliqVariant = "ArabicNastaliqVariant",
  ImperialAramaic = "ImperialAramaic",
  Armenian = "Armenian",
  Avestan = "Avestan",
  Balinese = "Balinese",
  Bamun = "Bamun",
  BassaVah = "BassaVah",
  Batak = "Batak",
  BengaliBangla = "BengaliBangla",
  Bhaiksuki = "Bhaiksuki",
  Blissymbols = "Blissymbols",
  Bopomofo = "Bopomofo",
  Brahmi = "Brahmi",
  Braille = "Braille",
  Buginese = "Buginese",
  Buhid = "Buhid",
  Chakma = "Chakma",
  UnifiedCanadianAboriginalSyllabics = "UnifiedCanadianAboriginalSyllabics",
  Carian = "Carian",
  Cham = "Cham",
  Cherokee = "Cherokee",
  Cirth = "Cirth",
  Coptic = "Coptic",
  Cypriot = "Cypriot",
  Cyrillic = "Cyrillic",
  CyrillicOldChurchSlavonicVariant = "CyrillicOldChurchSlavonicVariant",
  DevanagariNagari = "DevanagariNagari",
  Dogra = "Dogra",
  DeseretMormon = "DeseretMormon",
  DuployanShorthandDuployanStenography = "DuployanShorthandDuployanStenography",
  EgyptianDemotic = "EgyptianDemotic",
  EgyptianHieratic = "EgyptianHieratic",
  EgyptianHieroglyphs = "EgyptianHieroglyphs",
  Elbasan = "Elbasan",
  EthiopicGeEz = "EthiopicGeEz",
  KhutsuriAsomtavruliAndKhutsuri = "KhutsuriAsomtavruliAndKhutsuri",
  GeorgianMkhedruliAndMtavruli = "GeorgianMkhedruliAndMtavruli",
  Glagolitic = "Glagolitic",
  GunjalaGondi = "GunjalaGondi",
  MasaramGondi = "MasaramGondi",
  Gothic = "Gothic",
  Grantha = "Grantha",
  Greek = "Greek",
  Gujarati = "Gujarati",
  Gurmukhi = "Gurmukhi",
  HanWithBopomofo = "HanWithBopomofo",
  HangulHangLHangeul = "HangulHangLHangeul",
  HanHanziKanjiHanja = "HanHanziKanjiHanja",
  HanunooHanunO = "HanunooHanunO",
  HanSimplifiedVariant = "HanSimplifiedVariant",
  HanTraditionalVariant = "HanTraditionalVariant",
  Hatran = "Hatran",
  Hebrew = "Hebrew",
  Hiragana = "Hiragana",
  AnatolianHieroglyphsLuwianHieroglyphsHittiteHieroglyphs = "AnatolianHieroglyphsLuwianHieroglyphsHittiteHieroglyphs",
  PahawhHmong = "PahawhHmong",
  JapaneseSyllabariesAliasForHiraganaKatakana = "JapaneseSyllabariesAliasForHiraganaKatakana",
  OldHungarianHungarianRunic = "OldHungarianHungarianRunic",
  IndusHarappan = "IndusHarappan",
  OldItalicEtruscanOscanEtc = "OldItalicEtruscanOscanEtc",
  JamoAliasForJamoSubsetOfHangul = "JamoAliasForJamoSubsetOfHangul",
  Javanese = "Javanese",
  JapaneseAliasForHanHiraganaKatakana = "JapaneseAliasForHanHiraganaKatakana",
  Jurchen = "Jurchen",
  KayahLi = "KayahLi",
  Katakana = "Katakana",
  Kharoshthi = "Kharoshthi",
  Khmer = "Khmer",
  Khojki = "Khojki",
  KhitanLargeScript = "KhitanLargeScript",
  KhitanSmallScript = "KhitanSmallScript",
  Kannada = "Kannada",
  KoreanAliasForHangulHan = "KoreanAliasForHangulHan",
  Kpelle = "Kpelle",
  Kaithi = "Kaithi",
  TaiThamLanna = "TaiThamLanna",
  Lao = "Lao",
  LatinFrakturVariant = "LatinFrakturVariant",
  LatinGaelicVariant = "LatinGaelicVariant",
  Latin = "Latin",
  Leke = "Leke",
  LepchaRNg = "LepchaRNg",
  Limbu = "Limbu",
  LinearA = "LinearA",
  LinearB = "LinearB",
  LisuFraser = "LisuFraser",
  Loma = "Loma",
  Lycian = "Lycian",
  Lydian = "Lydian",
  Mahajani = "Mahajani",
  Makasar = "Makasar",
  MandaicMandaean = "MandaicMandaean",
  Manichaean = "Manichaean",
  Marchen = "Marchen",
  MayanHieroglyphs = "MayanHieroglyphs",
  MedefaidrinOberiOkaimeOberiKaim = "MedefaidrinOberiOkaimeOberiKaim",
  MendeKikakui = "MendeKikakui",
  MeroiticCursive = "MeroiticCursive",
  MeroiticHieroglyphs = "MeroiticHieroglyphs",
  Malayalam = "Malayalam",
  ModiMo = "ModiMo",
  Mongolian = "Mongolian",
  MoonMoonCodeMoonScriptMoonType = "MoonMoonCodeMoonScriptMoonType",
  MroMru = "MroMru",
  MeiteiMayekMeitheiMeetei = "MeiteiMayekMeitheiMeetei",
  Multani = "Multani",
  MyanmarBurmese = "MyanmarBurmese",
  OldNorthArabianAncientNorthArabian = "OldNorthArabianAncientNorthArabian",
  Nabatean = "Nabatean",
  NewaNewarNewariNepLaLipi = "NewaNewarNewariNepLaLipi",
  NakhiGebaNaKhiGgBawNaxiGeba = "NakhiGebaNaKhiGgBawNaxiGeba",
  NKo = "NKo",
  NShu = "NShu",
  Ogham = "Ogham",
  OlChikiOlCemetOlSantali = "OlChikiOlCemetOlSantali",
  OldTurkicOrkhonRunic = "OldTurkicOrkhonRunic",
  OriyaOdia = "OriyaOdia",
  Osage = "Osage",
  Osmanya = "Osmanya",
  Palmyrene = "Palmyrene",
  PauCinHau = "PauCinHau",
  OldPermic = "OldPermic",
  PhagsPa = "PhagsPa",
  InscriptionalPahlavi = "InscriptionalPahlavi",
  PsalterPahlavi = "PsalterPahlavi",
  BookPahlavi = "BookPahlavi",
  Phoenician = "Phoenician",
  MiaoPollard = "MiaoPollard",
  KlingonKliPlqaD = "KlingonKliPlqaD",
  InscriptionalParthian = "InscriptionalParthian",
  ReservedForPrivateUseStart = "ReservedForPrivateUseStart",
  ReservedForPrivateUseEnd = "ReservedForPrivateUseEnd",
  RejangRedjangKaganga = "RejangRedjangKaganga",
  Rongorongo = "Rongorongo",
  Runic = "Runic",
  Samaritan = "Samaritan",
  Sarati = "Sarati",
  OldSouthArabian = "OldSouthArabian",
  Saurashtra = "Saurashtra",
  SignWriting = "SignWriting",
  ShavianShaw = "ShavianShaw",
  SharadaRad = "SharadaRad",
  SiddhamSiddhaSiddhamTK = "SiddhamSiddhaSiddhamTK",
  KhudawadiSindhi = "KhudawadiSindhi",
  Sinhala = "Sinhala",
  SoraSompeng = "SoraSompeng",
  Soyombo = "Soyombo",
  Sundanese = "Sundanese",
  SylotiNagri = "SylotiNagri",
  Syriac = "Syriac",
  SyriacEstrangeloVariant = "SyriacEstrangeloVariant",
  SyriacWesternVariant = "SyriacWesternVariant",
  SyriacEasternVariant = "SyriacEasternVariant",
  Tagbanwa = "Tagbanwa",
  TakriKrKr = "TakriKrKr",
  TaiLe = "TaiLe",
  NewTaiLue = "NewTaiLue",
  Tamil = "Tamil",
  Tangut = "Tangut",
  TaiViet = "TaiViet",
  Telugu = "Telugu",
  Tengwar = "Tengwar",
  TifinaghBerber = "TifinaghBerber",
  TagalogBaybayinAlibata = "TagalogBaybayinAlibata",
  Thaana = "Thaana",
  Thai = "Thai",
  Tibetan = "Tibetan",
  Tirhuta = "Tirhuta",
  Ugaritic = "Ugaritic",
  Vai = "Vai",
  VisibleSpeech = "VisibleSpeech",
  WarangCitiVarangKshiti = "WarangCitiVarangKshiti",
  Woleai = "Woleai",
  OldPersian = "OldPersian",
  CuneiformSumeroAkkadian = "CuneiformSumeroAkkadian",
  Yi = "Yi",
  ZanabazarSquareZanabazarinDRbLjinUsegXewteeDRbLjinBicigHorizontalSquareScript = "ZanabazarSquareZanabazarinDRbLjinUsegXewteeDRbLjinBicigHorizontalSquareScript",
  CodeForInheritedScript = "CodeForInheritedScript",
  MathematicalNotation = "MathematicalNotation",
  SymbolsEmojiVariant = "SymbolsEmojiVariant",
  Symbols = "Symbols",
  CodeForUnwrittenDocuments = "CodeForUnwrittenDocuments",
  CodeForUndeterminedScript = "CodeForUndeterminedScript",
  CodeForUncodedScript = "CodeForUncodedScript"
}
  