export const TradeCategory = {
  "01": "UkOpenMarketEdition",
  "02": "AirportEdition",
  "03": "Sonderausgabe",
  "04": "PocketBook",
  "05": "InternationalEditionUs",
  "06": "LibraryAudioEdition",
  "07": "UsOpenMarketEdition",
  "08": "LivreScolaireDClarParLDiteur",
  "09": "LivreScolaireNonSpCifi",
  "10": "SupplementToNewspaper",
  "11": "PrecioLibreTextbook",
  "12": "NewsOutletEdition",
  "13": "UsTextbook",
  "14": "EBookShort",
  "15": "SuperpocketBook",
  "16": "BeauLivre",
  "17": "Podcast",
  "18": "Periodical",
};

export enum TradeCategoryEnum {
  UkOpenMarketEdition,
  AirportEdition,
  Sonderausgabe,
  PocketBook,
  InternationalEditionUs,
  LibraryAudioEdition,
  UsOpenMarketEdition,
  LivreScolaireDClarParLDiteur,
  LivreScolaireNonSpCifi,
  SupplementToNewspaper,
  PrecioLibreTextbook,
  NewsOutletEdition,
  UsTextbook,
  EBookShort,
  SuperpocketBook,
  BeauLivre,
  Podcast,
  Periodical
}
