// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const UnitOfUsage = {
  "01": "Copies",
  "02": "Characters",
  "03": "Words",
  "04": "Pages",
  "05": "Percentage",
  "06": "Devices",
  "07": "ConcurrentUsers",
  "15": "Users",
  "19": "ConcurrentClasses",
  "20": "Classes",
  "31": "Institutions",
  "08": "PercentagePerTimePeriod",
  "09": "Days",
  "13": "Weeks",
  "14": "Months",
  "16": "HoursMinutesAndSeconds",
  "27": "DaysFixedStart",
  "28": "WeeksFixedStart",
  "29": "MonthsFixedStart",
  "10": "Times",
  "22": "TimesPerDay",
  "23": "TimesPerMonth",
  "24": "TimesPerYear",
  "21": "DotsPerInch",
  "26": "DotsPerCm",
  "11": "AllowedUsageStartPage",
  "12": "AllowedUsageEndPage",
  "17": "AllowedUsageStartTime",
  "18": "AllowedUsageEndTime",
  "98": "ValidFrom",
  "99": "ValidTo",
};

export enum UnitOfUsageEnum {
  Copies,
  Characters,
  Words,
  Pages,
  Percentage,
  Devices,
  ConcurrentUsers,
  Users,
  ConcurrentClasses,
  Classes,
  Institutions,
  PercentagePerTimePeriod,
  Days,
  Weeks,
  Months,
  HoursMinutesAndSeconds,
  DaysFixedStart,
  WeeksFixedStart,
  MonthsFixedStart,
  Times,
  TimesPerDay,
  TimesPerMonth,
  TimesPerYear,
  DotsPerInch,
  DotsPerCm,
  AllowedUsageStartPage,
  AllowedUsageEndPage,
  AllowedUsageStartTime,
  AllowedUsageEndTime,
  ValidFrom,
  ValidTo
}
  