export const UsAndCanadaExcludingQuBecSchoolOrCollegeGrade = {
  "P": "Preschool",
  "K": "Kindergarten",
  "1": "FirstGrade",
  "2": "SecondGrade",
  "3": "ThirdGrade",
  "4": "FourthGrade",
  "5": "FifthGrade",
  "6": "SixthGrade",
  "7": "SeventhGrade",
  "8": "EighthGrade",
  "9": "NinthGrade",
  "10": "TenthGrade",
  "11": "EleventhGrade",
  "12": "TwelfthGrade",
  "13": "CollegeFreshman",
  "14": "CollegeSophomore",
  "15": "CollegeJunior",
  "16": "CollegeSenior",
  "17": "CollegeGraduateStudent",
};

export enum UsAndCanadaExcludingQuBecSchoolOrCollegeGradeEnum {
  Preschool,
  Kindergarten,
  FirstGrade,
  SecondGrade,
  ThirdGrade,
  FourthGrade,
  FifthGrade,
  SixthGrade,
  SeventhGrade,
  EighthGrade,
  NinthGrade,
  TenthGrade,
  EleventhGrade,
  TwelfthGrade,
  CollegeFreshman,
  CollegeSophomore,
  CollegeJunior,
  CollegeSenior,
  CollegeGraduateStudent
}
