// -----------------------------------
// This file is generated. Do not edit
// -----------------------------------
export const WebsiteRole = {
  "00": "UnspecifiedSeeWebsiteDescription",
  "01": "PublisherSCorporateWebsite",
  "02": "PublisherSWebsiteForASpecifiedWork",
  "03": "OnlineHostingServiceHomePage",
  "04": "JournalHomePage",
  "05": "OnlineResourceAvailableContentPage",
  "06": "ContributorSOwnWebsite",
  "07": "PublisherSWebsiteRelatingToSpecifiedContributor",
  "08": "OtherPublisherSWebsiteRelatingToSpecifiedContributor",
  "09": "ThirdPartyWebsiteRelatingToSpecifiedContributor",
  "10": "ContributorSOwnWebsiteForSpecifiedWork",
  "11": "OtherPublisherSWebsiteRelatingToSpecifiedWork",
  "12": "ThirdPartyWebsiteRelatingToSpecifiedWork",
  "13": "ContributorSOwnWebsiteForGroupOrSeriesOfWorks",
  "14": "PublisherSWebsiteRelatingToGroupOrSeriesOfWorks",
  "15": "OtherPublisherSWebsiteRelatingToGroupOrSeriesOfWorks",
  "16": "ThirdPartyWebsiteRelatingToGroupOrSeriesOfWorksEgAFanSite",
  "17": "PublisherSB2BWebsite",
  "18": "PublisherSB2CWebsite",
  "23": "AuthorBlog",
  "24": "WebPageForAuthorPresentationCommentary",
  "25": "WebPageForAuthorInterview",
  "26": "WebPageForAuthorReading",
  "27": "WebPageForCoverMaterial",
  "28": "WebPageForSampleContent",
  "29": "WebPageForFullContent",
  "30": "WebPageForOtherCommentaryDiscussion",
  "31": "TransferUrl",
  "32": "DoiWebsiteLink",
  "33": "SupplierSCorporateWebsite",
  "34": "SupplierSB2BWebsite",
  "35": "SupplierSB2CWebsite",
  "36": "SupplierSWebsiteForASpecifiedWork",
  "37": "SupplierSB2BWebsiteForASpecifiedWork",
  "38": "SupplierSB2CWebsiteForASpecifiedWork",
  "39": "SupplierSWebsiteForAGroupOrSeriesOfWorks",
  "40": "UrlOfFullMetadataDescription",
  "41": "SocialNetworkingUrlForSpecificWorkOrProduct",
  "42": "AuthorSSocialNetworkingUrl",
  "43": "PublisherSSocialNetworkingUrl",
  "44": "SocialNetworkingUrlForSpecificArticleChapterOrContentItem",
  "45": "PublisherSOrThirdPartyWebsiteForPermissionsRequests",
  "46": "PublisherSOrThirdPartyWebsiteForPrivacyStatement",
  "47": "PublisherSWebsiteForDigitalPreservation",
  "48": "ThirdPartyWebsiteForDigitalPreservation",
};

export enum WebsiteRoleEnum {
  UnspecifiedSeeWebsiteDescription = "UnspecifiedSeeWebsiteDescription",
  PublisherSCorporateWebsite = "PublisherSCorporateWebsite",
  PublisherSWebsiteForASpecifiedWork = "PublisherSWebsiteForASpecifiedWork",
  OnlineHostingServiceHomePage = "OnlineHostingServiceHomePage",
  JournalHomePage = "JournalHomePage",
  OnlineResourceAvailableContentPage = "OnlineResourceAvailableContentPage",
  ContributorSOwnWebsite = "ContributorSOwnWebsite",
  PublisherSWebsiteRelatingToSpecifiedContributor = "PublisherSWebsiteRelatingToSpecifiedContributor",
  OtherPublisherSWebsiteRelatingToSpecifiedContributor = "OtherPublisherSWebsiteRelatingToSpecifiedContributor",
  ThirdPartyWebsiteRelatingToSpecifiedContributor = "ThirdPartyWebsiteRelatingToSpecifiedContributor",
  ContributorSOwnWebsiteForSpecifiedWork = "ContributorSOwnWebsiteForSpecifiedWork",
  OtherPublisherSWebsiteRelatingToSpecifiedWork = "OtherPublisherSWebsiteRelatingToSpecifiedWork",
  ThirdPartyWebsiteRelatingToSpecifiedWork = "ThirdPartyWebsiteRelatingToSpecifiedWork",
  ContributorSOwnWebsiteForGroupOrSeriesOfWorks = "ContributorSOwnWebsiteForGroupOrSeriesOfWorks",
  PublisherSWebsiteRelatingToGroupOrSeriesOfWorks = "PublisherSWebsiteRelatingToGroupOrSeriesOfWorks",
  OtherPublisherSWebsiteRelatingToGroupOrSeriesOfWorks = "OtherPublisherSWebsiteRelatingToGroupOrSeriesOfWorks",
  ThirdPartyWebsiteRelatingToGroupOrSeriesOfWorksEgAFanSite = "ThirdPartyWebsiteRelatingToGroupOrSeriesOfWorksEgAFanSite",
  PublisherSB2BWebsite = "PublisherSB2BWebsite",
  PublisherSB2CWebsite = "PublisherSB2CWebsite",
  AuthorBlog = "AuthorBlog",
  WebPageForAuthorPresentationCommentary = "WebPageForAuthorPresentationCommentary",
  WebPageForAuthorInterview = "WebPageForAuthorInterview",
  WebPageForAuthorReading = "WebPageForAuthorReading",
  WebPageForCoverMaterial = "WebPageForCoverMaterial",
  WebPageForSampleContent = "WebPageForSampleContent",
  WebPageForFullContent = "WebPageForFullContent",
  WebPageForOtherCommentaryDiscussion = "WebPageForOtherCommentaryDiscussion",
  TransferUrl = "TransferUrl",
  DoiWebsiteLink = "DoiWebsiteLink",
  SupplierSCorporateWebsite = "SupplierSCorporateWebsite",
  SupplierSB2BWebsite = "SupplierSB2BWebsite",
  SupplierSB2CWebsite = "SupplierSB2CWebsite",
  SupplierSWebsiteForASpecifiedWork = "SupplierSWebsiteForASpecifiedWork",
  SupplierSB2BWebsiteForASpecifiedWork = "SupplierSB2BWebsiteForASpecifiedWork",
  SupplierSB2CWebsiteForASpecifiedWork = "SupplierSB2CWebsiteForASpecifiedWork",
  SupplierSWebsiteForAGroupOrSeriesOfWorks = "SupplierSWebsiteForAGroupOrSeriesOfWorks",
  UrlOfFullMetadataDescription = "UrlOfFullMetadataDescription",
  SocialNetworkingUrlForSpecificWorkOrProduct = "SocialNetworkingUrlForSpecificWorkOrProduct",
  AuthorSSocialNetworkingUrl = "AuthorSSocialNetworkingUrl",
  PublisherSSocialNetworkingUrl = "PublisherSSocialNetworkingUrl",
  SocialNetworkingUrlForSpecificArticleChapterOrContentItem = "SocialNetworkingUrlForSpecificArticleChapterOrContentItem",
  PublisherSOrThirdPartyWebsiteForPermissionsRequests = "PublisherSOrThirdPartyWebsiteForPermissionsRequests",
  PublisherSOrThirdPartyWebsiteForPrivacyStatement = "PublisherSOrThirdPartyWebsiteForPrivacyStatement",
  PublisherSWebsiteForDigitalPreservation = "PublisherSWebsiteForDigitalPreservation",
  ThirdPartyWebsiteForDigitalPreservation = "ThirdPartyWebsiteForDigitalPreservation"
}
  